apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: repositories
  namespace: flux-system
spec:
  interval: 1h
  path: "./common/repositories/helm"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system