apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: calibre
  namespace: flux-system
spec:
  image: linuxserver/calibre
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: calibre
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: calibre
  filterTags:
    pattern: '^(?P<semver>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$semver'
  policy:
    semver:
      range: '>=8.0.0 <9.0.0'
---