apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-calibre-synology
spec:
  capacity:
    storage: 10Ti  # Adjust as needed
  accessModes:
  - ReadWriteMany
  nfs:
    server: "192.168.202.1"  # Replace with your NFS server
    path: "/volume1/Media/Books"  # Replace with the path on your NFS server
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     namespace: media
     name: pvc-calibre-synology
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-calibre-synology
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: pv-calibre-synology
  storageClassName: ""