apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vikunja
  namespace: vikunja
spec:
  interval: 1m
  chart:
    spec:
      chart: vikunja
      version: 1.0.x
      sourceRef:
        kind: HelmRepository
        name: vikunja
        namespace: flux-system
  values:
    image:
      repository: vikunja/vikunja
      tag: latest
      pullPolicy: IfNotPresent

    persistence:
      data:
        enabled: true
        type: pvc
        mountPath: /app/vikunja/files
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: tasks.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: 
        secretName: kube-system/nmoura-pt-tls
        hosts:
          - tasks.nmoura.pt