apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vikunja
  namespace: vikunja
spec:
  interval: 1m
  chart:
    spec:
      chart: vikunja
      version: 1.0.x
      sourceRef:
        kind: HelmRepository
        name: vikunja
        namespace: flux-system
  values:
    vikunja: 
      image:
        repository: vikunja/vikunja
        tag: latest
        pullPolicy: IfNotPresent
  
      persistence:
        data:
          enabled: true
          type: pvc
          mountPath: /app/vikunja/files
          readOnly: false
          accessMode: ReadWriteOnce
          size: 5Gi
          retain: true
  
      ingress:
        main:
          enabled: true
          ingressClassName: traefik
          hosts:
            - host: tasks.nmoura.pt
              paths:
                - path: /
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer:   "letsencrypt-prod"
        tls: 
          secretName: nmoura-pt-tls
          hosts:
            - tasks.nmoura.pt

      env:
        VIKUNJA_DATABASE_USER: 
          valueFrom:
            secretKeyRef:
              name: vikunja-secret
              key: VIKUNJA_DATABASE_USER
        VIKUNJA_DATABASE_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: vikunja-secret
              key: VIKUNJA_DATABASE_PASSWORD "vikunja"
              
        VIKUNJA_TYPESENSE_APIKEY:
          valueFrom:
            secretKeyRef:
              name: vikunja-secret
              key: TYPESENSE_API_KEY

        VIKUNJA_MAILER_USERNAME:
          valueFrom:
            secretKeyRef:
              name: vikunja-secret
              key: SMTP_USERNAME
        VIKUNJA_MAILER_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: vikunja-secret
              key: SMTP_PASSWORD

        VIKUNJA_AUTH_OPENID_PROVIDERS_CLOUDFLARE_CLIENTID:
          valueFrom:
            secretKeyRef:
              name: vikunja-secret
              key: OID_CLIENT_ID
        VIKUNJA_AUTH_OPENID_PROVIDERS_CLOUDFLARE_CLIENTSECRET:
          valueFrom:
            secretKeyRef:
              name: vikunja-secret
              key: OID_CLIENT_SECRET

      configMaps:
        api-config:
          enabled: true
          data:
            config.yml: |
              service:
                enableregistration: false
                publicurl: "https://tasks.nmoura.pt"
                timezone: "Europe/Lisbon"
                customlogourl: "https://public.nmoura.pt/Babybites%20Instagram%20Post%20(1).png"
              database:
                type: postgres
                host: vikunja-postgresql
                database: vikunja
              typesense:
                enabled: true
                url: "http://  vikunja-typesense:8108"
              mailer:
                enabled: true
                host: "oauthmail-2465.tools.svc.cluster.local"
                port: 2465
                authtype: plain
                skiptlsverify: true
                fromemail: "vikunja@babybites.pt"
              auth:
                local:
                  enabled: false
                openid:
                  enabled: true
                  providers:
                    cloudflare:
                      name: "Cloudflare SSO"
                      authurl: "https://babybites.cloudflareaccess.com/cdn-cgi/access/sso/oidc/e91e5a14cfdd222ec71ee168678caa9678e7e9029dcd5e10034c9e6f191d719d/authorization"


    postgresql:
      enabled: true
      primary:
        networkPolicy:
          enabled: true 
      auth:
        database: vikunja
        existingSecret: vikunja-secret
        secretKeys:
          userPasswordKey: VIKUNJA_DATABASE_USER
          adminPasswordKey: VIKUNJA_DATABASE_PASSWORD

    typesense:
      enabled: true
      env:
        TYPESENSE_DATA_DIR: /data
        TYPESENSE_API_KEY:
          valueFrom:
            secretKeyRef:
              name: vikunja-secret
              key: TYPESENSE_API_KEY
      persistence:
        data:
          enabled: true
          type: pvc
          readOnly: false
          mountPath: /data
          accessMode: ReadWriteOnce
          size: 1Gi
          retain: true
          storageClass: longhorn
