apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: radarr
      version: 16.3.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/nmourapt/radarr-mkvtoolnix # {"$imagepolicy": "flux-system:radarr:name"}
      tag: 5.24.1.10017 # {"$imagepolicy": "flux-system:radarr:tag"}
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: movies.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        secretName: nmoura-pt-tls
        hosts:
          - movies.nmoura.pt
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        nameOverride: config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
      media:
        enabled: true
        mountPath: /synology
        existingClaim: pvc-radarr-synology
