apiVersion: v1
kind: Pod
metadata:
  name: prowlarr-sidecar
  namespace: media
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["sleep", "3600"]
    volumeMounts:
    - name: config
      mountPath: /config
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: prowlarr-config

