apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repositories
  namespace: flux-system
spec:
  interval: 1m  # Check every 1 minute
  path: ./kubernetes/common/repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system