---
apiVersion: v1
kind: Service
metadata:
  namespace: immich-ml
  name: immich-ml
spec:
  type: ClusterIP
  externalIPs:
    - 192.168.202.158
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
  selector:
    app: immich-ml
---