apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters:
  protocol: 'iscsi'
  dsm: '192.168.202.1'
  location: '/volume1'
reclaimPolicy: Retain
allowVolumeExpansion: true
