apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-discovery
  namespace: istio-system
spec:
  interval: 1m
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi