apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-discovery
  namespace: istio-system
spec:
  interval: 1m
  chart:
    spec:
      chart: istiod
      version: 1.0.x
      sourceRef:
        kind: HelmRepository
        name: istio/istiod
        namespace: flux-system