---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/nmourapt/k8s.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes
