# kubernetes/prod/cloudflared/cloudflared/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
  namespace: ai
spec:
  interval: 1m
  chart:
    spec:
      chart: open-webui
      version: 5.4.x
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  values:
    ollama:
      enabled: false
    ollamaUrls:
      - "http://ollama:11434"
    ingress:
      enabled: true
      class: "traefik"
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      host: "ai.nmoura.pt"
      tls: true
    extraEnvVars:
      - name: WEBUI_AUTH_TRUSTED_EMAIL_HEADER
        value: "Cf-Access-Authenticated-User-Email"
      - name: USER_PERMISSIONS_WORKSPACE_MODELS_ACCESS
        value: "true"