# kubernetes/prod/cloudflared/cloudflared/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
  namespace: ai
spec:
  interval: 1m
  chart:
    spec:
      chart: open-webui
      version: 5.4.x
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  values:
    ollama:
      enabled: false
    ollamaUrls:
      - "ollama"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
      - host: "ai.nmoura.pt"
        paths:
          - path: /
            pathType: Prefix
      tls: 
        - secretName: nmoura-pt-tls
          hosts:
            - ai.nmoura.pt