apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: sonarr
      version: 16.3.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  valuesFrom:
  - kind: Secret
    name: sonarr-secrets
    valuesKey: values.yaml
  values:
    image:
      repository: ghcr.io/nmourapt/sonarr-mkvtoolnix # {"$imagepolicy": "flux-system:sonarr:name"}
      tag: 4.0.14.2939 # {"$imagepolicy": "flux-system:sonarr:tag"}
      pullPolicy: Always
    env:
      SONARR__POSTGRES__HOST: "192.168.202.1"
      SONARR__POSTGRES__PORT: "10004"
      SONARR__AUTH__METHOD: "External"
      SONARR__AUTH__REQUIRED: "DisabledForLocalAddresses"
      
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: tv.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        secretName: nmoura-pt-tls
        hosts:
          - tv.nmoura.pt
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        nameOverride: config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
      media:
        enabled: true
        mountPath: /synology
        existingClaim: pvc-sonarr-synology

    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          exec:
            command:
            - /usr/bin/env
            - bash
            - -c
            - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while
              read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
          failureThreshold: 5
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
    