apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: sonarr
      version: 16.3.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  valuesFrom:
  - kind: Secret
    name: sonarr-secrets
    valuesKey: values.yaml
  values:
    image:
      repository: ghcr.io/nmourapt/sonarr-mkvtoolnix # {"$imagepolicy": "flux-system:sonarr:name"}
      tag: 4.0.14.2939 # {"$imagepolicy": "flux-system:sonarr:tag"}
      pullPolicy: Always
    env:
      SONARR__POSTGRES__HOST: "192.168.202.1"
      SONARR__POSTGRES__PORT: "10004"
      SONARR__AUTHENTICATION__METHOD: "external"
      
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: tv.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        secretName: nmoura-pt-tls
        hosts:
          - tv.nmoura.pt
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        nameOverride: config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
      media:
        enabled: true
        mountPath: /synology
        existingClaim: pvc-sonarr-synology
