apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: sonarr
  namespace: flux-system
spec:
  image: ghcr.io/nmourapt/sonarr-mkvtoolnix
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sonarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sonarr
  filterTags:
    pattern: '^(?P<semver>[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$semver'
  policy:
    semver:
      range: '>=4.0.0 <5.0.0'
---