apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: sonarr
  namespace: flux-system
spec:
  image: ghcr.io/nmourapt/sonarr-mkvtoolnix
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sonarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sonarr
  filterTags:
    pattern: '^(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)\.(?P<build>\d+)$'
    extract: '${major}.${minor}.${patch}.${build}'
  policy:
    alphabetical:
      order: asc
---