apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  image: ghcr.io/hotio/prowlarr
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: prowlarr
  filterTags:
    pattern: '^release-(?P<semver>[0-9]+\.[0-9]+\.[0-9]+)\.[0-9]+$'
    extract: '$semver'
  policy:
    semver:
      range: '>=2.0.0 <3.0.0'
---
