apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: adguard
spec:
  interval: 1m
  chart:
    spec:
      chart: adguard-home
      version: 5.5.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system

  values:
    controller:
      # -- Number of pods to load balance between
      replicas: 2
    
    initContainers:
    # -- Configures an initContainer that copies the configmap to the AdGuardHome conf directory
    # It does NOT overwrite when the file already exists.
    # @default -- See values.yaml
      copy-configmap:
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - "sh"
        - "-c"
        - |
          if [ ! -f /opt/adguardhome/conf/AdGuardHome.yaml ]; then
            mkdir -p /opt/adguardhome/conf
            cp /tmp/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml
          fi
        volumeMounts:
        - name: adguard-home-config
          mountPath: /tmp/AdGuardHome.yaml
          subPath: AdGuardHome.yaml
        - name: config
          mountPath: /opt/adguardhome/conf
        securityContext:
          runAsUser: 0

    image:
      repository: adguard/adguardhome
      tag: latest
      pullPolicy: IfNotPresent

    args:
      - "--config"
      - "/opt/adguardhome/conf/AdGuardHome.yaml"
      - "--work-dir"
      - "/opt/adguardhome/work"
      - "--no-check-update"
    
    service:
      main:
        primary: false
        ports:
          http:
            port: 3000
      dns-tcp:
        enabled: false
        #type: NodePort
        #ports:
        #  dns-tcp:
        #    enabled: true
        #    port: 53
        #    protocol: TCP
        #    targetPort: 53
        #externalTrafficPolicy: Local
      dns-udp:
        enabled: true
        type: LoadBalancer
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
        
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /opt/adguardhome/conf
        #nameOverride: opt-adguardhome-conf
        readOnly: false
        accessMode: ReadWriteMany
        size: 5Gi
        retain: true
      data:
        enabled: false
        #mountPath: /opt/adguardhome/work

    config: |
      bind_host: 0.0.0.0
      bind_port: 3000
      beta_bind_port: 0
      users: []
      auth_attempts: 5
      block_auth_min: 15
      http_proxy: ""
      language: ""
      debug_pprof: false
      web_session_ttl: 720
      dns:
        bind_hosts:
          - 0.0.0.0
        port: 53
        anonymize_client_ip: false
        ratelimit: 50
        ratelimit_subnet_len_ipv4: 24
        ratelimit_subnet_len_ipv6: 56
        ratelimit_whitelist: []
        refuse_any: true
        upstream_dns:
          - https://5owy17dm40.cloudflare-gateway.com/dns-query
        upstream_dns_file: ""
        bootstrap_dns:
          - 1.1.1.1
          - 9.9.9.10
        fallback_dns:
          - 8.8.8.8
          - 9.9.9.10
        upstream_mode: load_balance
        fastest_timeout: 1s
        allowed_clients: []
        disallowed_clients: []
        blocked_hosts:
          - version.bind
          - id.server
          - hostname.bind
        trusted_proxies:
          - 127.0.0.0/8
          - ::1/128
        cache_size: 4194304
        cache_ttl_min: 0
        cache_ttl_max: 0
        cache_optimistic: false
        bogus_nxdomain: []
        aaaa_disabled: false
        enable_dnssec: true
        edns_client_subnet:
          custom_ip: ""
          enabled: false
          use_custom: false
        max_goroutines: 300
        handle_ddr: true
        ipset: []
        ipset_file: ""
        bootstrap_prefer_ipv6: false
        upstream_timeout: 10s
        private_networks: []
        use_private_ptr_resolvers: false
        local_ptr_upstreams: []
        use_dns64: false
        dns64_prefixes: []
        serve_http3: false
        use_http3_upstreams: false
        serve_plain_dns: true
        hostsfile_enabled: true
      tls:
        enabled: false
        server_name: ""
        force_https: false
        port_https: 443
        port_dns_over_tls: 853
        port_dns_over_quic: 853
        port_dnscrypt: 0
        dnscrypt_config_file: ""
        allow_unencrypted_doh: false
        strict_sni_check: false
        certificate_chain: ""
        private_key: ""
        certificate_path: ""
        private_key_path: ""
      querylog:
        dir_path: ""
        ignored: []
        interval: 24h
        size_memory: 1000
        enabled: true
        file_enabled: true
      statistics:
        dir_path: ""
        ignored: []
        interval: 720h
        enabled: true
      filters:
        - enabled: true
          url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
          name: AdGuard DNS filter
          id: 1
        - enabled: true
          url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
          name: AdAway Default Blocklist
          id: 2
      whitelist_filters: []
      user_rules: []
      dhcp:
        enabled: false
        interface_name: ""
        local_domain_name: lan
        dhcpv4:
          gateway_ip: ""
          subnet_mask: ""
          range_start: ""
          range_end: ""
          lease_duration: 86400
          icmp_timeout_msec: 1000
          options: []
        dhcpv6:
          range_start: ""
          lease_duration: 86400
          ra_slaac_only: false
          ra_allow_slaac: false
      filtering:
        blocking_ipv4: ""
        blocking_ipv6: ""
        blocked_services:
          schedule:
            time_zone: UTC
          ids: []
        protection_disabled_until: null
        safe_search:
          enabled: false
          bing: true
          duckduckgo: true
          google: true
          pixabay: true
          yandex: true
          youtube: true
        blocking_mode: default
        parental_block_host: family-block.dns.adguard.com
        safebrowsing_block_host: standard-block.dns.adguard.com
        rewrites:
          - domain: matchbox.nmoura.internal
            answer: 192.168.202.2
        safebrowsing_cache_size: 1048576
        safesearch_cache_size: 1048576
        parental_cache_size: 1048576
        cache_time: 30
        filters_update_interval: 24
        blocked_response_ttl: 10
        filtering_enabled: true
        parental_enabled: false
        safebrowsing_enabled: false
        protection_enabled: true
      clients:
        runtime_sources:
          whois: true
          arp: true
          rdns: true
          dhcp: true
          hosts: true
        persistent: []
      log:
        file: ""
        max_backups: 0
        max_size: 100
        max_age: 3
        compress: false
        local_time: false
        verbose: false
      os:
        group: ""
        user: ""
        rlimit_nofile: 0
      schema_version: 28

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: adguard.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: 
        secretName: nmoura-pt-tls
        hosts:
          - adguard.nmoura.pt