apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: longhorn-mtls
  namespace: istio-ingress
spec:
  mtls:
    mode: STRICT  # Requires mTLS for all traffic
    caCertificates: /etc/certs/longhorn-ca-cert/ca.crt
  selector:
    matchLabels:
      istio: gateway