---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii
  namespace: firefly
  labels:
    app: firefly-iii
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: firefly-iii
  template:
    metadata:
      labels:
        app: firefly-iii
    spec:
      restartPolicy: Always
      containers:
      - image: fireflyiii/core
        name: firefly-iii
        env:
        - name: APP_ENV
          value: "local"
        - name: TRUSTED_PROXIES
          value: "**"
        - name: DB_HOST
          value: firefly-mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_CONNECTION
          value: mysql
        - name: DB_DATABASE
          value: "fireflyiii"
        - name: DB_USERNAME
          value: "root"
        - name: MAIL_MAILER
          value: log
        - name: MAIL_HOST
          value: oauthmail-2465.tools.svc.cluster.local
        - name: MAIL_PORT
          value: "2465"
        - name: MAIL_ENCRYPTION
          value: "null"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: firefly-iii-secret
              key: db_password
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: firefly-iii-secret
              key: app_key
        - name: MAIL_FROM
          valueFrom:
            secretKeyRef:
              name: firefly-iii-secret
              key: mail_from
        - name: MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: firefly-iii-secret
              key: mail_username
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: firefly-iii-secret
              key: mail_password
        - name: STATIC_CRON_TOKEN
          valueFrom:
            secretKeyRef:
              name: firefly-iii-secret
              key: static_cron_token
        ports:
        - containerPort: 8080
          protocol: TCP
          name: firefly-iii
        volumeMounts:
        - mountPath: "/var/www/html/storage/upload"
          name: firefly-iii-upload 
      volumes:
        - name: firefly-iii-upload
          persistentVolumeClaim:
            claimName: firefly-iii-upload