# kubernetes/prod/cloudflared/cloudflared/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: device-plugin-operator
  namespace: device-plugin-operator
spec:
  interval: 1m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.30.x
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system