---
# Image Reflector Controller Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-reflector-controller
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-reflector-controller
  template:
    metadata:
      labels:
        app: image-reflector-controller
    spec:
      containers:
      - name: manager
        image: fluxcd/image-reflector-controller:v0.31.0
        imagePullPolicy: IfNotPresent
        args:
        - --database-path=/data/badger
        - --storage-path=/data/cache
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: image-reflector-controller
      terminationGracePeriodSeconds: 10
      volumes:
      - name: data
        emptyDir: {}
---
# Image Reflector Controller Service
apiVersion: v1
kind: Service
metadata:
  name: image-reflector-controller
  namespace: flux-system
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: image-reflector-controller
  type: ClusterIP
---
# Image Automation Controller Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-automation-controller
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-automation-controller
  template:
    metadata:
      labels:
        app: image-automation-controller
    spec:
      containers:
      - name: manager
        image: fluxcd/image-automation-controller:v0.31.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: image-automation-controller
      terminationGracePeriodSeconds: 10
---
# Image Automation Controller Service
apiVersion: v1
kind: Service
metadata:
  name: image-automation-controller
  namespace: flux-system
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: image-automation-controller
  type: ClusterIP
---
# Image Reflector Controller Service Account and RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-reflector-controller
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-reflector-controller
rules:
- apiGroups: [""]
  resources: ["secrets", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["image.toolkit.fluxcd.io"]
  resources: ["imagerepositories", "imagerepositories/status", "imagepolicies", "imagepolicies/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-reflector-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-reflector-controller
subjects:
- kind: ServiceAccount
  name: image-reflector-controller
  namespace: flux-system
---
# Image Automation Controller Service Account and RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-automation-controller
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-automation-controller
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["image.toolkit.fluxcd.io"]
  resources: ["imageupdateautomations", "imageupdateautomations/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["image.toolkit.fluxcd.io"]
  resources: ["imagerepositories", "imagepolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["source.toolkit.fluxcd.io"]
  resources: ["gitrepositories", "gitrepositories/status"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-automation-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-automation-controller
subjects:
- kind: ServiceAccount
  name: image-automation-controller
  namespace: flux-system
---
# Image Repository CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagerepositories.image.toolkit.fluxcd.io
spec:
  group: image.toolkit.fluxcd.io
  names:
    kind: ImageRepository
    plural: imagerepositories
    singular: imagerepository
    shortNames:
      - imgr
  scope: Namespaced
  versions:
    - name: v1beta2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                interval:
                  type: string
            status:
              type: object
---
# Image Policy CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagepolicies.image.toolkit.fluxcd.io
spec:
  group: image.toolkit.fluxcd.io
  names:
    kind: ImagePolicy
    plural: imagepolicies
    singular: imagepolicy
    shortNames:
      - imgp
  scope: Namespaced
  versions:
    - name: v1beta2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                imageRepositoryRef:
                  type: object
                policy:
                  type: object
            status:
              type: object
---
# Image Update Automation CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imageupdateautomations.image.toolkit.fluxcd.io
spec:
  group: image.toolkit.fluxcd.io
  names:
    kind: ImageUpdateAutomation
    plural: imageupdateautomations
    singular: imageupdateautomation
    shortNames:
      - imgupd
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                interval:
                  type: string
                sourceRef:
                  type: object
                git:
                  type: object
                update:
                  type: object
            status:
              type: object