apiVersion: v1
kind: Service
metadata:
  name: image-reflector-controller
  namespace: flux-system
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: image-reflector-controller
  type: ClusterIP