# Create provider with webhook.site URL
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: gotify
  namespace: flux-system
spec:
  type: generic
  address: "https://notify.nmoura.pt/message?token=A9SePpvV_K0j9wl"
---
# Create alert for image events
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: image-alert
  namespace: flux-system
spec:
  providerRef:
    name: gotify
  eventSeverity: info
  eventSources:
  #- kind: ImageRepository
  #  name: '*'
  #- kind: ImagePolicy
  #  name: '*'
  - kind: ImageUpdateAutomation
    name: '*'