---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-pico
  namespace: firefly
  labels:
    app: firefly-pico
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: firefly-pico
  template:
    metadata:
      labels:
        app: firefly-pico
    spec:
      restartPolicy: Always
      containers:
      - image: cioraneanu/firefly-pico:latest
        name: firefly-pico
        env:
        - name: TZ
          value: Europe/Lisbon
        - name: FIREFLY_URL
          value: https://firefly.domain.com
        - name: DB_CONNECTION
          value: pgsql
        - name: DB_HOST
          value: pico-pgsql
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: firefly-pico
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: firefly-pico-secret
              key: db_username
          value: firefly-pico
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: firefly-pico-secret
              key: db_password
        ports:
        - containerPort: 80
          protocol: TCP
          name: firefly-pico

      - image: postgres:latest
        name: pico-pgsql
        env:
        - name: POSTGRES_DB
          value: firefly-pico
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: firefly-pico-secret
              key: db_username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: firefly-pico-secret
              key: db_password
        ports:
        - containerPort: 5432
          protocol: TCP
          name: pico-pgsql
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: firefly-pico-pgsql
      volumes:
        - name: firefly-pico-pgsql
          persistentVolumeClaim:
            claimName: firefly-pico-pgsql