apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: firefly-pico-app
  namespace: flux-system
spec:
  interval: 1m  # Check every 1 minute
  path: "./kubernetes/prod/firefly/firefly-iii-pico"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age