apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: lidarr
      version: 14.2.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  valuesFrom:
  - kind: Secret
    name: lidarr-secrets
    valuesKey: values.yaml
  values:
    image:
      repository: blampe/lidarr # {"$imagepolicy": "flux-system:lidarr:name"}
      tag: version-2.12.4.4658 # {"$imagepolicy": "flux-system:lidarr:tag"}
      pullPolicy: IfNotPresent
    env:
      LIDARR__POSTGRES__HOST: "192.168.202.1"
      LIDARR__POSTGRES__PORT: "10007"
      LIDARR__AUTH__METHOD: "External"
      LIDARR__AUTH__REQUIRED: "DisabledForLocalAddresses"
      DOCKER_MODS: "linuxserver/mods:lidarr-flac2mp3"
    resources:
      limits:
        gpu.intel.com/i915: 1
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
        - host: music.nmoura.pt
          paths:
          - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        secretName: nmoura-pt-tls
        hosts:
        - music.nmoura.pt
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        nameOverride: config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
      media:
        enabled: true
        mountPath: /synology
        existingClaim: pvc-lidarr-synology
    probes:
      liveness:
        enabled: false
        custom: false
