apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: lidarr
  namespace: flux-system
spec:
  image: blampe/lidarr
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: lidarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: lidarr
  filterTags:
    pattern: ^version-(?P<semver>[0-9]+\.[0-9]+\.[0-9]+)\.[0-9]+$
    extract: $semver
  policy:
    semver:
      range: ">=2.0.0 <3.0.0"
---