apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nmoura-pt
  namespace: default
spec:
  secretName: nmoura-pt-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - '*.nmoura.pt'
  - nmoura.pt