apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:31.0.7-apache # {"$imagepolicy": "flux-system:nextcloud"}
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              value: "192.168.202.1"
            - name: POSTGRES_DB
              value: "nextcloud"
            - name: POSTGRES_USER
              value: "cathouse2344"
            - name: POSTGRES_PORT
              value: "10010"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: password
            - name: REDIS_HOST
              value: "nextcloud-redis"
              
          volumeMounts:
            - mountPath: /var/www/html
              name: varwwwhtml
            #- mountPath: /config/configuration.yaml
            #  subPath: configuration.yaml
            #  name: configmap-file
      volumes:
        - name: varwwwhtml
          persistentVolumeClaim:
            claimName: pvc-nextcloud-synology
        #- name: configmap-file
        #  configMap:
        #    name: nextcloud-configmap
