apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
    initContainers:
      - name: fix-permissions
        image: busybox:1.35
        command: ['sh', '-c', 'chown -R 1059:100 /var/www/html && chmod -R 755 /var/www/html']
        volumeMounts:
          - name: varwwwhtml
            mountPath: /var/www/html
      containers:
        - name: nextcloud
          image: nextcloud:31.0.7-apache # {"$imagepolicy": "flux-system:nextcloud"}
          securityContext:
            runAsUser: 1059
            runAsGroup: 100
            fsGroup: 100
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              value: "192.168.101.66"
            - name: POSTGRES_DB
              value: "nextcloud"
            - name: POSTGRES_USER
              value: "cathouse2344"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: password
            - name: REDIS_HOST
              value: "nextcloud-redis"

          volumeMounts:
            - mountPath: /var/www/html
              name: varwwwhtml
            #- mountPath: /config/configuration.yaml
            #  subPath: configuration.yaml
            #  name: configmap-file
      volumes:
        - name: varwwwhtml
          persistentVolumeClaim:
            claimName: pvc-nextcloud-synology
        #- name: configmap-file
        #  configMap:
        #    name: nextcloud-configmap
