apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  image: nextcloud
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nextcloud
  filterTags:
    pattern: '^31\.\d+\.\d+-apache$'
    extract: '^(\d+\.\d+\.\d+)-apache$'
  policy:
    semver:
      range: '~31.0.0'