---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nextcloud-synology
spec:
  capacity:
    storage: 10Ti  # Adjust as needed
  accessModes:
  - ReadWriteMany
  nfs:
    server: "192.168.202.1"  # Replace with your NFS server
    path: "/volume1/nextcloud"  # Replace with the path on your NFS server
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     namespace: nextcloud
     name: pvc-nextcloud-synology