apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-secret
    namespace: firefly
type: Opaque
stringData:
    db_password: ENC[AES256_GCM,data:/rNXrn01x5C1u2n+uU7cbg==,iv:DmLAqX9P7E53UUi4apawLvS4hSuQFpQ0txjYS7Y8Tqg=,tag:GZS5owT3OevCaoaVKJA4ew==,type:str]
    app_key: ENC[AES256_GCM,data:+J422/PVXUlT0ewUTF5pfY9mrqpkxnwK0ePzcNMqZRA=,iv:Pz/avYZP9rbk1r03o8Gl+xnnXcQKfu5i1GThg/BBBtw=,tag:2GBfAV4E1UqKkrIkpIJ8/g==,type:str]
    mail_from: ENC[AES256_GCM,data:W3fJLWDxEc4NHkYX9Krf3SY=,iv:mX5w0mf/QLDQlxVmiiaBn8a0GN51YOYLORr0hg3A9wM=,tag:AIIhKDmZt8XAL8es8Z3CkQ==,type:str]
    mail_username: ENC[AES256_GCM,data:fkiMRRQ4UqUxKcSi84vmdSE=,iv:mWq6NweREA3LVjbVZSOSF70AY2aQsiROnYL9ugOh+nk=,tag:Cd5cq47T0l0kit7v/KJ8fw==,type:str]
    mail_password: ENC[AES256_GCM,data:RkvvHLXg5gQMAto4,iv:KYBHbfcX0y0OwmOryw4/UWcNq6emF8cv+MeGs6poZeg=,tag:0gKpfjT2w4HlvYvP6aTw5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTUljMzFnOEJNbXBuTmVz
            clRES1FYNndYUjVnMHhTMVNkRkZjSkxJMkVBCjNybjF0V2ZIa1NwNmI1TkpwTGhL
            QTZxYlMxYjVFcWJMaDY2TGx2UzRlYlUKLS0tIDNwV3ptc0JiTCs3VDZadi9CcDJ5
            UFVnd0l3cEVhdGVtL2hVK2wvakJ2bDgKTj0ALMT8Ggxm7S4I5XkHatBCBIx9AoZf
            G4UZiayOfANOCFEcTEGz1mrhSnS7woyLpXaH1ymkuOBIqGBOHNlu2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T13:15:11Z"
    mac: ENC[AES256_GCM,data:NRQxkNwgEL/4z/31YX5li8xFFNSUf2BiVB0OjiyaP0O1YDcaOrLv5pLNj8PEesnjU4n/t3Ai1WfC42SAAcU4Gha6hg3fWTTjv/jZ9H9uM13BP3K7F/KWnVnRKt6KtDtpACzdbSdr8S7Gx/FDDWpXNbvAJUGz7XFXWLxiOgFhmf4=,iv:IV1C9Mqs7ZUywEddmBX487UBvbYr9f7KjUlXE+dLXeE=,tag:o3gl4wENcYiIJNJ1dlHeVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
