apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-secret
    namespace: firefly
type: Opaque
stringData:
    db_password: ENC[AES256_GCM,data:go+0vy1sIjhTwC3OsftGCw==,iv:msZo1i23xNdhxYMv/QNYRFzpm0PUHef1vRPEwlf5mLA=,tag:gaDTGYzmoEpyT1l4oft3gw==,type:str]
    app_key: ENC[AES256_GCM,data:JfJEiDm4HYoyIffbJFa8mPhsYrvMlpMRpk1tYBdvKWA=,iv:qfj81ZqZ+QNfFwWYu5/Ak3/8S+bno8e9/y+Hem2GOzs=,tag:E+YSt2SAIw7MqXy+Mf2nfA==,type:str]
    mail_from: ENC[AES256_GCM,data:3LKpAWrUO/TtnQYoWNjSyrA=,iv:dH+BEcD56qmFJN39TsMPLwXtP5DQUSu9dlUd8bqUnGE=,tag:44AigTOI1f10kqsX8RLmVg==,type:str]
    mail_username: ENC[AES256_GCM,data:i7NqRGD0yks82AqOTvlRIyc=,iv:4DHXGTsGxFXnEYibR8r68Q+MTmOKGdKsa3udtGxQLGc=,tag:mLg9x9xOG4QctXA8vjrXKg==,type:str]
    mail_password: ENC[AES256_GCM,data:x5bKqC+bjyV3lADM,iv:7OKLw0t8z2DtgDRLshQukb28zE90yopfC2kJ62n6Ko0=,tag:q6iTjrpK3my2zcTf87NStA==,type:str]
    static_cron_token: ENC[AES256_GCM,data:7ABEAzLbMfPIuzRu7Yqn+kW67gBSEN45G2SVYkuwaMo=,iv:Sr86rGwdktsejjrJtDPI9TrRytYpP5azX12FWY8YtLY=,tag:8gudv/EOVYrSnALlgGw9mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOStMcWxNTmNWQWVxWWQ3
            YzR5ckk0M294ZkwvY3lqTFl1TmtmMXRsVUdNCjZha1lCTXVHSnZWWTBINVVGejY4
            NW1aSStsbHR3aitsU0RLZjBjcTNZQ0kKLS0tIFhWdlJJbDBPT2FDb0pQSlRjcjI1
            M2k2NjAvT2RtVXBoeVJUeHArVW5mTjQKs7B7JYtJxjstE58BE6u7K9j8X7NLxETf
            AQMjZbz8+TBxsTe15RkXyI2EykSS8sizA6P0DmxY9vyMK4mIKDZeZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T13:24:12Z"
    mac: ENC[AES256_GCM,data:Hw1LGpD+++sjjdthxG9jK52P+v0odAN+veOBo/1oow9qCDNb/COpvNBLNchsB9WE34pxt1e5uzFQD0Uap/A2E+zJJSltpxsqDq3chB1LvfHbqzSFrYY4SdexRtKm+pGLMcUhDeN/SeZoYlHmZox+GFc5rzpuRz/qgnGMHizW0Ps=,iv:WlDtvACdXTyAWmpHT5LJIXXgb44ujrTxLZSQdO0mur4=,tag:tncksRz8tTQXD76KPUZ/sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
