# kubernetes/prod/cloudflared/cloudflared/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: device-plugins-gpu
  namespace: intel-device-plugin
spec:
  interval: 1m
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.30.x
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  values:
    intel-gpu-plugin:
      sharedDevNum: 3
      resourceManager: true