apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unpackerr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: unpackerr
      version: 5.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/hotio/unpackerr
      tag: latest
      pullPolicy: IfNotPresent
          
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        nameOverride: config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
      downloads:
        enabled: true
        mountPath: /synology
        existingClaim: pvc-unpackerr-synology
    
            
      