apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unpackerr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: unpackerr
      version: 5.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/hotio/unpackerr # {"$imagepolicy": "flux-system:unpackerr:name"}
      tag: release-0.14.5 # {"$imagepolicy": "flux-system:unpackerr:tag"}
      pullPolicy: IfNotPresent
    env:
      - name: UN_SONARR_0_API_KEY
        valueFrom:
          secretKeyRef:
            name: unpackerr-secrets
            key: UN_SONARR_0_API_KEY
      - name: UN_RADARR_0_API_KEY
        valueFrom:
          secretKeyRef:
            name: unpackerr-secrets
            key: UN_RADARR_0_API_KEY
      - name: UN_READARR_0_API_KEY
        valueFrom:
          secretKeyRef:
            name: unpackerr-secrets
            key: UN_READARR_0_API_KEY
      - name: UN_WEBSERVER_METRICS
        value: false
      - name: UN_SONARR_0_URL
        value: http://sonarr:8989
      - name: UN_SONARR_0_PATHS_0
        value: /synology/torrents/series
      - name: UN_RADARR_0_URL
        value: http://radarr:7878
      - name: UN_RADARR_0_PATHS_0
        value: /synology/torrents/movies
      - name: UN_READARR_0_URL
        value: http://readarr:8787
      - name: UN_READARR_0_PATHS_0
        value: /synology/torrents/books
    persistence:
      downloads:
        enabled: true
        mountPath: /synology
        existingClaim: pvc-unpackerr-synology
