apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: unpackerr
  namespace: flux-system
spec:
  image: ghcr.io/hotio/unpackerr
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: unpackerr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: unpackerr
  filterTags:
    pattern: '^release-(?P<semver>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$semver'
  policy:
    semver:
      range: '>=0.0.0 <1.0.0'
---