apiVersion: v1
kind: ConfigMap
metadata:
  name: cross-seed-config
  namespace: media
data:
  config.js: |
    "use strict";
    // If you find yourself always using the same command-line flag, you can set
    // it here as a default.
    Object.defineProperty(exports, "__esModule", { value: true });
    module.exports = {
        delay: 10,
        torznab: ["http://prowlarr:9696/10/api?apikey=74d92c7a8d424c89b470bf869c0d740f", "http://prowlarr:9696/7/api?apikey=74d92c7a8d424c89b470bf869c0d740f", "http://prowlarr:9696/11/api?apikey=74d92c7a8d424c89b470bf869c0d740f", "http://prowlarr:9696/2/api?apikey=74d92c7a8d424c89b470bf869c0d740f", "http://prowlarr:9696/9/api?apikey=74d92c7a8d424c89b470bf869c0d740f", "http://prowlarr:9696/8/api?apikey=74d92c7a8d424c89b470bf869c0d740f", "http://prowlarr:9696/12/api?apikey=74d92c7a8d424c89b470bf869c0d740f"],
        dataDirs: undefined,
        matchMode: "safe",
        dataCategory: undefined,
        linkDir: undefined,
        linkType: "symlink",
        skipRecheck: false,
        maxDataDepth: 2,
        torrentDir: "/torrents",
        outputDir: "/cross-seeds",
        includeEpisodes: true,
        includeSingleEpisodes: true,
        includeNonVideos: true,
        fuzzySizeThreshold: 0.02,
        excludeOlder: undefined,
        excludeRecentSearch: undefined,
        action: "inject",
        rtorrentRpcUrl: undefined,
        qbittorrentUrl: "http://admin:dummy@qbittorrent:8080",
        transmissionRpcUrl: undefined,
        delugeRpcUrl: undefined,
        duplicateCategories: true,
        notificationWebhookUrl: "https://cross-seed.gotify.nmoura.pt",
        port: 2468,
        host: undefined,
        apiAuth: false,
        rssCadence: "10min",
        searchCadence: "1w",
        snatchTimeout: "5min",
        searchTimeout: "1min",
        searchLimit: undefined,
    };
    //# sourceMappingURL=config.template.docker.cjs.map