apiVersion: v1
kind: ConfigMap
metadata:
  name: cross-seed-config
  namespace: media
data:
  config.js: |
    "use strict";
    // If you find yourself always using the same command-line flag, you can set
    // it here as a default.
    Object.defineProperty(exports, "__esModule", { value: true });
    module.exports = {
        delay: 10,
        // 1 - TorrentLeech
        // 2 - Milkie
        // 5 - upload.cx
        // 6 - Portugas (API)
        // 7 - SportsCult
        // 8 - MyAnonamouse
        // 9 - DigitalCore
        // 13 - RuTracker.org
        // 14 - CinemaZ
        // 15 - AvistaZ
        // 16 - FearNoPeer
        // 17 - seedpool (API)
        torznab: [
            "http://prowlarr:9696/1/api?apikey=74d92c7a8d424c89b470bf869c0d740f", // TorrentLeech
            "http://prowlarr:9696/2/api?apikey=74d92c7a8d424c89b470bf869c0d740f", // Milkie
            "http://prowlarr:9696/5/api?apikey=74d92c7a8d424c89b470bf869c0d740f", // upload.cx
            "http://prowlarr:9696/6/api?apikey=74d92c7a8d424c89b470bf869c0d740f", // Portugas (API)
            "http://prowlarr:9696/7/api?apikey=74d92c7a8d424c89b470bf869c0d740f", // SportsCult
            "http://prowlarr:9696/8/api?apikey=74d92c7a8d424c89b470bf869c0d740f", // MyAnonamouse
            "http://prowlarr:9696/9/api?apikey=74d92c7a8d424c89b470bf869c0d740f", // DigitalCore
            "http://prowlarr:9696/13/api?apikey=74d92c7a8d424c89b470bf869c0d740f", // RuTracker.org
            "http://prowlarr:9696/14/api?apikey=74d92c7a8d424c89b470bf869c0d740f", // CinemaZ
            "http://prowlarr:9696/15/api?apikey=74d92c7a8d424c89b470bf869c0d740f", // AvistaZ
            "http://prowlarr:9696/16/api?apikey=74d92c7a8d424c89b470bf869c0d740f", // FearNoPeer
            "http://prowlarr:9696/17/api?apikey=74d92c7a8d424c89b470bf869c0d740f", // seedpool (API)
            "http://prowlarr:9696/18/api?apikey=74d92c7a8d424c89b470bf869c0d740f", // ReelFLiX (API)
        ],
        dataDirs: undefined,
        matchMode: "safe",
        dataCategory: undefined,
        linkDir: undefined,
        linkType: "symlink",
        skipRecheck: false,
        maxDataDepth: 2,
        torrentDir: "/torrents",
        outputDir: "/cross-seeds",
        includeEpisodes: true,
        includeSingleEpisodes: true,
        includeNonVideos: true,
        fuzzySizeThreshold: 0.02,
        excludeOlder: undefined,
        excludeRecentSearch: undefined,
        action: "inject",
        rtorrentRpcUrl: undefined,
        qbittorrentUrl: "http://admin:dummy@qbittorrent:8080",
        transmissionRpcUrl: undefined,
        delugeRpcUrl: undefined,
        duplicateCategories: true,
        notificationWebhookUrl: "https://cross-seed.notify.nmoura.pt",
        port: 2468,
        host: undefined,
        apiAuth: false,
        rssCadence: "10min",
        searchCadence: "1w",
        snatchTimeout: "5min",
        searchTimeout: "1min",
        searchLimit: undefined,
    };
    //# sourceMappingURL=config.template.docker.cjs.map