apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: calibre-web
      version: 8.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: linuxserver/calibre-web
      tag: latest
      pullPolicy: IfNotPresent

    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        nameOverride: config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
      books:
        enabled: true
        mountPath: /books
        existingClaim: pvc-calibre-web-synology