apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: calibre-web
      version: 8.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: linuxserver/calibre-web # {"$imagepolicy": "flux-system:calibre-web:name"}
      tag: 0.6.24 # {"$imagepolicy": "flux-system:calibre-web:tag"}
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: calibre-web.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        secretName: nmoura-pt-tls
        hosts:
          - calibre-web.nmoura.pt
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        nameOverride: config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
      books:
        enabled: true
        mountPath: /books
        existingClaim: pvc-calibre-web-synology
