apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: firefly
type: Opaque
stringData:
    PGPASSWORD: ENC[AES256_GCM,data:TtvB9HVfbA==,iv:8hWh/ZJs1GSWf1lgUuC7BjSHkd8DYjBKJSp60CEJumE=,tag:Aw4KYTVkoC2z2yyhG3Geqw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:CzuICkedtA==,iv:MjioAfsgjHVzcmZVT254t8wu1IRKoEJ24bW6nIbj+gQ=,tag:Nnba1IntUrpjcsSlfUF9oA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK2V6b2taYVpWTThOdWNI
            RHU2cDJqUUN2WWdjenM2TXZ6Z3dsWitTZDJrCnl2aWQ4emFTdTUzQ0s2WC82a2xS
            WGFIcXNjY29jRmtwMUdzN0ozRERvL1kKLS0tIFhLTm1FUTJxallPQkg3ZGZRL0ZH
            R0tEMlI2VU82aytnMEFIcGt5Q0RlY0kKWSQdnLBzqKaCLKkrv4G/2Eq4I0P5H4rm
            k0NZjHTcAQ62NXsnYYxjtBgcEIQZHaSxpB0Rzx2hiKG+vPyaiJ5hCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T01:31:12Z"
    mac: ENC[AES256_GCM,data:keaxeCoeuwLOjY14zWskF6Txasf9k6EwU/12NKPr1sRJnLbFLVWcQcWILyUdcCaqVAcueKReV5OVZ6cZ5Zx6jnSppbeV9NJOKxAco8wM+XRbTCxS2OwQ1/GEi0sZMgWkldb3CNjCGxDwZEsRAJPgNUEWZOcZw/LD0Y0Fu4gy4Bc=,iv:Y+6RsLbTS7zajxBPD8zCmDizKOM5rlhFvm0C2c4YG8E=,tag:fw3EqE+uvAfjQJ8YiguCog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
