apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: firefly
type: Opaque
stringData:
    PGPASSWORD: ENC[AES256_GCM,data:ODmvcB3OjIk=,iv:uG+ltODMwLcRbxfn0CdNr1RqUTmteWLeI5afaB6pW8g=,tag:KQGsE5hT+KP0OxQpmWlz1w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:6+QfQtzNxLA=,iv:91rrVDvIjQ8f1iSeaA4krqPzytn1DU2kg6LzosAqVps=,tag:ep5nJDhUcvzDa4sWiJ3KlA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:pwAyog==,iv:KJLNqcYWbd5w+ymwJtjluMuuEIPK4IXjL0mo2ZPniFw=,tag:3mj7rNqhWMx6reOdyMWUrQ==,type:str]
    DBUSER: ENC[AES256_GCM,data:Shdstw==,iv:2vZehNHockh+DDSEhXuTretnT/T8js0taqPuPIy8Tjo=,tag:Ag0x2ecn2DLgWholaKb63g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MGV2RTBCd3JWa1plSCsw
            V2l5UWVWRTJSRFJMa29BQmphcHdIeXhUZEhZCmQ1aEpxTWxwTEFiLzJsWE5zODJt
            R3V0cFBXbit2eFpvQXZNYkpjampGVE0KLS0tIFVWVzJjbVRwRTlzYS9hSUYwNmlO
            YVFkaTFITWpFSFF1eUZxZHI0M0xYRmsKNFaNo1qR3GGbwfai6GyNYOBOFREiHm05
            hE7nxPx7KzBCdkYSIO+YFTBXupcQUqjcolXxO1Cg9jK/rt0RHWJglw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T11:27:23Z"
    mac: ENC[AES256_GCM,data:EXF3iOjM6QcoHN2nK3hxg3yP/a8vepydatXPgKkRiQTPaa7xAubalQERHTpIVaqtdreSkGMUGiLLgDsTUOOxH7HO57v0aDXMBE8ieyfNW7sMuM8X2LEgk22byvIToXTBYIlhkdCX7BYTrPNb9SYly7Xp6tBIsYNDRA9vaUc+Eq4=,iv:cqs+Tlp8zilbKQrf/xM9csW4kwwsmdHNa7TWzn7j858=,tag:9CJ/Bt/rWCGa61SeK07+bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
