apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: medusajs-postgres-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./kubernetes/dev/babybites-medusajs/postgres"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age