# kubernetes/repositories/helm/cloudflare.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: flux-system
spec:
  interval: 1h  # Check every 1 hour
  url: https://bjw-s.github.io/helm-charts
