apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: firefly-iii
  namespace: flux-system
spec:
  interval: 1h  # Check every 1 hour
  url: https://firefly-iii.github.io/kubernetes
