apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 1h  # Check every 1 hour
  url: https://immich-app.github.io/immich-charts
