apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: intel
  namespace: flux-system
spec:
  interval: 1h  # Check every 1 hour
  url: https://intel.github.io/helm-charts/
