apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ollama-helm
  namespace: flux-system
spec:
  interval: 1h  # Check every 1 hour
  url: https://otwld.github.io/ollama-helm/
