apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1h  # Check every 1 hour
  url: https://prometheus-community.github.io/helm-charts
