apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:pGO5lM4rbbvP/oyagwNU2CJa4EzetrAfRf4xgtxMiOE=,iv:XeSkl+V6YFDoCSPoPnXCM+MtukVTav2VjmOHEHMkung=,tag:1WpdOJjYfEGA/zkf4Um+Xw==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:Ds2OkImuU3zI7eN6quLOmqEqtIKfV7Tvvnc3sbMDPes=,iv:VtTplfMqm3SWqyV2hWmmMBESM+U2C70aDkC2Pz4Jgis=,tag:hg/ZMDUtKSwftDlr70HIbQ==,type:str]
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:VACIc7hlup8Z2akny7aNPhrgWvjrIHBDEaEjq+upnJU=,iv:TZ/Wc/yOlei46xiiRPBNjshhyMCRH7bKmuoAGU3IRv4=,tag:d7+KIw1ylvpylGXa7R06aw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:unaQtSmFBvdhWap9vJIK0cE=,iv:thG8Md3s1K1/DeF/N/qn6FwtS3eVmDe+8QYsVv2sXus=,tag:8I1Iv3fFCkSQsDGu+RHLDA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:BjWKuyPlhmZ58Kvp,iv:CyC/bnX0oh+2EJIXA+t53NH2oUj4pWgkp7z6PGs2vVs=,tag:t2CPuuPeMuMAm+4v1tHhhA==,type:str]
    OID_CLIENT_ID: ENC[AES256_GCM,data:hzFM1j/+OvLLEqrvwSKrlhtipNUnt6YKb4PzeK7VKZ6hyg2Sd3T6eOEfrelZ7BU0iW93HMbUI1qQ+/Wu7vDieA==,iv:2eh3aDbyDe7h4YukZJQaXv5vbYwecZHWmhqZC/Advrc=,tag:W+svr7ESbgB3WWgR+xNyDQ==,type:str]
    OID_CLIENT_SECRET: ENC[AES256_GCM,data:36uIPwn4R/Elv3MkL8ntMGPy6KCZ3pIRPQKvM8psoA/dTFSLRhNpiht76K2ydaCzi4QkNIwM6va4cPZThnHFCQ==,iv:euCXnH7NCjG23ADYb0+Ht/MndphxWIPIYBnm0qaQ4qI=,tag:rjq23wbh5bvG/y6nn4qRsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEblJtbXFXTzR4U3FmK1RF
            WWZINmNRZ3hmL0dKOW5LUkFlaTUxOGNWVm1ZCm5KQ3pUWGFqa0QwczAyeVhJVUE0
            Zzh1dkc1VXEzVWJnYUdYelN4b3dsTWsKLS0tIHEzWHY3cFhKeXRlN3dWRklDS1lT
            UFViSXFzM2luZmpMVlg4OHlLd2w3MFkKr8iv5alMSXHZ9NRv+9NVd2H5cGKvFUw6
            kRMsmcmDgy+xI1XzCx46HBRBaQ2yiY8kpm9YtzE3npXPimIdZ56gCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T13:12:47Z"
    mac: ENC[AES256_GCM,data:ve7btKoiTpZepHo2OVCdN+KV/6+PnKr6Fkqtfyx222Ht2WzbDM2w7+Wbf0j8jEHUhejPi8nXdFDBaPNGAHXC7jC3UXC4QSwuNTIT6sBUpYJkNwTpGdqi6hvSWI9YqKH0b9GHKsvgwlqRLjwU8ckHUSj+8vA+QX4E2/M6oIe1zj8=,iv:orEr4BELMKSMQB0QRlxB+x/iHTy5IK40U1GytGnrlY0=,tag:kIQxAbccYvjuS0v5E3xvrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
