---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orb
  namespace: tools
  labels:
    app: orb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: orb
  template:
    metadata:
      labels:
        app: orb
    spec:
      containers:
          image: orbforge/orb:latest
          name: orb
          volumeMounts:
            - mountPath: /root/.config/orb
              name: orb-config
      restartPolicy: Always
      volumes:
        - name: orb-config
          persistentVolumeClaim:
            claimName: orb-config
