---
apiVersion: v1
kind: Service
metadata:
  name: firefly-mysql
  namespace: firefly
  labels:
    app: firefly-iii-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      name: firefly-mysql
  selector:
    app: firefly-mysql

