apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-smb
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters:
  protocol: "smb" # required for smb protocol
  csi.storage.k8s.io/node-stage-secret-name: "cifs-csi-credentials"
  csi.storage.k8s.io/node-stage-secret-namespace: "synology"
  dsm: "192.168.202.1"
  location: "/volume1"
reclaimPolicy: Retain
allowVolumeExpansion: true
