apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: readarr
      version: 6.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  valuesFrom:
  - kind: Secret
    name: readarr-secrets
    valuesKey: values.yaml
  values:
    image:
      repository: ghcr.io/hotio/readarr # {"$imagepolicy": "flux-system:readarr:name"}
      tag: testing-0.4.9.2730 # {"$imagepolicy": "flux-system:readarr:tag"}
      pullPolicy: Always
    env:
      READARR__POSTGRES__HOST: "192.168.202.1"
      READARR__POSTGRES__PORT: "10008"
      READARR__AUTH__METHOD: "External"
      READARR__AUTH__REQUIRED: "DisabledForLocalAddresses"
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: books.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        secretName: nmoura-pt-tls
        hosts:
          - books.nmoura.pt
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        nameOverride: config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
      media:
        enabled: true
        mountPath: /synology
        existingClaim: pvc-readarr-synology
    probes:
      liveness:
        enabled: false
        custom: false
