apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: readarr
  namespace: flux-system
spec:
  image: ghcr.io/hotio/readarr
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: readarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: readarr
  filterTags:
    pattern: '^nightly-\d+\.\d+\.\d+\.(?P<version>\d+)$'
    extract: '$version'
  policy:
    numerical:
      order: asc
---