# kubernetes/prod/cloudflared/cloudflared/flux-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn-app
  namespace: flux-system
spec:
  interval: 1m  # Check every 1 minute
  path: "./kubernetes/prod/longhorn-system/longhorn"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      AWS_ENDPOINTS: ${AWS_ENDPOINTS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}