apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1m
  chart:
    spec:
      chart: longhorn
      version: 1.6.x
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system