# kubernetes/dev/flux-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 1h  # Check every 1 hour
  path: "./kubernetes/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
  resources:
    - cloudflared/flux-kustomization.yaml
  dependsOn:
    - name: helmrepositories
