apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:DK5H5STJrkiVgs788Tpf0oMRxIdw0FL/Lr/8H/8zhhp/Ni2AVw6PDpwRcNe4L6EB+uHAKv/Af0OwK6jj8ZlEvaNsGDRQJYIWQq4B0DEhOalnzJs8ApIY3QJ12821SRHWEcMjfWKu5kCWqzk48z6r1Xpu+98e7IH6F5j9NJd1Ls/2G6u/E4D4OCq8Jj+WYm0D6PgVg6UlmSpjZ7tmWOYdY2dagmlFWcy/RrgjaDYIX4qYGaAlqfxPvTdY4UlaDjwrFgGIBq608Hr4m4/Tl6BlbdWZys3J,iv:Z62kcj/1B354EgrW+00LTYot/5S2dq2itsuCYaC9W7o=,tag:pXCwjU65zAEVW+Fii1XLug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OSs2QS8ybWd2bmVmN2xZ
            YUFaYXBRZjBqVm0wTUYxZkxaWm1SbjZheWg4ClRIMVd6WlY5OUZJKzVINFhtM1VS
            SWp3aWU5VzFzQzZITGtxajZ6ZFhQYncKLS0tIEY4SzVvMU95R1JkNCtPODRpNmgv
            MTViMXRQMzlabWZ0dG91Y2tGcUQ5RDgKYrJnF1wdDsvTy1BRmlS1Eo3VF2pXGXHy
            NrdSbP6puriy83UNVbeAhdLtNniJtE+IohzW/gB+Cp1YIEmVstGhUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-29T08:10:39Z"
    mac: ENC[AES256_GCM,data:VNKNGtLHyP7fz1zuGU9BgeqWCdO/dqAP3yGaXIsH36fTnE/5WOxdgbWzw8rKxuszdu1JBJ+bIjec9WEs+3BpUw0v7hdtCRvR13SX/rcemAqjijukC189MgujT73zgTl3sFxvKRScvNQCukVLcrMr1r9jokcE9vsiw0RuGjxElZM=,iv:4o6PpediBbGvIZOMfRg/ZWAcbhKDAybSIlBNqLLD8cQ=,tag:EUtMINHz6+YBWxC2xz0+4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
