apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-token
    namespace: cloudflared
type: Opaque
stringData:
    tunnel_token: ENC[AES256_GCM,data:LwgznHkaB27hqUsecHWU+M72C8oIxhQfBXTOj+jSzApHzmbmMtJlkXrWJipxPaCDL0alxd5vcZ9lJ6eTbmE8wGP7DPA9SSCFY3HGEogNC7wHLxSsO004Gq7Yj03h13zrDUCc/1pLH9HQB94ceGUOrE1WVQPVTn3ZPPxmljmYHCjtuMZVVZsun8iZWzOvLlfy/XaGMUnlrvqspXjTHD0zvO/oKqOuHnICnfI3XNe5US1/YJHtHwIePg==,iv:V9C6uUWcIKa6LYvLoIsLs8GbISXdwNmBqWgaIVp5KaE=,tag:jDiFvDJFKbgl7lf1CXx/MA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS0ZNK29zbWErcW9BTTl2
            bHNFVTFrNlQ5c2s2NWNpODdoN00xaFZlRERZCnFxbkk4Wm8xaDRNVUF3d2lCWVhn
            WmZweHBSRVpNb0xXRTZiRStINkJoemsKLS0tIDVxOVc0eWtSZ1RjSnpNbUUyTGNy
            dEpIZEJVeU9RYTdwVlVuUER5V1p0UXcK+WhCDYjRHGTKVSOG/9n5KxjFaWGlM+L5
            Uj8PvuZ41co62N5eTpvYNwK0WD3AfDrz1PRmPaOZ/6sgBzMeLUpL6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-06T21:02:03Z"
    mac: ENC[AES256_GCM,data:bP5dnCHHWhy8WYKr/M4wGgjowEl7W0tBI1RIKMgs3Q1Q8wZ4KREVWs9/3KjMEcdXAXagnPJ+YAIwKoH6sLwxp7zlwT+Fpk9MDQ0ApHI4/oVjBMk+IyM73xLj0CJIll0dUXUiRlWFjd7HC8IuTtNcjZUOY79HsPQmE7UxsVOdLFc=,iv:PvFmt/VF1epd4HJZ9oIfWmOI5LJrMtxY2w2R6+QorUY=,tag:19odRhRYfC92bRxp7Ocubw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
