apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: cloudflared
type: Opaque
stringData:
    tunnelToken: ENC[AES256_GCM,data:9IMZS5BBsdwiURzYhocAk6I0KwpcMMbm3UduyDy7gWnWnEm6/Ect0PY8x14UQyZGcxEhvc63EDMo1p7J3UYW4fteTta94Wk2pk4Fkn+QjX0Tqb5xr6rZIVo37WmBYSWsjXgOGuiXGtrc7exIbFtqwrPs4zDq1rcEdOxD1T+n/hhA4TRHXlXSIGOPpLI2M+QJr6v0odYerQs+ZT4YNW5j0T5GHao7q6wxjV5/qfc/4cLDCFjdvqY7Sg==,iv:CGLgtHIZ/Z2RN7GZWTwXXgr7IzmD3UXHiVZjSSFJoRk=,tag:yC4K2+j/uJoAcz9bEHtokw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSlJvWStFRDBOa052dXpq
            bkFrSzJPMG1GUElGZFIzV08wUDkwemdWaHpZCkw4OW1aa25BL1Y3NTloejdsR1Vw
            b211VU1pWm4xaHFOelJLcmNUUGF1Nk0KLS0tIE9aWjhlU0dNbnZkNk0vQ1NpYzN3
            OHFTcFRDWGNtTVVrT3hMd0lPMTBkMmsKE8vnP0ZeHeBPT4D0N6Qv/IoSu+xXbZ4W
            8gPcJ9dFuNAxLnNA4SC5ZmX+NuC50vzaxNNgg7Ur4AaOyHwpjn1X7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-06T22:18:41Z"
    mac: ENC[AES256_GCM,data:b8d+suzUxwLn77z88ENRtCzyD44T+9CLtfupOXKdJU+HA8Z+2APmAepwb4pqcGBV0wQ3V80UEX59k1Hsnir79PTlA2uc+9R5G3tSk529TfH8fP36Zfv2ZG4wMVG3ohTe7CTViwPUkdeScFZqN2vmc/8IFVyGXMAe+Dq2C+GhiYU=,iv:rqCHl1MvqEe/4nKu5q/FR/a2LPBuq3OeRayUoC/WObQ=,tag:byLnTBSSpbLW4OmgHZuABw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
