apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:cceNBuiAjESmokX8RI5Epa7EqVPYXSkHfvKi3C+2ZXwJvUZP2YVQO70NZ0NlXEPtk5Stc8fx6WRY6jw40DvcbY6ohKtOEBrFdteY0CUQA4xIk0N0cNApg5lTWp+kx6Xb0wFrqpCSCF6YZfA8b0gpo08SkxP0JH7j+eA1hhe7ikRN+Kjb0rpGR3U68SiCttPWt0jc+7QZLcj9QGtOz3IO/139wgGgzl8bQWbWevsG8ep2AFO1sNUsACNb7zNyMUJ/j+NWVq9VO/PEWQuth4qyeokozaE=,iv:IuZqfuY0KrVlju5FGz4SDL58sn/dgn8MWQ24oR3ZKmc=,tag:li+dIIVzZrSPRZDPBzpbWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SjUzRzRHTURiOW1GY3lM
            WGtLeVdmWEVUSUM1VmorSkFqRGw3eWIrcmtrCnd5WE9Uc2F3N2NpbzEvTCtsdFhP
            SmNGYitJU1kycmI5ZW5MNUY5dkNBZHMKLS0tIEhtMjNpeFlqb2tldzhUZHJjYWs4
            U0R6VmljamlpS0F4OFU1aXdaaGFIQlEKdcgjgDtAGzZvKTgdR+QvxPNN7eYC1Vxk
            nYmNJ7w8ZCLh0M9jNO5Qe52W71b9ASiyLjf7qXcF8qLyPxGZc1BaUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-06T22:40:51Z"
    mac: ENC[AES256_GCM,data:ccSIZrJXzi8AH2OXM8aDwh2XNS+eetHdYszN4+xTd38UleyWFHdiIaw+Yo8bocHHI94jCAIcFF0CGqyms8C3L9ZxKdo0nHdVHtniCtErwR3BlzgR3Y5uXQcvnR1UVnU8jMJ/+vICps7tQDs+J72J1OKTWMVn1NGtl3ceSMZRMU4=,iv:I8nBssfYgwL1XOgQVMh7NxeYdqGZ5ZMpqqDw7yc5FiY=,tag:lBAMpxbhg4iNaMMICetxGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
