apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: cloudflared
type: Opaque
stringData:
    tunnelToken: ENC[AES256_GCM,data:Bxvwd8XQ3KAAynxhM7Eg6hKYTIqZcUb6yjYOZNxx9BqLjHaBfhEgBx4bgjusdywbq4Jq0gEqvjomhnTFZPIxJ07ecdOdF9pBjRVpdAv28YbaCVKl8eKS0mNZhdB4/TA6Bo0vETYY6cscVr4rxXZ1mjAWhSiGJC6bDLVLgqx2X4asd59QvQlrwcudOVGCsLueaNWTVQELqyUETs/vEAHnithtv8AZZ+tlWbqyqmlchU2hOcmwGYzRVQ==,iv:AxTHUfu7mP73GHOaSAAlN+aUfRLzeJMvxi/u5TiU7sw=,tag:kVkWbjIreSWBhbiMnoDYgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQ2dIS1I2ZXVEbjlmeVpD
            RE5ITFV0SW1lQ2cwYXVvVGZKMHErUVJTWVVJClVSZ2I2TmJBcFZvZi9nSTFraGtL
            L2NzUk12R0w4UUNDblV5QWpjbGorOWMKLS0tIGswZlppN05PcTJyYU9lVnN2aHAw
            dHFpMG1CTFhER1FyMHR3Y0FJLzVWN1kKXdGUeut/ur8Fo2C6K7rVOzF+uMmoB41p
            IV6E7EyghV8TajYDgyHvWget7VehJsrS1MzdCmFwQtW8juZjdLfqpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-06T21:24:03Z"
    mac: ENC[AES256_GCM,data:nlc/4QDwXmZg3wKnpX3BtD6kFXYMg1ttEwCs0dOYy5x7zcEQ+UIHIT+BMSI+kIRFUYF941Ns3ljHbZy3hX3w9IVNi62zC1WD8deybQzDAs4hphrk0SafdrCQq9dCZ3eQDqCYoZx+8mpV9tvriNgJVxzODa9ZffqxI2uIYR71xxw=,iv:ueyBbox0bXjFS9Ra6gQRCSNz6mW1skqPimEk7pJysDQ=,tag:2qUp91J3XxnjsdnyxKy11w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
