apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:vqZKdm+8aCwH5Wzy+0Ucs8fDgkn8aRBmwQtrw3M3BDr8WaVR2SOJuzF8rY93xifmK01kOFEeJ8JqVrWoSFrE03EJVtkrAoQs1KNA+p9FqTXV3NVTEq51GvuB1U9RIuHkWXLdSM3CGCAnxrruHiga72O8NhIfokClJ5kkW/dt1spGftnGbQ2EVkdJmzhLFupwXq1op3HxguAjNt7nCB6FTszl4TLMUVetB8th//UOAYjZLJOjS8JIYDT7Ttk+nhZrKvJ0WpIDv5cMNwfo3S5VxCQlRs8=,iv:pgaFwvWNksaeG9+al4WmMImwnb3GhRBGwtxoPV56iQQ=,tag:EZWQcnJg1p6jIbhpvLqmuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUG9yL2dwdzlFeTE5TWtX
            blBydTlsQlRlV0FHck4wbTZjVWxyUTQ3Q1JjCjNST2FRSFUwektmelFJMzczMFJR
            OHVHMm5sUWlUU2NxOERlMEkwQklHQk0KLS0tIFNUemRnY1pUczNBdVc5Zkxyem1u
            cDNjVnI5WkNMbkJUV29VNnYxNnBrRkkKyJ60kBYJ3hd4wzQhn19SqG7tZgO9g6Cy
            EK1/dHzjAYrjyM5dVrs+6/hJSJregSMKgMyRUZej/5flZnFFR5zKQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-29T09:27:47Z"
    mac: ENC[AES256_GCM,data:pbdRgfUpUsnOT70P0nK0Pgh7kbzVRhGHlNbzxFGRJ97iuy9QcYhMMmHESQqp59EkXxStdo6hv4Vubv4sdak5EmcoL8/NnIQdqvFC7DJ/+wd3ezT+6kYw9287eTHXG6s9MjnocAHexlGM975ePk1T0JFbinvbXu8mDDmhv6UrIN0=,iv:uPpRPy7oJpFvEIn8lgS+bx9ZUKgO3qwPrAJoXpvKQAg=,tag:+oDSkVVahDiJVFu9ccoZ6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
