apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:UNNk6dkIf9nz1kGAuMVv4Z1C2SRWO0FDqEqqkNfVL3RXKep45ZsQKCCi+qfw/v3SIh69mtbCHdlFMzZr4lzqBqA0hXh6WgcoK99TQ98HcJMtUYdLHAZjEaRgZF3RowvH84Xfj6a76Lmb+ERWrWeDzUCGMkJqRBEZOgJiU8GLSmVjDyMUrVQPzfWqreOWcTJLaPiKpoQXCeqVLJAmsJJn0VWMh+ZVj7dzY2ad6fzaun4s411PBzS2Fx237K29cgVRDJNy5Qk5zKo9l6fK5FzlBwjlJGNI,iv:HjY6xesjbn82owwQQiYmCYABR+ly3/MMA3ThafD6Sws=,tag:lmooob9C/kjfF0mqZbXH4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSEhKRkJqalEvMkp1amlO
            ajdSNDJxd0krbzVTWUNINEkzLzN1OENJaUJ3CkwzbHlJS25mOXE0VFlZSnNoT0J2
            cGpCTmxBR3FoeVdOK1ZpclBtVGNobmsKLS0tIHo3TG0rdHRMc2MySmNsVEx5Rzlm
            VVpwUlVjVzZrV2xmajJTTm5tK2I4NFEK9kuVV6KLaivSkKUQBwwR7zbHeuk2bwTt
            TBuJ/O/H5gchtC/XQTC8oIVhlD/oB9Y64mb9xPFyQG+rzgdLalKZ6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-29T09:02:56Z"
    mac: ENC[AES256_GCM,data:EL30RIi6JAjOzMVzKkBVPVJwkhZytRkGQtszQ+Q45K/aMCTii/O9kqOqe0Zp4wzXhWs66YqKTtvkBkIVlqfhVFHHD9ud/XgeJ6ZpJzfwr6QQV0kKGnx8Z4HfhnxhSKJdUKY2EMNiYorWSsnrdR92+hW+zdax/Hyl/03+87moLsQ=,iv:Zuq6+TqxcPjSerVlnKdlSZ96kvmpQDCFx4L36cMQqkQ=,tag:ZJZGW3IOA8P0UBUD1mqvyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
