apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:LlU7GCNoMw+HtBnfbrUmrj/EHCCc0XnZh7OYq2iZBP554Scy/XMSho/GwVltt6Vnnxson1GpYYaEKY2A00NVIZ5LYTCFsLgXr2l52/dWfbnF2Ubx3X31fBVUkPT91TDXRkqsCkos8/di19EH+F2FvCyeogiwU42XKGv33ugkkZOOsIpe/X6ri05EvospSDzZ3LOMXL75k+UP6JeS6STEryE5BIArwPG1GY0GuyrA64pLboswCivWERIsWjAW9pv+zhHScIJ3bVrbiIIkNmq5LnGctLQ=,iv:VKOf69N2nA2PVd+w+tTAA3PWdYfcWB5RhGQ6ZsFAyHU=,tag:Tml4cRBVzRcTU5CYiVUYDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcVUwdGJnM0JNcSt5QldU
            UEczbDhzRklwVW5UN0p6eWlVamx2c3gwL0RVCkxUT0o1RVZDQmJXWU1sTk1oeEVM
            RlN0N3BEV3lqcU9saTJrOTEwVG5ybGsKLS0tIDJRenBYQ0hJKzV3cTJINE8wRkZH
            Z2JMek9mamtWMlFKSnVtbjNRYnBkYkkKyGPEDcZ09609GMLX2SOwUX2I9NF4Ums1
            24oSR9zxDcOzUNbifXrqWS1Qiz5rBMahBIsSfX/h0rrLUFErRdUACQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-29T07:36:01Z"
    mac: ENC[AES256_GCM,data:TSh63P2KC7Z/eZA1qChF6Lp1tPCjoFMQjraaySVLoGmBtIG4CLjLAv/oVPCbsMJjByM79vpS2XIDUti4YfelTwc5Ip+7Tt2yZqWsh1h2trK4VftoD2EocBpEM9ATc5ymNoWr92892SMdEsmUDWl0UwHLKLqBukZUryJ2et+H0wk=,iv:T7tXueqTX9E1wDKyi6KTVuRqyFfpnHPTz9kBt//qDkY=,tag:l6T5FEmrRNWva2xLIljLzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
