apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:zFsoSY1n3QS/08eIXCs+QhYbYLsY4brNc7UaXIHcUwkRExtyicUbHZVDZDQUS7wVq6o9WZYU5HwCJMdRshwvnTmjb48qG2VQo9rNbE1MwagoiEGGUxfF5b6K5Rg9Yl7dx2newAF+X4iVy5HJJI9svxUj+Cwl/g9d95qBEGPJWb2hvTaE9xx6NW6sOcCn8Wiq5fwvExuw4UJ2xWVLfuZrrCcM2+nRwaY9d+ZC3A5bRV7/0/1KOKkYbw8BkEZVkMm+E1wXK78MlUY3PVIsirBPtNXbxA==,iv:4IQBwRLddqVj95kgZE0nvTztzacYigrYgVZb968joKs=,tag:8vKO3/weOSd8sLPzvzUbrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBta2dQeEtjSkpGMFYvQUg2
            OG9sT1h1QWxua0lSVkY2WTJnY3NmcUZVVmlVCnpMTEM4cTJtT1NRdFIwelRNdnRQ
            QU1hZGF3QjNyNU53R2FwRllIZHVOUUUKLS0tIDlQTmhzZFF1K3E5YjVUWDc4ZVAv
            UlZKdWVkR1hHVk9yRk4rQ0xpR0E2SGMKBiHiHoEI1DoJoBSn6D+7CVPtD0zjdDtf
            coF+VB+q1S9nmm+b1TF3TgJX0sM+8zGmbqnZCvZTed16RksbHT4x9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-29T08:07:19Z"
    mac: ENC[AES256_GCM,data:LDfvMeJOBNvGylNgRxihQI6pc7hZfY7RzEy4odoaJwpOR5+2abny9mz+vCpIjH8wDB2V0jNacBgH2kGfpIqaomP1klrEwEKLh4v2UUaNJY3bTw89TYHhGOGv00TXMTwsLCKJghR2c9mW9F7tYrSvlMje0PJu/6Whip4+ERSzxiI=,iv:RfIyIa2u8GUPKjAIvDGJwfbBe7Miqx/Yf6NI4K8kGoQ=,tag:InEbAcsGui3WbbWX13nKdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
