apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:ctjHAulFMlSv7jARbcIBJaVfL1ako/Oqr5m/nKvn5Cd3+SanXUqmx0Rm2NymFZMzD8XgP5Im/h80mG9v0t32QY+o9YSL2XLnXncBrqY12cjVpTaPlqESv3MAaOdpuqXJzsRHZFsvgGqD4jexBAu1LPN5K9Ulw9Q9RdDlXRlJpHm2VrOgwCf0CkRy8wzihQqnDf6M6BC9C6KunCUwaGD0ayX2974gJL5oMaEqDGhalfh9XYQlULqzeiQT+FB+mTJh/pcakuUdoZO3Q1AeNz2tzSSiBQ==,iv:YK5gIXN6OkAimt7uogKxur4cwoW7gkZmnmNkClIEGNs=,tag:cn0b8Ivp3Kv2IVHa4pUcmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOWV6TWxRTGlsajNBdlMw
            d3ZKRW96WC9Melc3dkJ1bDB0TStKZ0ZZUjJBCm5kMlZoQnMvOUVMV0w1ZEFBa0Fj
            V1ZIWG1OdWJkbk9iVk5tRFhMNkJTblUKLS0tIERHZ014NnJ1aFYyOEVXQW5nbnRB
            QTVQV3pycnhYdHlwcHNzUElBSm1LUzgK6MSKKl/LQk39S5du4fVwou/RzzCl8etT
            iNPHo8NbDo3u/ZTZORCAMn7W7Dl63sU1j3J4WG0Oen2sSCeu8uf0+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-29T08:26:03Z"
    mac: ENC[AES256_GCM,data:NohymREc6pQ/Ehjf4iN32OOzIN8wEHyea6aonl6p7K/maTMYgDjty/rQshWZfs3Bn/EjOKJUMVQyYtgupYWLvNfXUuCoIiZQWHaLFh+GdYUXYBJeTdfG9dg+Y9ak1G1vxHGtStVQaFP5zMG9pMXvOFMIGP2MCbdBGHmQBCA7vvI=,iv:OiZ1Bw6THsu/MTYCg2cFEf4qeIudmyqMnpKZHpIh7AA=,tag:xvCiNO3t3sUa36XDjM047Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
