apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:1yRPxIRk78Eda4/vFUthLtsOZQWYIUY+p5aObJ0rbKb9oAm/eHm1R6cft0G990CHc7i5Z3MtYiTYUK3BGfIA5HWqoAeHH06jlp26sra06kZwD4CiuYvGAx+9wyp+r130U2TTA3Q3YBxCEO5RdCf6HtL6teQprd6TQug2LlkXj05O1sFScegndkYhSQNcLpaRaZTPgI+FGhiwqhpiDh5Kp3K646svRgdfvvZXNIJzKtXUJ/oMigaCbMR8cV8bcqleay1UI9Jli4VTaa5L,iv:dUgmXCXQb0Q6qCbuWPpKM+K5I3cgMPmc+LPpwnJDWzs=,tag:EhNsCKMbFRGIU8RX2T8A3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4anBhSUtYMFVOWmNJK21E
            MjNqTE45c0FUNDJvS2dkbkx1TlNQTkR1ODEwClFnOHVrWVY1eTF3YXZQMDc0dndz
            bVEyb0tEUXRmQWdRR09pMGNIRXF5dGMKLS0tIGgzZ3JqL2NPV21RYXFvQUU4cHVT
            b2tqcUNVWFFzcUROcUJpSlRrMWloa3MKT7lZtyibrDG0uVxEgw5vDzGMivsZN18N
            O7nrGH8QNY/mVzXbPF+pBSpS4PJx5aMLdn30U3VpcwJbrPEJvmwwhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-29T09:21:46Z"
    mac: ENC[AES256_GCM,data:/icHig1edg47aRTk2YHe052P5JUgVTkMIEA5tZfmIHgXP0mYhgaXCBeCXUtH4YubFd0w2wiW00jpO7rLKx2li7ItofXP+D/9kHtSS0Txsrtf3VUrikiyVC2HkO486np5siLgfeJS6b5m8uzZNMLhT5mXA0SQ4OEB4UBvtvsptUM=,iv:U4f7S8my5BoGLUJ11qEWOePVOuIUcPUtBrodRW9N238=,tag:DKFfwFzeqq9q6dYtZ2kvCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
