apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: cloudflared
type: Opaque
stringData:
    tunnelToken: ENC[AES256_GCM,data:zhGbGuhMLWFgPxql3dlJz6Zx3PJRmFzJ9F3owimXsCAs7nhoDp4JPaQE+pKKqJIXJAnP0TH1HdITker/7um2avO+A2kTrpjP0dDVDU3U5+2itEyGesi429NbLiEajW6S3lG32y7TZpKDemPd95gllOh/dJxXAtlbn4o/mH6EvYuFZce1WiHEjJIXYyKG0Z4jJzgfp+RyUPyuhMFbvgoiySKj6XK7Q/sZ/fqi6Rf5CPF8tgt2Pzz0gQ==,iv:/HEO9TdKSL6E8wnLs/1P8+j5RoV4dHTSDHak9qWdjYk=,tag:YuemTDic3MRoCsmcBMf+Fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeXZCaDNONkwzdEFxNVlz
            Qy9QaTQrQ1pVZnlxY3I0Rm8vRGN2YkxNVVdRClRzZUQ0YUU3Q0dENkEzbVFPNjA4
            TWRuTWVKaExiTjZhM3pzVHNmQkZPUTQKLS0tIGxBMFFvSUp6a05tNDZZTjc3VTVO
            YjA4UGo5UVRrbHVBclJnNWllNmlIYkEKjEZIkoUOcBlnAvJfvpkFh6FmvvUwyUKW
            +Qx+zWk4I3qgFS9snw6hl2Cb4sbcCsEr0+ZPpxyX7YZgJR6NXUj4QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-06T21:20:19Z"
    mac: ENC[AES256_GCM,data:PFc8nlSHQzY3Ld1N7YOm967LPjx+QF8GmkpOQBX1mV7T8UytCcGqU0UfC2fjSn0Qd7J5pN7X7yPgObigQuwv+On6cVtsBKDE0ftBPebfCn6KylSU3igm2AkepgV8VS2SMXBh260Tu8vRwij/UWbbAmybEVpXGc7zlPWJT8zmLCI=,iv:IbSYddF6qwGnhqZaPoaWy9ffkCWIoDMQFc7nyoenNNs=,tag:BI9Ay2PztsBf8nCGczPuGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
