apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:2YHOnwpKAg5jjzINki3LjQZGmhlmtM8/HMnKr8uCI88CTGMafFypkw==,iv:X7lG5YbyUZxooiL7vJHSt/Rx/cawjMljCKFuVlG2/fI=,tag:Bqoi7JB7Krr8VmH/rs3SIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K3JGcUcxY05JQmlxZTNi
            N2VPcmNzcG04Sy9wdURSbmxzeFNUdUNVSkZRCnhBNDV4TkViOFgyRFI0WU1jbHR0
            S25yRk5aQkhQMGh3ZDYvZlE0TWk5bm8KLS0tIC9uTzhqOXN6TktLZzV6V3pwYk0y
            dU5SSkZEZ1ZDeXVTTjVxSHlQRGNsTGsKOJQ162haX1arT3Jv4gcEZN1RAm5oyKkf
            zgId6SVn/kgu2/F9HasM6bnohmVDzNs7xpd9axOIgtstUUeGrUXHZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-30T13:52:16Z"
    mac: ENC[AES256_GCM,data:wDBc9YvQGFnxCM83H9bxYeuzfdaT8kVwgRcBfMq6MqLxJ5b2nDwKS/QmZK2G9/ErbY/wzO/LoUAvcqZWJTcfJ4ke+dGtrCH6zRwtc4joi7Bmz4UZr+7j76Q4gG8i4GCn109CUYCOJayMyJ3Qra5WlA3Gk86iVJxZB1E0IkAYIRk=,iv:BlyH3VJ9VXkGKSLtNnm1m3zhNY6HM074vPAm8KC5/lM=,tag:2LgpXmo3jbdsA3w61Ad+Pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
