# kubernetes/prod/cloudflared/cloudflared/flux-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: repositories
  namespace: flux-system
spec:
  interval: 1h  # Check every 1 hour
  path: "./kubernetes/prod/cloudflared/cloudflared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
