# kubernetes/prod/cloudflared/cloudflared/flux-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cloudflared-app
  namespace: flux-system
spec:
  interval: 1m  # Check every 1 minute
  path: "./kubernetes/prod/cloudflared/cloudflared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: cloudflared-secret
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared-secret
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./kubernetes/prod/cloudflared/cloudflared/values/"
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age