apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./kubernetes/prod/cloudflared/cloudflared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age