# kubernetes/prod/cloudflared/cloudflared/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 1m
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      #version: "0.6.2"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  values:
    replicaCount: 2
  valuesFrom:
  - kind: Secret
    name: cloudflared-secrets
    valuesKey: values.yaml
