# kubernetes/prod/cloudflared/cloudflared/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 1m
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: 0.1.x
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  valuesFrom:
  - kind: Secret
    name: cloudflared-secrets
    valuesKey: values.yaml
  values:
    image:
      repository: cloudflare/cloudflared # {"$imagepolicy": "flux-system:cloudflared:name"}
      tag: 2025.7.0 # {"$imagepolicy": "flux-system:cloudflared:tag"}
    replicaCount: 2
