# kubernetes/prod/cloudflared/cloudflared/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 1m
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: 0.1.x
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  values:
    replicaCount: 2
    cloudflare:
      tunnel_token: 
        $secretValue: cloudflared-tunnel-token/tunnel_token
