# kubernetes/prod/cloudflared/cloudflared/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 1m
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: 0.1.x
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  values:
    replicaCount: 2
    cloudflare:
      # This ensures that Helm pulls the tunnelToken from the secret directly
      tunnel_token: {{ .Values.tunnelToken }}
  valuesFrom:
  - kind: Secret
    name: cloudflared-secret
    valuesKey: tunnelToken