apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thelounge
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: thelounge
      version: 3.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/thelounge/thelounge
      tag: latest
      pullPolicy: Always

    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /var/opt/thelounge
        readOnly: false
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: irc.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: 
        secretName: nmoura-pt-tls
        hosts:
          - irc.nmoura.pt