apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: flaresolverr
      version: 5.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: alexfozor/flaresolverr
      pullPolicy: IfNotPresent
      tag: pr-1300-experimental
    
    env:
      TZ: Europe/Lisbon
    
    service:
      main:
        ports:
          http:
            port: 8191
    
    ingress:
      main:
        enabled: false
    