apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: flaresolverr
      version: 5.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/flaresolverr/flaresolverr
      pullPolicy: IfNotPresent
      tag: latest
    
    env:
      TZ: Europe/Lisbon
    
    service:
      main:
        ports:
          http:
            port: 8191
    
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: solverr.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: 
        secretName: nmoura-pt-tls
        hosts:
          - solverr.nmoura.pt
    