apiVersion: v1
data:
    client-info.yml: ENC[AES256_GCM,data:bVwI14m1QE1WXBXBGqg2I9Y43T60McphvtOiWrn160exRT8QS4+6syGAWQAre/pJBH+qyJ9F5MZTuP+2V7D0gvbNBY5bblaJsrCyE6VvrcsxWmAdfGx1Y89qLq5+7hG+M4OSRl0X+cFa+FJPUD/5CjbXdI4JnYRk7SROVYMtqDJnpyg9iS9zf1WSEgQFY6nEhQAbjJ8HIyWR2ybIvNamKtiRhIp3tUqwUpVLOhLGwNLRTVj4Qfo4dSTmOUZEiFlAb+jo6HCBPs8wLqdDbv+4W21+pybxk3vXlC1cNmU7Uyszarkku4x5AddV0W1XkHvAyA+8x7yjJR/NgboWQJcDYAbuzx0Zj5SjwjV8Wb99lr/ytH26J2HmIxq86y5oQ+azChDTJinovbSH/7MZ2jH4syaNSkFclv6kXwBqg+pv9RaeWOA5oSAQyVKHS6qF56zE8SVfxnX05KLaCXuWNhNcry94aUEe2EwumbML9TrYLSuOBmKMdZAbY7uKeeHY8biU8etDqYbKNXhrdlzsXne2bDKoHbKiSUrH/XSH6VxNZdx9co22XjJabtexsAcu4kK/,iv:WKuZ+x2N/kQ7++pWdhhdSjn2fitSw0B2xa3ehOZu6p4=,tag:in7hmNAUXQglvjXp2uaJCA==,type:str]
kind: Secret
metadata:
    name: client-info-secret
    namespace: synology-csi
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQUJBenRiSW16c3lhSHRI
            RVVyYmhoTUhiNFRMTS9RcHRhMmlrSE9tNVM4CmViSUF0MEsySTYwaWhkVWtsUHov
            M3JIQnExT3E5ZXViYzM4RTZQazVRS3cKLS0tIFZoM096c01QcVVJL09lYkF0NEpI
            aTlyb3AzSEZCME1wdWJwcC9vcDJMYUkKwX8CuP9gP61ukv0aRLDKZaxoRnSsw52s
            ZwTeP5CBx7dmIn49D8OMLK6zqu8npQ6HbP9vyCkCKh+wFKx8xrah/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-05T22:30:50Z"
    mac: ENC[AES256_GCM,data:2rwCAGxu054d4WobcoFLpvIaBBMdKkD97w5tNxtQ+zE5JwoIClYTepK6bnlRMAFjwcdGkyoJVZU2TsM0VMnKTwMbt6pB1z+sLVefRtArvWzuO6ejm4tOwErD56BdJprijNYAiAxo0l58YJQl2FnmfDjJ21NWpoI4J4uxsmG7vn8=,iv:lgaIdTcOeRhTvj0yHKiME6UZQJ4HslungHkVHzHhoa4=,tag:NDX52iTfasdVeiP1q/1YXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
