apiVersion: v1
data:
    client-info-clearsecret.yaml: ENC[AES256_GCM,data:1ApNk6jwVZ/kLzpus7fGoB3v8EJiXf4IffzhWlw/rQKevyCNkCI/dUWsOpu4CVLQjnL00rquhkvX3EZaiQRjQm8SxwVBIZ3PwIfGQnKn2m2lP2247bqmbQuLo30a1CcRck9ShpBMw8GCjFg84RTXkxII22oy6StlzQBVoPzHsuaLH7L4UFSwhqr4CaewySsiP97ULKRiyn5NEkYjqTQPX3di1SQ2iYD8lrjRsGAFNdGdY8ca8yEY7pxfP21kHRuMsz3bqD6Mg0KR/0T62P4Tn3ZQmi0ekNo59PQSj7Uwy8Jmpv7x8acwsykfnycubDagQhcOdg5yijNu6vpCmpW1WqqCAWAq+g85VeNmiulg4h9gTRPUM4y2Enecl5xABHKnQr3Caf5Cxaii9a+ISI1zgUZSvuQV2dpcwRJBo05auVD9MtBXYU4N9TDcUDbnCUR9RHcyhAxCkGDumzIoPpWeqTBF3UNN1sX8QxATPM4tMk8N7bfK2pP4HCgnpucABfcWcKMKAwucV/GdNeL+2UuZEh0CgzZlzb6A/Efi/THxsjnKxzPDLj9nyFMSk4fkL0cnETv4uif0so3tNmhYaGsT5hqXZq+uHPm1sSYHzSs2/wI1oEXRo6DmmJDKU6iBNu428mRdOTI4XLsC524GbI97laJEybTAO3bmLe2cqFZEDSCG60pZFdYWm3y4OjiERAlI2IBoq5/BXw2stGZ3d2hnkDYJ7yTTO37n3FxFSaFWfNdKz32pk6VQ0N9peIFmfEck3Nhb9neSYXKdZpCcbaCtC7uoOlmhdf+BLv3yPrUgZFj87FPPeYc2GHShQzo8DN4T6pjcs7/ej2uoqF1BxxdiP0S3S5+RGP2CVQ9RYpmArNwVNQRtdBCzz8seTCd7O0TFBPM1qO1Fs7c0a1llaYxk0roQ08VA62LS9R6FZuhu/ip8+/oR6H52FBNnt7rXnGWOh448OxmIi1gRh/rb8euY8k2rylorKe91uPqEChZ+DvXaym/c0nOm+KOV7UPQbAV3sHDDQcmaKbAZ410IhfyrgHn3nfkx58qlVAAyVzihOc8ZIhI3hU6zn2uG5os0WtJZ4vXTq4CB57We3HPmj/fAdSS+DzHgKqR9xyL9y2ciCzl2X/mXnOOVXBvcJ31PZjLweWoMsNNPwtJnLarLfiGfwYWrr8yHlUIO+oZ/UyzBNDssIilBwrbkuwCH/je42JMTL37knZTWTKY/0cFZob7xbodaj+NuBZ1yWbbpwQCdd5ZHnhb+Bv3fW/Jauo5ayY+Wvau68ajFshLzsA+Bl3aUbnkuvcCvU2Fto9w5W+XlguAdg3dIG+jF+Z8816YgBBcF+SuPSPpNWP/oj5NIRjGvqYOiUeRAgiftd2m6/xFNy6PCfxsUCjHbKtdtv8UgX/qHK/kzolL2EOND5F+UfTGdZU/gHA18N7x+wCrvatKlOFZZS75b1Lkt5BmXfs0/2VnOvNIEiwI+JaFPcieUE075YRqKgrv0NTitPSAb5vmCSbcJJLyt,iv:awzkuVSLTSQTkxNTEDREUczt0gLEvddLZA+Q6YEzsdk=,tag:dVSe8pl9OmoECzN2VdraqQ==,type:str]
kind: Secret
metadata:
    name: client-info-secret
    namespace: synology-csi
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPN3VYYmtpczVaOGhEMFlV
            bXJ5RDRlanE0b28zMERRK3JTdFplcGlpY0hjCk9PTlp5T2JtUmQzamVrMnNpaHBQ
            L3YwOUJIbmVPcEd5ditIeC9WQ0U0bHMKLS0tIDRGNkRRSTZxWXB4L1ZGL1VpTHV0
            UVE2SXVsbUQvS25KYUdzclZQcnpnRTQKlznJybRwDeVZYmz6shF8NzJTWuzlTryb
            a/xBGlporfbkJe862mr3svZRm80ySWmxdNqr9U4dUPc+tpCE9rm9Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-05T21:19:37Z"
    mac: ENC[AES256_GCM,data:uBUGJXxLuxtVaQOvqLAztywDwCxQUXJbwSTRFyYdU10MHXWjWny6cgzIwMvla8cvDJJINvLj+/4gyj01FjNf0L7g9iDjEQuImP6Y9W9l9kOhV0H3HXiP+j45EzZ3Z3uk5p0lt3tRoCkzEPCcEilqKeUc3XF6KFyxCdDsbgCSyvc=,iv:vOmthejypOO3WfX+zoeyJDA1YrmJuZIFjCPcAbUbtkk=,tag:EWxvPBoN4BP2EpPOtQlspQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
