apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-backend
  namespace: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medusa-backend
  template:
    metadata:
      labels:
        app: medusa-backend
    spec:
      containers:
      - name: medusa
        image: ghcr.io/babybites/medusa-docker:8c89b8d9ef55cadb23a6541319fa29180e264ed0-arm64
        env:
        - name: DATABASE_TYPE
          value: "postgres"
        - name: REDIS_URL
          value: "redis://medusa-redis:6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: medusa-secrets
              key: jwt-secret
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: medusa-secrets
              key: cookie-secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: medusa-secrets
              key: database-url-secret
        ports:
        - containerPort: 9000
