apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-backend
  namespace: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medusa-backend
  template:
    metadata:
      labels:
        app: medusa-backend
    spec:
      containers:
      - name: medusa
        image: ghcr.io/babybites/medusa-docker:1ce3a581f87bb3a4a9243be6253961c94c8ecfa8
        env:
        - name: DATABASE_TYPE
          value: "postgres"
        - name: DATABASE_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@medusa-postgres:5432/medusa-db"
        - name: REDIS_URL
          value: "redis://medusa-redis:6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: medusa-secrets
              key: jwt-secret
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: medusa-secrets
              key: cookie-secret
        ports:
        - containerPort: 9000
