# kubernetes/prod/cloudflared/cloudflared/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-stack
  namespace: elastic-stack
spec:
  interval: 1m
  chart:
    spec:
      chart: eck-stack
      version: 0.12.x
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
  
    eck-elasticsearch:
      enabled: true
      fullnameOverride: elasticsearch
      
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        pathType: Prefix
        hosts:
        - host: "elastic.dev.nmoura.pt"
          path: "/"
        tls: true
          secretName: nmoura-pt-tls
    
    eck-kibana:
      enabled: true
      spec:
        elasticsearchRef:
          name: elasticsearch
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        pathType: Prefix
        hosts:
        - host: "kibana.dev.nmoura.pt"
          path: "/"
        tls: true
          secretName: nmoura-pt-tls
    
    eck-agent:
      enabled: false
    eck-fleet-server:
      enabled: false
    eck-beats:
      enabled: false
    eck-logstash:
      enabled: false
    eck-apm-server:
      enabled: false
    eck-enterprise-search:
      enabled: false