apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: certmanager
  namespace: flux-system
spec:
  image: quay.io/jetstack/cert-manager-controller
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: certmanager
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: certmanager
  filterTags:
    pattern: '^v-(?P<semver>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$semver'
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
---