apiVersion: ENC[AES256_GCM,data:kOw=,iv:/bUx3vSZPCaphgHDjd1wX4/JX8vGFLZ4fNnTzqUJXEU=,tag:/BO3PJnPOsJJIhY4MyoaKA==,type:str]
kind: ENC[AES256_GCM,data:cFItYyD5,iv:ih8zRrNAv1a25FfYgu0rbZMIa0v7FZVIc9bo1HE/c8Y=,tag:3AopiKO4n6Vx3cFNaOcBsQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:p6FULggLKNztSeMh6SI=,iv:UeQKf/f3bKy1hN5NlzHuqC/a3O7ymJRjIRdQx6P+5yE=,tag:8iSfYS0rlEIxzApW0hkG2Q==,type:str]
    namespace: ENC[AES256_GCM,data:ShF7NNY=,iv:OxHgaIiU7iYnYyLrWGGUXZ7JR/MBTNweCZCctXbVK7s=,tag:UAI1djg0LbFMzyHxIjH7pw==,type:str]
type: ENC[AES256_GCM,data:p00RZB2P,iv:YXjzmFS0TNV2V9DwvIOMzFWexHDPYo5vxgkuDabC2w0=,tag:41DLsD9kQD+xYioc7O9P1A==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:kSrstzKAGBQuCDB9mxCsuGxO00qZPXR28ye7M8IWVEUS7+IcsdOxYcnElLf2rOgkDz+aIUZ8/uvFdJmpF2lmOommSE/A2b0rJqOZiNGJXuTdKWt5bBrdxmlivUgle/zb5vFvIsCC7kVCYdfq1w6sg0MS3Sj6h8ck16+VUbZKfVib1HN2UgtwvKHRrI7kOIGSmPi6JObXsb+07BpBmDGVkHUvb9K1bX6WYpbdtPjyXf4na2StuMVlZA==,iv:Penlpp2X5uG/kgjhGhATWdYPswO1HJcPHoAQDDnDBfY=,tag:ELvcbYMf8GXrJdul9CzAjQ==,type:str]
sops:
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cWdhaFF6NFJQRVpmMVBT
            bndUWFFkbTFBZCt2aHlvODBmOVZlUnlUYWhnCjV0NlE0RklIbDJWR0tRSXBpaW9V
            VlVxVmE5Zy9nN2pwbDBTNm8xNERwN2sKLS0tIGl2ak1KNkpkQmwzR3owdndkMTMx
            UzIyc0hKMDdZb1BHZHRZdzVRQUhKUTQKt6NY5d2yfbh0k9CI7u+5nwLRcCgQVqHd
            tZ3KEFr2EinSgRHF1io/bRznpQyhtAHTYDtlIwzkZD7yqhS96M3yyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-12T22:37:39Z"
    mac: ENC[AES256_GCM,data:2Vus6zDJcG53VR10/wFYbZTfkZRZQJgz73+u4cRf714qaeY6iOvo5UbkHJ7uspEsSorKKQAF7VnJCIhUVPmswLcKifWg3QJYs2ak/CxRjYDrAyfuq8d9bvb7tZ2FTRqmEusai2hoxZ1rG8n9eKf368p3LPrSaT/RMwvW6FKo0fo=,iv:Hg/t3Ya/IhSGRbYVhDm8Bc3Kwd38ZHPYKjpHoaMQEv4=,tag:M9xPhc/1F8qQWSy9IxeuTA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
