apiVersion: ENC[AES256_GCM,data:37s=,iv:GD6TOANDIMpi69Ugia26Eq8xebBCPhEvZjgsbfbDvX4=,tag:SJr0dCo3cQL5gd/Fo8xTWw==,type:str]
kind: ENC[AES256_GCM,data:pbCZ1Viu,iv:UAG0rRMgey07x91mKykVT+MfJzBToSLFQW0sV5UfF7U=,tag:rwtLiOtWK2qI5PK0uIXEgg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MW/ATW39I8/d2W6js14=,iv:abqtUwSazEf0Kuof9bXlr3ThMADvgldIlWyBFgYWRAY=,tag:slz1nYtfND8B06UfdkxA6g==,type:str]
    namespace: ENC[AES256_GCM,data:nPLAo7U=,iv:2jwyg/Wc6Li/kI6vC2BKmT6HU+gZeVrENM6ak5XEdLQ=,tag:GYRYqhglCNRzxTBJtiYSOA==,type:str]
type: ENC[AES256_GCM,data:pwpCLDo+,iv:AwX/shKHQz7JVkf9sY6xw96mMcb6eKTGqd+NfDCcRzg=,tag:fp/htR8oGUFKCrpr8X/LeQ==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:SWpxYai4PNcqcyx/TERS7Iba9tE/QwS9fPI8TpIWX941IEZay7QPSOtF0nl70yma/VwGbhG/OVfjGcOSb/NuP45bDZMPX7Kd4FO52YuvcQvxW/ZOFJwL8SLWDLCGbqHjElf3LVM3jUacet3SCtXqQlP3bPM0cdS6i6ScGuyBKyB42X6UPL1r2Y4ukVQL/QHJnd30SDpdyFSBBhAiBNTdqoQSiB6Bi5M=,iv:Jvj5dntPvQ2tznpDx8PhCsMZj36FCvdaoN6P6T+1BK8=,tag:4MufSj+R5z4zssN7PBN6Lg==,type:str]
sops:
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0V0ZRcEtTWWhFL1dBdHBX
            YVZLUE1tK05GMXFWclFQN3FNMGNtVDg2ZzBVCjlLSHh3RzVQY2Y1ckUwV2dZcndL
            STRQRXdEOVQ0dGNaUndmajNycXJOM2MKLS0tIFRVNmR4SlBUTkY1Q3JJaXcvQy8y
            cUNkQ0t4aURvN0VMTlVpM3pCRGRCckUKt0fQNZxEFVab6HPTFNDkNUscgXterN6V
            0tdJiX+UyF7C1UWUMf2pJ4DRqoXNEFuIWm6SM8x1YxFBXmeeyjRbaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-30T10:49:25Z"
    mac: ENC[AES256_GCM,data:/6I0+xyjc3I/vvuoz05DsWFndUMqra5pQIWohDhX/ZnyM+abw4tUKDXu9cs2VwEnz1RmlZg0elwErDPG9CkGZDy/nWFb3G+JeL7JdxRW/Q1WRMS8iHRur2keGQKNGi2Npq9nN5uFj6KTxj/w9dlWdiQ7nnnQTepLffiH0JJVxXA=,iv:YJ75NPb0GWbGYM87JxUxeH1DT/HA9hdxQKv0Oit17DQ=,tag:rvOXPOhVerAmnOfnbLQMDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
