apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio
spec:
  interval: 1m
  chart:
    spec:
      chart: base
      version: 1.0.x
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system