apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secrets
    namespace: cloudflared
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:dxW2F9QWZ5aE45gIopWgcoIPvfm6Pd/82Kz/8WPo09U12u8VK9238dLXm8fgRvr6ltSEYnb09ggcvw6OP1i36T8MR+xETlLhqeK7x95PYW7N7XxWpQlhleE/fSF00JON9wWFftEA0rUo6F09lJBSVryEmk3iaOpdpH4XM5dZqhaFJtMG9YzjnnN3kPL7XbidhyXGAv4NEfpW3neafyINagAW0lTd0yeiV76QMt1mcqPtfOow0LwxtAqMSbb4ZzfgmqxpXbTHaxuH5nXzmbM936+ACYc=,iv:jGO0A8HSmF/5y+6/KyRRWd9GLyyYK5hKFMNCbL9L7Gs=,tag:IzvrSZ/7aGaZg5KjODrV3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT0dHL2xKUENFRU9GNG4w
            T094aHhkNkIvLzF3dXdOQWFQQ0x2NTJuRGlnCjJGZGlrU3RSUjBueDQxUUtLbkpv
            eUJ6Qzg4UFdadlhIY0g2anFZVmxRYW8KLS0tIHdWNWhrQ1NpNyt3UG0yTDdySlVB
            WEFyYUJzZG5jWTdqcU0vMmIxNDVQcWsKuRwaC+zOazvODCX+9+UrYgW+SNkFu7fv
            s+DdHsSqfmIAafrgALmAI8ZDPnxShnL3xcc8zeOH87LtQ1GXthTTCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-17T22:18:03Z"
    mac: ENC[AES256_GCM,data:cjh7Ht8+AE9f/uodALy8RG/RdrFzYBnaPLdIMYcHhbDDS2rM0fnoDUc0FDSj/oPaHhchj9g0evUdswUBKBnLrj6wZbwm+Qa5Mp+Q97z1uzrNyC73if2mPqT5BUUcJlZhIyYnv2eEd+sVhgx7xBvz+eXpc33UZrugypyiDSRGtRU=,iv:hw643dkN5B00wtHkkZ7V8OjoMZY+87zwOT8tgB8+UVQ=,tag:DxjGGL81ajqF7Kpqgmj1GQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
