apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: bazarr
      version: 10.6.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  valuesFrom:
  - kind: Secret
    name: bazarr-secrets
    valuesKey: values.yaml
  values:
    image:
      repository: ghcr.io/hotio/bazarr # {"$imagepolicy": "flux-system:bazarr:name"}
      tag: release-1.5.2 # {"$imagepolicy": "flux-system:bazarr:tag"}
      pullPolicy: IfNotPresent
    env:
      POSTGRES_ENABLED: "True"
      POSTGRES_HOST: "192.168.202.1"
      POSTGRES_PORT: "10009"
      POSTGRES_DATABASE: "bazarr"
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: subs.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        secretName: nmoura-pt-tls
        hosts:
          - subs.nmoura.pt
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        nameOverride: config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
      media:
        enabled: true
        mountPath: /synology
        existingClaim: pvc-bazarr-synology
