apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: bazarr
      version: 10.6.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/hotio/bazarr
      tag: latest
      pullPolicy: IfNotPresent

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: subs.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: 
        secretName: nmoura-pt-tls
        hosts:
          - subs.nmoura.pt
    
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        nameOverride: config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
      media:
        enabled: true
        mountPath: /synology
        existingClaim: pvc-bazarr-synology