apiVersion: v1
kind: Secret
metadata:
  name: medusa-secrets
  namespace: babybites-medusajs
type: Opaque
stringData:
  postgres-user: medusa
  postgres-password: your-secure-password
  jwt-secret: your-jwt-secret
  cookie-secret: your-cookie-secret 