apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: firefly
type: Opaque
stringData:
    APP_PASSWORD: ENC[AES256_GCM,data:XdN8ZA50tc+jbA8UHN3WZKMiBJa5czNyUHsuKsyUK8k=,iv:MkT0osGGvmHsmBPFkpyH1vgyTVtEPx4q3gdt+l1CwKs=,tag:QKLMC3LUkVBJXJjfKjYaCg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:YqBXk9cpLoSpYR/EREQhhZnEKzwltUx0kmCAyU9JPRI=,iv:EAbglvDKS1yAv91WagkKadfAY1d5yyQZIUrRBE3nLVI=,tag:knoGXDBWSGDjFw4E0ru7sw==,type:str]
    APP_KEY: ENC[AES256_GCM,data:CPRIGGLFEZHk4Fmr5famIO0KgHDPnCdoUfpP65U/q1U=,iv:eD25X4wnjlV38v1mk6f+8QS891agOFFPzl0TkOieJEo=,tag:vTYKLBpPve7VwZxEKlsf9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSE5iUVo0Y0Y2SmthYU0z
            OEkyNjF2KytPdXhwZGROOG9QYVk2MGVXMTE4CnBGdEt3VXp0L1hjUU1lMlJ0RWN5
            UzZTYmFvcUVpejI4c1pWdXhYczk1b2cKLS0tIHZlVFVtRXhYVkhjYlZ4bW5uaVV1
            aWcwR0JrQTloMHgrOGhjM0RPeTYzWkEK7FLFS4Mk0xJTXaFtQeeRE8Ww0EBpbBO+
            qyryBDQ+f3KXH7/iGthzrk/jTex3I/zl97bcX/lRk+6iyYUCvSd5gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T01:16:21Z"
    mac: ENC[AES256_GCM,data:aAocaYbMFhUFY+ObnUvl0ajHCLsA8H3ZYUNYPew/jPkC5FLYXpSRJ5PLuN/P1kxUyl5X9SpUZR4VNsqChevCgZbWHLxg1jzt9sSPiZU34F7KLuFg1QzFY6DgHRKVI/IGMbVoKDilg231eaqmuGEq49flHF2QcK6Md30F1wklyyg=,iv:y63bSt6TIfg4r9oZOF0aeePqZyhvoyGva2M6/5YwP0E=,tag:NxYN4N7yuCASTxuo0XBrPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
