apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: firefly
type: Opaque
stringData:
    APP_PASSWORD: ENC[AES256_GCM,data:ZnaVwgMLQA==,iv:vvVCY6B3aPNrNDSaUpUtAoKOkfvmbyYTaIiCy2MZ8Gc=,tag:Zp2EmInuacaNkLA+Z1Q4+A==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:X9sAlk3Gug==,iv:a9fsx+oXy+BJzmPmTKbdqCtIQqTQIq4ruvBeveTUlHI=,tag:fqufJtXycDGc5ZPS/RCJoA==,type:str]
    APP_KEY: ENC[AES256_GCM,data:6jzfUkqSfwPg3Cazi2iTKA55MOBdKWVCXHK1JzE6QCY=,iv:HepEm2vDif7uhHNI0k3MyAhAkwXOk4MELVTNr2PEPmc=,tag:n9mI2j6B8KYzem3vPVpmWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZnRYNkpja0UvUkNpamxG
            RnBONWNqSktxUno5QUlKRGtRMDhMRmtoajBZClFtcC9PQlZhYk0zL0plRTc3d3Vw
            NnpoL0tDL3BvNzhCMFc4M1JiYWVxMjQKLS0tIDlaWUpGVW1pNy9mK24waXlSNTgw
            Y09xMVFZbmU0bjF4cUxMK2NVelJNbk0Kaw7nGa8XoRsBM3cBCQ2+giGyd36vkTB/
            t1hu3X73FQrX3nsj143HKaZXFQYNAnJE9LjFAnZocX47xAdnb9tMOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T01:31:08Z"
    mac: ENC[AES256_GCM,data:0kh/4EVMqx2eiBJ0Z8lz/czKz8AOqEc2eARVDvZJsSjJ3Qzug9BLQqZsERob39zjeZSS6DDcsvQZ4ba/yrww6TOuojsKEYpuC1pGMEPCvSJI7y4oOKzPQHQT7UEykxLO0KbDnyguoxdBmkIR/RT82SuyM7xDHZyCtfKyFMKTeok=,iv:Y2ACEcgymR3EgNz7V914xatDHVgIWBg3Jhvu7FPcIr4=,tag:sVd8YqWb7ZAxTN5qB9nkWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
