apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: plex
      version: 6.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/hotio/plex # {"$imagepolicy": "flux-system:plex:name"}
      tag: release-1.41.6.9685-d301f511a # {"$imagepolicy": "flux-system:plex:tag"}
      pullPolicy: IfNotPresent
    env:
      PLEX_CLAIM_TOKEN: claim-1zHA6eWAgEkDQv2zAovZ
      PLEX_ADVERTISE_URL: https://media.nmoura.pt:443,http://192.168.202.152:32400
      PLEX_NO_AUTH_NETWORKS: 192.168.0.0/16
    resources:
      requests:
        #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
        #   # using intel-gpu-plugin (https://github.com/intel/    intel-device-plugins-for-kubernetes)
        gpu.intel.com/i915: 1
      #   cpu: 200m
      #   memory: 256Mi
      limits:
        #   # Hardware acceleration using an Intel iGPU w/ QuickSync and
        #   # using intel-gpu-plugin (https://github.com/intel/    intel-device-plugins-for-kubernetes)
        gpu.intel.com/i915: 1
        #   memory: 4096Mi
    #podSecurityContext:
    #  runAsUser: 568
    #  runAsGroup: 568
    #  fsGroup: 568
    #  fsGroupChangePolicy: OnRootMismatch
    #  supplementalGroups: [44, 10000]
    #  seccompProfile: { type: RuntimeDefault }
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: media.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        secretName: nmoura-pt-tls
        hosts:
          - media.nmoura.pt
    service:
      main:
        enabled: true
        type: ClusterIP
        externalIPs:
          - 192.168.202.152
        ports:
          http:
            port: 32400
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        nameOverride: config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 40Gi
        retain: true
      media:
        enabled: true
        mountPath: /synology
        existingClaim: pvc-plex-synology
