apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: plex
      version: 6.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/hotio/plex # {"$imagepolicy": "flux-system:plex:name"}
      tag: release-1.41.9.9961-46083195d # {"$imagepolicy": "flux-system:plex:tag"}
      pullPolicy: IfNotPresent
    env:
      PLEX_CLAIM_TOKEN: claim-xL76hu9vS4wzsCFkthVH
      PLEX_ADVERTISE_URL: https://media.nmoura.pt:443,http://192.168.202.152:32400
      PLEX_NO_AUTH_NETWORKS: 192.168.0.0/16
    resources:
      requests:
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 1
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: media.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        secretName: nmoura-pt-tls
        hosts:
          - media.nmoura.pt
    service:
      main:
        enabled: true
        type: ClusterIP
        externalIPs:
          - 192.168.202.152
        ports:
          http:
            port: 32400
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        nameOverride: config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 75Gi
        retain: true
      media:
        enabled: true
        mountPath: /synology
        existingClaim: pvc-plex-synology
