apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: plex
  namespace: flux-system
spec:
  image: ghcr.io/hotio/plex
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: plex
  namespace: flux-system
spec:
  filterTags:
    pattern: '^release-(?P<semver>[0-9]+\.[0-9]+\.[0-9]+)\.[0-9]+-[a-f0-9]+$'
    extract: '$semver'
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
---