apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trivy
  namespace: trivy-system
spec:
  interval: 1m
  chart:
    spec:
      chart: trivy-operator
      version: 0.24.x
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system

  values:
    trivy:
      # -- createConfig indicates whether to create config objects
      createConfig: true
      image:
        registry: ghcr.io
        repository: aquasecurity/trivy
        tag: latest
        pullPolicy: IfNotPresent
