---
apiVersion: v1
kind: Service
metadata:
  name: oauthmail-1994
  namespace: tools
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.202.154
  ports:
    - port: 1994
      targetPort: 1994
      protocol: TCP
  selector:
    app: oauthmail
---
apiVersion: v1
kind: Service
metadata:
  name: oauthmail-2465
  namespace: tools
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.202.155
  ports:
    - port: 2465
      targetPort: 2465
      protocol: TCP
  selector:
    app: oauthmail

