---
apiVersion: v1
kind: Service
metadata:
  name: oauthmail-1994
  namespace: tools
spec:
  ports:
    - port: 1994
      targetPort: 1994
      protocol: TCP
  selector:
    app: oauthmail
---
apiVersion: v1
kind: Service
metadata:
  name: oauthmail-2465
  namespace: tools
spec:
  ports:
    - port: 2465
      targetPort: 2465
      protocol: TCP
  selector:
    app: oauthmail

