
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mkvtoolnix-synology
spec:
  capacity:
    storage: 10Ti  # Adjust as needed
  accessModes:
  - ReadWriteMany
  nfs:
    server: "192.168.202.1"  # Replace with your NFS server
    path: "/volume1/data/media"  # Replace with the path on your NFS server
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     namespace: media
     name: pvc-mkvtoolnix-synology
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mkvtoolnix-synology
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: pv-mkvtoolnix-synology
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mkvtoolnix-config
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi