---
apiVersion: v1
kind: Service
metadata:
  namespace: media
  name: mkvtoolnix
spec:
  type: ClusterIP
  ports:
  - port: 5800
    targetPort: 5800
    protocol: TCP
  selector:
    app: mkvtoolnix
