apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 1m
  chart:
    spec:
      chart: uptime-kuma
      version: 1.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: louislam/uptime-kuma
      tag: latest
      pullPolicy: IfNotPresent

    env:
      # -- Set the container timezone
      TZ: Europe/Lisbon

    persistence:
      data:
        enabled: true
        type: pvc
        mountPath: /app/data
        nameOverride: app-data
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: kuma.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: 
        secretName: nmoura-pt-tls
        hosts:
          - kuma.nmoura.pt