apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 1m
  chart:
    spec:
      chart: vaultwarden
      version: 6.x
      sourceRef:
        kind: HelmRepository
        name: andrenarchy
        namespace: flux-system
  values:
    env:
      - name: ADMIN_TOKEN
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: ADMIN_TOKEN
      - name: DOMAIN
        value: https://warden.nmoura.pt

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: warden.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: 
        secretName: nmoura-pt-tls
        hosts:
          - warden.nmoura.pt

    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        nameOverride: config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
