apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 1m
  chart:
    spec:
      chart: vaultwarden
      version: 0.29.x
      sourceRef:
        kind: HelmRepository
        name: guerzon-vaultwarden
        namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: vaultwarden/server # {"$imagepolicy": "flux-system:vaultwarden:name"}
      tag: "1.34.0-alpine" # {"$imagepolicy": "flux-system:vaultwarden:tag"}
      pullPolicy: IfNotPresent
    serviceAccount:
      create: true
      name: "vaultwarden-svc"
    storage:
      data:
        name: "vaultwarden-data"
        size: "15Gi"
        class: longhorn
        path: "/data"
        keepPvc: true
        accessMode: "ReadWriteOnce"
    pushNotifications:
      enabled: true
      existingSecret: "vaultwarden-secrets"
      installationId:
        existingSecretKey: "INSTALLATION_ID"
      installationKey:
        existingSecretKey: "INSTALLATION_KEY"
      relayUri: "https://api.bitwarden.eu"
      identityUri: "https://identity.bitwarden.eu"
    domain: "https://warden.nmoura.pt"
    signupsAllowed: true
    ipHeader: "Cf-Connecting-Ip"
    adminToken:
      existingSecret: "vaultwarden-secrets"
      existingSecretKey: "ADMIN_TOKEN"
    timeZone: "Europe/Lisbon"
    yubico:
      clientId: "103892"
      existingSecret: "vaultwarden-secrets"
      secretKey:
        existingSecretKey: "YUBICO_SECRET_KEY"
    smtp:
      existingSecret: "vaultwarden-secrets"
      host: "oauthmail-2465.tools.svc.cluster.local"
      security: "off"
      port: 2465
      from: "nuno@babybites.pt"
      fromName: "VaultWarden"
      username:
        existingSecretKey: "SMTP_USERNAME"
      password:
        existingSecretKey: "SMTP_PASSWORD"
      authMechanism: "Plain"
      acceptInvalidHostnames: "true"
      acceptInvalidCerts: "true"
      debug: false
    ingress:
      enabled: true
      class: "traefik"
      nginxIngressAnnotations: false
      additionalAnnotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: true
      hostname: "warden.nmoura.pt"
      tlsSecret: "nmoura-pt-tls"
