apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autobrr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: autobrr
      version: 1.1.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      # -- image repository
      repository: ghcr.io/autobrr/autobrr
      # @default -- chart.appVersion
      tag: latest
      # -- image pull policy
      pullPolicy: Always