apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autobrr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: autobrr
      version: 1.1.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/nmourapt/autobrr-qbitrace # {"$imagepolicy": "flux-system:autobrr:name"}
      tag: v1.61.0 # {"$imagepolicy": "flux-system:autobrr:tag"}
      pullPolicy: Always
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        readOnly: false
        nameOverride: config
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: autobrr.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        secretName: nmoura-pt-tls
        hosts:
          - autobrr.nmoura.pt
