# kubernetes/repositories/helm/cloudflare.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: autobrr
  namespace: flux-system
spec:
  interval: 1h  # Check every 1 hour
  url: oci://tccr.io/truecharts/autobrr


