apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-secrets
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Va2gzio8zX+fBO6xtice54GR2rR+XYd5enCcLTJ9ecQPzdmnWzHPQPOb2y0TEtKH54hGg4n4Xwbu37CSMw5dszPoCmurBe2PVszDJYfvN/o8bxwXqoZHJl2YNHfcnnNx0NqqZ8LjRRnqWP/BY+Boy7NKXfac7YAhLW1bEkBy53v5I47T3MnY0DpTGzRR7r73Yh5yGQV8E4nZATVsa3Td7liifDiVrAqLzFaRTfHOaEy8IieoUiglM/a7+iytZATpqwJ7GAH8K97qvRGOHLIUnLdTCkzwHf+WIL5G3YNc2tMliV+bgjHuK4DPIxX0IsobZOj6v7+qgmaTfZ3XeKxGGaJAvaaMu0A/cubK7JtIx8+jmytlUm38BVTft1kQNYfMl9ars7i+7fevhXSc/ZLSFvTaRdXrmn7oPWd1JJRavL3Xsal6DrfmGm9N2eRNMV28h4/AXkctEBJEQSt/pbgG0Jdr9S9egK1tCu7f7d0VFF5UuVfrLDMw/0HUj9zFXt4Eq4VZYTQyXIaCUByABj1n7Ci3jwq7b6z8MnGHCJ/JozsIT8vwKFlKEkiVD3zaPAq6+2HyJ0fHufwljjXYd6v4B/W6W3jDWX9EebPGsmVBtUVH403H11qetoAAsKjXi1ksiEJ2FjR4tloWGM1WGond+BextHcqaHzXzcBz6obD/0Wz225eZP6jT6y1nJ8btXXTnqfZv6JxS+wRfUZFpHanOCZGVDld1JHlp8cakHcE7m9/0SD6FmXIzpybaOzqOxhG0Hwol9k+cX3fiMV2LagtUbF8vD/gkBWykGfx66P+a4hS9hUrqpePSDns6LLQBmvJZVDcL/mjj617Do7doBwC5LfNI3BJyK9D8dEv+DzWbvjD/9639q4emNDXuZ1AldSe3BIJ4Tc4bUNhg1sqmhkWeEAiojfOX1XOxshmDGImx68zBq1R1qt0wKcSIV6VAzITEciDHzBQTDCXVGHLpxNT1bnC7+bCpuVqlDEN0gXUB1/A96k2VJbNrVkO6oYRrOviaIwpN3Blxl5EkDMemetrb1Zge/BzdU6snOXyl2SzO3vCwZUKWtNjydYH0jERGXjHoJg0ZXDtQoi67t0i3/E8hNUzdaNBhw+h3YZzfE1dlIyKHhFcOl5npi/YUJHoT4gbPdfKKcylNNrSS+CEWWjl+8VBaT5iuntQF0fRAPEQ15A+JrWvd6NCCgZI2oB96RXhI6vmcqeKsG4QO/sazzF4HoAAuElSiICWRo6bHaflhE05dCJ9Tbzg+e7Sr2ZBg7l+EnoL6pLTJDCLQ/rJn8MkVQzz5iHZAu2Xm9/KmCMrob/IR0z3/bc9iXs6xw2FFwps4zlsTxFOvXLMVNtmSA==,iv:y4w5WMh0I9xl94LRsSPfubhKUHbi3CM5EZy0p2R8uNM=,tag:gaQtMSG/O9Wkkgmhnwi1lQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaWxFczJIeU12dHBDVFVj
            bzZTWGJBTnVmaE1HWGliN2FmWEc2S3JtVW5jCmpXVVkyeFVJTFg1aWVXdi9RY3FE
            SVJNY081VkYwUDN0bzJxQmhaY1BxbTAKLS0tIE11aTROMGdRZHR4WFk0eUhxekxH
            ZkorT0E1b1N6eERYSjVoeHU1MVZOV3MKuLp2W+4KR9nI1GCXzBvzGrohBAxsiN1c
            V1m5DIv6djDXSRrpCn19jc03INUuARGI0jdvSb7XImuGv9Zesr6ZyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T00:04:08Z"
    mac: ENC[AES256_GCM,data:ujLOGoXQ95yVGmvgRKeeesFlN/ow5SZvxGntGHFWZk2RlX8pSxEfmeH9LuedOWnxkIlcFPOLSq8IINC6DvxwDZhxk4GPjlyk43PftuiMZtRubZ+bw5lbHPNFSpZTBo1TMThNjk147X25fc3f4rzdMQqh0ECSLZbomvSAs60r9nw=,iv:ScDrPY4jgLnumpBcHHSIoFCKmDvTRp/Pd/yzHmgzcPg=,tag:1+5jzKnOHgq13ew6J43/fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
