apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-secrets
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:OLNtXmzeuNs4K9RjXBOEzviJwEpBnepyLxY8+6P9YG9O3F5rezX16qsrBLwqNlYFKa0q1kiDwUmXF0jHgpI13r1fZ9uXlh+fQTqFUyrGUy557dFcyZWwELTLeBYt8G1YitauYljNvXkjenVd7gpNS0gE6LswNgGDw6tP7WF9xfGuqYkoFw8Ki4FNe0T69Y8bm3ZCGbX5GDbZ/5CCmxtvFreoer2BDWxgHPJLIFWExEQYTKys1RIl8yWUyNZNVWioHC6nReAP8E5mCyyRugl+OgSoCbMtM7HqCeDLWNdWbsLo1IrY/hz9hmkOU3zEOiPLKweXpxz//ZsF3SZCVBejMSgqnIyNoATStTmCzWa8LIyWUfRb0lkD7MIwDdWgi5N4Bd8PgdOh9Elqsyw9rZDg3t2hKV/Xe5cqZMbnBDCGVvoKySwHALb7qaqnIwgavKmyKmoCjiVMFMSVMRcOFaRcIeZ6IW1eWoJlkYC79U8zRe124SX2dsXo1CWluh/ThFqwjK18+1N07Xg6ANnJwISbGtS5kcOMfdXB7vQRnHSOKhNk2y+HhNlR8zOa/GDKK1MFMqceWzc7HKmtpitLlB5TY9RbYFI2sNRyY0IKmMqic84s2mgA9UoKogZ9Ag5Tg+aeL1WzEGhqoJpRogBUJCB/1YuAjPwG0yAg6lpspxnKVoyxb75FfWANNblzX0S/MU0792O05RwhXDye4fnl39vSU+zcqaX8fdATsAn+RdrDMz8mVpqOVWeRkfOq0hcUaQshdvVWHA2fLt93nWLqTsW8uEHoT4brq4MD1BYp/OzYsIrG/BmMfgJckrzMTD8L2SX5vtAcgpP1eybZfO3eqT0m7gVuy9BvN2kyJKpppa2pKiqXGFnEUH78amjgjfJeaOUCu3+KNx3o/vtqHt4BbdmefFlwkvWWHU673iFQuBo8zeu4Zo3W14Cbi1zUIA7G5WSig80gIVc=,iv:8FbxYU7TSw7rljCYQIKG2Z7rwPjLIpd9AHtK9TV4IPc=,tag:gYDVvQqVkQRkHKvcqQWTfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBablJ0eEF0TmpZS0szZTNH
            OGJkY3RLZHE5eWt2VTFFb0VqcTVMdy8vRWwwCjZMUWh4UVJkYnVTQjM3WjhqWFNL
            QlpYcFFMdDhqT2tFaVlFeG5mTjFUREUKLS0tIFAxakZkeTlGampGZlVOemZOMnkz
            OXQ1cytDZENiYkdKZWhQdDN1Nmc0RUUKMb70kYkB243krrzw79SKv2xRBgZmL++m
            JQBnAQQhORCAAOa6iPkjOv7YOE0+SD4EiQ+G3hDJ/CtqS3i3Qf6oXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T08:36:25Z"
    mac: ENC[AES256_GCM,data:E/UDsMLxIYgUkLiWdknYqx8fQdcrMgvpA26OYgUX8PU/5mn+AXuE8s8yMajD7R1uz6HKofZQSUhNUy5HlaKwhzyUMMPwFbzEqcciaLkEkJ9bfktCcsgaf827+TlyTxfvnQWhopRcslucxeNXHobrLn5lWL2EbjQEyb0DGXoPa8s=,iv:rW/w1UtdUZmf9UIn8X+kn7q1mAzTHRbnWSsgk2Dq/EM=,tag:vaGxY7kE9ptMcvByRk4lmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
