apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-secrets
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:EOYA5l44hjoR0smYysgC3+NKIyoPDb+K80h+qTQy/a4C6RSLyOWXBqUOVhT0ayMJ8m4/IcUNuHthPH9RdLK3yqjcLluSX3M0TuO36J5abdbIfOeGRoaVDJaljU3MG6+/l0KhSPDd1I5MTk5+Sr3835YvtrSH1uGjvlZhAHSIPOUnTMPy1VLHt3XejQKCq6B3iWTdjrz7HFRrDCYpRvvamuJxWjFJdF3Mn5DbqWGADcM/+pUau5lquehU18NttaAhCPZ0bENl6Uy1pOrjDCGcZT9prMXC/NV/ZgzXYofwTg/mPAdeBEPD/A8qwv3kn5OM4/oZpfvbqAXDYUV21mOU4k57nJAJtc2MofxhyGN+BuChx7rfmTbVnEPajzSCB30auGNZxFEBg6A0w20PyQ5GfH91I9UHdGoGCToKTb19ZlzgrLYMAoPt5ZQj27gwZosjuWJz/MhlOkaRyGZXk/6O9CrY0qOFZVGtwA7GJ22x9hCUe0K9ELhQ5nrrOjlIq8FLFrjN4G7Sa2oZaABfl9RCiBDpKRKOeWdHY+7Kcpx25dVGDXEUOG6mpjvmqi/EE5TqulKCYcS6zI7iuTwvOEBgmxIf8VxAf++Jk1575o/jxyf1MRvLwjK9fMMa3cTeJjM2OwXfsGLKFLoNYATuc7tzRa5zOjIklOwWfynNO2fH0gjddv35cnTzRlhGejpLjvSXTylQIeOFmBo1vSOfV1IazKYn/xq7hw+KGlXL6E89z42+h/VYHs6SIEy/1Eq/Zh5UsSLuDwANdBR5wC2uAhqRiU18Z6tuOjcExN2RajbRFUUVDqyz4sigMIRXDxmjYMZFt0dCXtXUxp3Cll9jgU/A0T2ium71C9QS6tKaFDLg2zXGCE3i0KX1E3xF3Da0Am58IXgSlDTs2Zz9BiJwsJWHRcmNZE+FuIct0uLMgFQcacL/x0WKA25zBX2FNOQ5u1DhN2nzHQezF0u/ZXCR9lWUk2MuOmT7WnZR7fxBTNzwevw0yB1hD782QN34YGYIBidQStV+wcuRkSWqJ5FMfJdz1M+qVRHPzwhZnoNjxo18AL8zmdI5/VQbiK1mnyVMp312NMEXxHtmaeE85khlYRY39iWWwBL7qkvDQdXCHRyYUd2EtG0OrPKwLb7DF/R6Drp5RWt24goSmRyiAk+vAzvQMpGjmwS5oPz5nhf4QMw0yS1tYf2nRWLlxH3rmVTqXtmhMndzlK/Rp12qeUIDLww=,iv:KFbDMMsPH3ZZUD0FUR4wX69zfS1vb251dC3GlHo8KnA=,tag:Q4YoEbM/XQKoRPNtwkh1qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bUVWa0psUGpMeTVYbzNK
            U2RuQVJUT3h4amhwS0pQTUdnY2NiOW5zbWhJCkNTUjV4ZEFGbHNjQzVxUnp4Wllk
            R01nTkUrM0UxZVpRNGZvS0QxR003MGsKLS0tIFJySlhUOWVIbEFSTW9xL3VxM2sy
            bW9veEkyUjdqMkM4YTVJNnJWTUd5QncKM95D43Osb+SW2cYNHTFr4nhLL3pLMxce
            8Fqqz0rd+3vfhsDIsxgwhTatOHchbrjS8jvOusyqDYIWVxot4jYSNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T09:37:08Z"
    mac: ENC[AES256_GCM,data:6k6f1muQh4bPao6GT0gZaPzCfllolReVd9OIcP4AtGmyVNa4kHnsQQMBZ7f6SyIFnUC6F/0DItpk6FFRCmBlV6UizbDMkrWPlisdVa+4/Y7tT/xgWPCp8I5/g3kUKilES4HVcOfbuzryeqzGTvWk3tI2dCwL72MAIq0cVxfy53Y=,iv:lM9B1aVJccfGYXOH5xPmMQ9x0NGwQxVAAULqC7YXiXQ=,tag:UDAg9fqrtYYyF+dRh1g5Cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
