apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-secrets
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:PeohKRRrWJnqct34Ys5fmzgAN23NiwGjjrSMVwsWx4xrw9w8rvqMCvnV4hkF3OvZkhL+HhhqwrJlrk/M/Ba0w7UipsPMIUAsVZfNCUu4YEo8Oj1qX3I3Yl1REdyn+wzhkGpgc3eyE+fol8xAHQ7a/BaXIMraiaAeE3ZDiBnDPKZoLB1pljAXoCxDQPfx+W7wpqsY7taUoRDShFi6haxgWVNIp2wBmLaddHIomq2QMM7i2y2ygiQNEzaqhevqYjNM1ced8GcHV/oGlJZrYQOGl1X2K01u1yhmjtw8saT87e3DL+VFHke9UDUTCr+EWynjuiDblvFl3Ztb3JJQCQdyYHtzaGapEG8htJdt09cz/b8m5rkcEg/IWTWxFVSFrTRtlEhq1ZvXXBhGjzwSyppP4yhGeDjPkgkKEMdeV5E9hYHHejQTb7pw0PSSiCFdgYlGONPV2Ap7BIsQogYnnYsS+iUoUepAPOb+jySh1sXrZ0QlyRC8L6SDyxufGCDMvJu1eqTFvWxEskt1qPnAEC2WWvNKstAc1qACNPpnEC97E+0y/06m8qNE5m9rOuXt33KEKgPLC96uhx6Wj8hW0DBAx7Lj2mTzKa+1h5OoOToF28Zne6BoWNLmMvo+/mK3p1dbeBaOk7vzmD5nLVZhD0O6V5sS2VYM/K4pAu1pOQGj8tPCHhUUKhhq8RF/N90uP6tCPRmkXuQNhiS3PQ4X3QC6+Y4ttKyagtJE/cC9OV/p0Qj7yQCPlMgtO7oMh4BNv7ezDVDBVoIM5kzuROGjD9IzVDl57qGDwgN1ZLfpqgStc/PxlurZM4z80FVf1YN2QA1laNtwmgLBogg95kdP95tv1hCNmNMsuBrSqaoP/pYZPBRliDPgFhnX1r/r45sV5Ts9ekTbUsrlWWP2c3P5d40GsFAgTXptkZncvBrgx66/HcWVhNnWfaVBvmrcdLqy/UHtum6INKX9lM16RPsWg5PrBnYyvKQJPcE1i2sJ1XmlrfoMxKvKno2vHmwdlAkQprVm0GCbsX0T5Ya0y/Xbb7/jDKGHsCWgXnlrtqVFj5lrAgyQ,iv:IXiw4unJXmNBLlCELrOBAs2AY2i21Nbc5t3MaA8Xxlk=,tag:gfg+77ggJxtyOY+ZjyPvEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQU9wb1FIL3RRYUs0V0pZ
            TmxxSC9RSG10bVJSUjY0ZXl3RkZITmVoKzNJCllmVVhaM29oOGdlWU9QbWswbDcx
            VGM5RXg3UTByTUhaVzdhcjVXRE1ZR00KLS0tIDNsWHp1QTg1Z2VsanlSTm9ORTRQ
            ZjJoVGVKcU9Tc1ZmZ3k5bUR1WTZML2cKfmoaw++latpOAMcq/2XJDRFYiEDJB9kt
            +3ZsR4JhBTG/Ch1+pMw73T5Gj5Eu5gFKT+SbGI0JsXoyzg4lr4aqjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T23:40:47Z"
    mac: ENC[AES256_GCM,data:8rOSb0fbf001vcx/5yUNGybRbZv8f6FaAbP7utkrDa2a0SjPx4aiLUVGAfRjrDvZ6c3SpUytv5IPH0P8+qoZAPkZadn0KGrOPOdAtul4KmthLV02M9DSFxf1A4pti/FmEc/msH1OSLb6TGiPW2GjAR35IEKcSlH4vQEt7CXKxQs=,iv:R2S/b5XEIOiwDQlI8+InxBOYgNvKBXB5QlyX0hp66zg=,tag:htn0a076ophl5auy1+jqbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
