apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-secrets
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:VBkSmRlFMEZKUVhQ+pEd4Masj9Ca+5/ygMxGJ4+4Izi5spAjq+Rnww9vvbHA/nierybdyPbSFTKQdu4jHdw2qHy46bruIQD6j92GAgBJwuPAf/RQ3LmhLOAmGVvecyZyw+oMv2M23al8pPl1CT1WPr2hISivwhX9G8zbVssOIjCjMRNSgA0zStayDhX/Ruztrw41asH7vqTrPO9TublPf9KFg+7b0HlZad80TeEyXdrFwG9e4tP6C1h5DOpQXgfPLJ2bA6ol2trRM6wk8S8Kpu0gNP82Edj/yuOnJ9nIq7CiKCc7JOS1gpygXAbZjbC/HQSvKDHBz2n0mk9HTaInA1ND6cWg8PZtUL52nlvt+ZwF1MsVmwk2aZQw/g+xDIVhIDERhCp5RnMI3TckDNI53hxOmkDq/EQltypwTcAcw52XrZ6ahbOJrnAqgwLaRKzWGpyVVWvqBjbOYlultfYM04NM9+lhyVq+SKuIxRrIWZRCMqNal0StqJGpoEwMaT5MB693GWk/OpNC44F/c0fCtfZmA+j81GMs7nfd5YWvzY48lhoVzkdGMmEVbOQHvDIrxsji6TrtjBZy1giF2lLQ2LisQde9Bns1+tqUwj/iqwh2Gv6zLXE39El/z5xq20bL9GGrlbZPZ5cOXzXt5/EVABAvceFgj1+wbBNCJGq/ViL1EFtcU0RZUyWCVMEhjFtb5+36V+2w5/uZadyVFJA838u0KFyAzPOhU4Dplwr4wVTcE/qHKLBcv80GmhuNtSDKSL13Dikb7gTgClKqw4LBh8rDZUxHWRwAL00Nd9noHocLOfb/bjjVbXL4NDDMhXkOSSV1SPT8Ur0guOMFOvkllheVDIxTDvNW78TKYmnW8/CLeKrT6tIexCt+RnPsLIbgq+BxXU0KIZh82S9J4qdLCRftKtFP3UhKb47EmI8zmspnujxrz2wicaHLtck+wzkYEV22KMPKeY8e98CFPcopZb2V5sYQ/DtwfYZVbo7A1KySfXOgZN0mi09mSfW9SUFtJqMdjF29r6ClHE6GurovB1sS7dS9e28YYyZWO+FmXcSWhmdzVZmouKs6eIUydjHIFuqC8F4QxOCl0UVa9b+uBngSwVypBznuFRwKzmDtwBEoJW7gVWpZqi3IFUTw1Z6JtBVavcHMOPeJSzi1nGCGBLE+OP9EVNYhWM0mqEioUs0e7ICYxpGHmc0NF13iBjQnYlVEtWigU1PVkN67Mj3AMCpG+GP1gg+GSB96WZyCqa9NrPMII/jAwHHiznoasNFAauGwXDxjjDQhVliURwU9RgtrmSzPsV5hKkiWqkpl7pV1xr2EpA3afHpgKodiQ0fKfi82qiNcDr+h5OlCKw==,iv:7NWT/gWhOpXVXctFS0N6iH5VYa8VhYsPikhjXh3GgyU=,tag:nW/hLwYJFF02N02ULZ6LNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNVdKb1U2VmVudklVKysy
            UTF5WHdLSjdGdmREZFFBTCt3dGFsWUJxS21zCi9NdUNncEthRWdtdFhOWWpsM2lm
            QVBmeU5Lc0hLZGtHS0FRV1FKalBUZVkKLS0tIG9EYVV2VHlzbkdKeGhSalFzckk5
            V3FnZ0Z1MlRYTEFVdGY3K1g3cTF1YWMKKdJ2srSZlsJvD2gwQlCJRU5sYM2cZZoA
            L5v0nfWtPYLmMguaHM7Y4zEoEXxdoh9WjX/BL2yl65vl6spmAkzfnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T00:13:31Z"
    mac: ENC[AES256_GCM,data:qJfAADxfo1MnNPSBNf42dfgLRPPUQ99CquPNuw4euPOk/GTyb2OCe+q3Y/n9ntXQ6Ac5fFvr6d2Jvm05XwQup2Zl3qnmNOFuMDb5cHyUOKeyDnjvdUtc+Ygm0tN/glKwIYWwWtD3N6OgbbP7iSntsYoYwCQVojT6jeCePsBoxSc=,iv:LZ4lxnpB70TIM9LYyuM9lZBb+2La4YXLleSJmRdbA+I=,tag:pb0p0xVhUw+pbXMGJW7FOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
