apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-secrets
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:cWm7MgiRfzhsoxmUyMux+fjFMbKPxYyXZBLeCV7XYngPG90nzCNUR2/8D4qbXppHzhAI6B/EmnCZTcTPomKmqL2QznnvH6CdaJQQW8hr2xLEqAerU2ozPoaDyn7Ma8vvjRbRR+/cPfm2t/283KPlXzf6mMjggXPhKFD8MUZaEhIdagsFYJaUUb5NNjWYDWm9GSaVcQXFsIwiSgSrzSrXK8WtRvBedB/lK9H8iVsoS7dcmMoBONd+HopZMeXWf/fdAftgGvUTkYfEemY+4l5QpMq258lkW/wK873h17dECK/jrKADkVQ+HvHGjgupnV1XNCYVpbWBKx5Az7jsPvls0DYXc5LSJ28PFp4bXyGqjnLjgh9DcID27tToLXU005xV6/BsWzyqiV9DtnQh+ME9Rv0e7NDYAgAEGoeDE8jF+v59FORRTbCT37pSfj3Rnf1Y2G5UXGz2d3ONFPn+fQ5kg/UOt8wZfkhrZtnHazo/mlnaHcFhpWVQ6Psl9YMzUG+D9Zho3BuhDrvrD+OpwiV+AFkrZOP3xB2yQR6RL3OR0SQtsqj1g2wk9HJ8XYAZWqvnwn6qB5CpoS8luZSLH07ChVdCv0dp7IIOY7pL/0CQ/T7nH8NN7Yjs46BsdS9Ry0YQHfe4vkSrFOpiDZ0l3BBic3nt3pErY6clpkL5rG+NXZi0p9A3HYbcN5vIlaaOuuFqRCulBlMkbWAmXF9k5GhGwXPeTG9lKzl8BT/j7eQ+TrdIUbZdXODUJEhLnC6D4HT7rbn8QQrCFOUBIUl0f7AiTlC7jnG4xzAAv0X+OrZE3q88syeJyJnrVukWBH0UISxXg/eQUkLe30aQ/ntlVntAgMBJuhlQkAG4gZHYmFleTfJSas5Jk68Kb9/A9fN4HRCauvSgVuNF8649bmtB9fy1oOc7gHuKEZLb1y4O8sXd+Br+Ev9GuUKVwTFpMnYUtx1zWseHaldweGnksLfdDHmRZRuqFVpUwqSo0+2ClY84Jo+6lOHOfmXpCdKnleNSp962qADVmSOdU2YCOrL5Csjp6G64gVbghD9P+X9Dwkxn+s7Mu9skPI9H5WhNW/ajy/wA6MbF8C6FF/ufKPohZH/XpdhCLHBz3m6ahPuD+aC8pTegmJlqRb41p2vIk5Uqnhh3LmV9LhB0OvPUzdQ4kvPwdGrQdYzLyLtBNO53DOEVP3anaP+cKpJdfmcHkyrph2tzfsVqp0hidueeJdn+TFhY9sT/SEre1/4BVUvOkoW27zck2GoqgSBIO2wvYgJvf1dUeH81hjZP/coUeWTYcv0OMyN5mrVgGq9MS5E/wpbn/XqkSQYSM9sowLowjmGDemAK5neUMd/W4nH2mR0ENRGv+g==,iv:Dnpe0a2ilKU5RfMKg00auzUGZoi7JmymXXgzLQkdQpE=,tag:dFdpQRAXHMx8H/t9JpIMNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVDd6M2M1NDhoVFQwbGRC
            VC9DMVJVanB6WThYOGFEejlTUkgyU3phZUhZCnNIN2xNYUhZU2gzWGFSVHFsQ1Yr
            RFZyRDJRYUVTSGhMRnNtZis4R1ZrOE0KLS0tIHdFbVBRQS85NWJCd0NSTWhrelI2
            YUdiZHRZTE54aWpZYTlJcFdZNHNJTlkKE2XoH691EMqjZzQtv3qf1FSYEUkLOvBu
            kPr8ErRrvdsY2wp7ANhZWD5vNKEABYCr9DpBqwOkj5Sm4PZ4+BcNAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T00:11:27Z"
    mac: ENC[AES256_GCM,data:q+g+1FbkD897dJZfMYiFqOc2S/bKQwPxOknI201cp26galdK0Z3UivnJfrjgppAbrju++tYtuu20S3pKuPD5aR7TGBtZG1wSTQwkFaYiW9HitQiUCybJI5P4A9M2K1OMW6Ad3FUHX2y2+kgSeBpCE931H9IwS65U5OHK6+eZ9Ok=,iv:yHul0OhSATNtooX72L2totLj8XGhD6KpFmYYQwEd3Cs=,tag:nIX5Ks6DSID5YjFmsZdPWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
