apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: threadfin
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: threadfin
      version: 1.1.x
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    env:
      # -- Set the container timezone
      TZ: Europe/Lisbon
    image:
      repository: fyb3roptik/threadfin # {"$imagepolicy": "flux-system:threadfin:name"}
      tag: 1.2.32 # {"$imagepolicy": "flux-system:threadfin:tag"}
      pullPolicy: IfNotPresent
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: "/home/threadfin/conf"
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
