apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: threadfin
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: threadfin
      version: 1.1.x
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    env:
      # -- Set the container timezone
      TZ: Europe/Lisbon

    image:
      repository: fyb3roptik/threadfin
      tag: latest
      pullPolicy: IfNotPresent

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer:   "letsencrypt-prod"
        ingressClassName: traefik
        hosts:
        - host: threadfin.nmoura.pt
          paths:
          - path: /
            pathType: Prefix
        tls: 
        - secretName: nmoura-pt-tls
          hosts:
          - threadfin.nmoura.pt
      
      integrations:
        enabled: true  # Add this line
        traefik:
          enabled: true
          fixedMiddlewares: []


    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: "/home/threadfin/conf"
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true