apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: threadfin
  namespace: flux-system
spec:
  image: fyb3roptik/threadfin
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: threadfin
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: threadfin
  filterTags:
    pattern: '^(?P<semver>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$semver'
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
---