apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: my-jellyseer
      version: 1.x
      sourceRef:
        kind: HelmRepository
        name: qjoly
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: latest
      # -- image pull policy
      pullPolicy: IfNotPresent

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: requests.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: 
        secretName: nmoura-pt-tls
        hosts:
          - requests.nmoura.pt
    
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /app/config
        nameOverride: app-config
        readOnly: false
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true