# kubernetes/prod/cloudflared/cloudflared/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eck-stack
  namespace: elastic-stack
spec:
  interval: 1m
  chart:
    spec:
      chart: eck-stack
      version: 0.12.x
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
  
    eck-elasticsearch:
      enabled: true
      fullnameOverride: elasticsearch

      #nodeSets:
      #- name: default
      #  count: 1
      #  config:
      #    node.store.allow_mmap: false
      
      ingress:
        enabled: false
        #annotations:
        #  cert-manager.io/cluster-issuer: letsencrypt-prod
        #  traefik.ingress.kubernetes.io/service.serverstransport: "insecure-transport"
        #pathType: Prefix
        #hosts:
        #- host: "elastic.nmoura.pt"
        #  path: "/"
        #tls:
        #  enabled: true
        #  secretName: nmoura-pt-tls
    
    eck-kibana:
      enabled: true
      fullnameOverride: kibana
      spec:
        elasticsearchRef:
          name: elasticsearch
        config:
          server:
            publicBaseUrl: "https://kibana.nmoura.pt"
          xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch-es-http.elastic-stack.svc:9200"]
          xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.elastic-stack.svc:8220"]
          xpack.fleet.packages:
          - name: system
            version: latest
          - name: elastic_agent
            version: latest
          - name: fleet_server
            version: latest
          - name: kubernetes
            version: latest
          xpack.fleet.agentPolicies:
          - name: Fleet Server on ECK policy
            id: eck-fleet-server
            namespace: default
            monitoring_enabled:
            - logs
            - metrics
            package_policies:
            - name: fleet_server-1
              id: fleet_server-1
              package:
                name: fleet_server
          - name: Elastic Agent on ECK policy
            id: eck-agent
            namespace: default
            monitoring_enabled:
            - logs
            - metrics
            unenroll_timeout: 900
            package_policies:
            - package:
                name: system
              name: system-1
            - package:
                name: kubernetes
              name: kubernetes-1

      ingress:
        enabled: false
        #annotations:
        #  cert-manager.io/cluster-issuer: letsencrypt-prod
        #  traefik.ingress.kubernetes.io/service.serverstransport: "insecure-transport"
        #pathType: Prefix
        #hosts:
        #- host: "kibana.nmoura.pt"
        #  path: "/"
        #tls: 
        #  enabled: true
        #  secretName: nmoura-pt-tls
    
    eck-agent:
      enabled: true
      spec:
        policyID: eck-agent
        kibanaRef:
          name: kibana
        elasticsearchRefs: [] 
        fleetServerRef:
          name: fleet-server
        mode: fleet
        daemonSet:
          podTemplate:
            spec:
              serviceAccountName: elastic-agent
              hostNetwork: true
              dnsPolicy: ClusterFirstWithHostNet
              automountServiceAccountToken: true
              securityContext:
                runAsUser: 0

    eck-fleet-server:
      enabled: true
      fullnameOverride: "fleet-server"
      spec:
        policyID: eck-fleet-server
        kibanaRef:
          name: kibana
        elasticsearchRefs:
        - name: elasticsearch
        
    eck-beats:
      enabled: false
    eck-logstash:
      enabled: false
    eck-apm-server:
      enabled: false
    eck-enterprise-search:
      enabled: false
