apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vaultwarden
type: Opaque
stringData:
    #ENC[AES256_GCM,data:b7yTOleWT0KCxpngD86E4H5EwoN2zbru57dlY0AmzOHjZs3BuDYA74HjVfnC9dUQ9LBX5znBl73W8Wi+b3j5iCbXj1Ve8GkEIl/wj64PdKoudvb+WDGS3hSZcXBZcdHCKgGDVZHdeq3YinU=,iv:BmmIPOPHDVOxi74sCl8/9AD74Nbel85VFqJ0QLf13wk=,tag:DaCE/eAaUPjV+/4qqo2/7A==,type:comment]
    #ENC[AES256_GCM,data:nIml2ZjQhsczROLIq7j6Cea36ZLUwFdN4ZYp2rFfTcTu2jOT1fPLWdGg+w==,iv:kHUz9PZcah64yUf3wHW1EZz9niH+kvUPwO8ivppjc3Y=,tag:dGpjm5cAlftXFET3lC6gEw==,type:comment]
    ADMIN_TOKEN: ENC[AES256_GCM,data:ocnmNrDl27ieCPno1wlM6sqwPYbrqg1IG+24hqYPzpBOWjd+xtnEUa6jiBYhDOx/arAis9mtZ2eRjRhhZHwYwKbrAmk8td7OL03WBwv8w/fwE5KRyzBGfL+Bn6KKbrUr9eFWh7hWjh4/xmku1rWybibuc14yspTlLdnbtXvFeH/0asiQ/JHKEKZRWA==,iv:rPRTP2/hrkd0VWChwWj1weEXJaGhFbdj6Ywg/BB1UDo=,tag:+Rca8DyDGdtNU8B/2QOC0A==,type:str]
    INSTALLATION_ID: ENC[AES256_GCM,data:EuG+DQTNQNJWhZqOfICVOPmKAE1Y8DIPTXq+BOze6FfCOQ5O,iv:DxpiYjsHei/A//9oV4un1+yq9dWjp9peEtLOtEv9mSc=,tag:flNHJodm58gVEKwUjIujRg==,type:str]
    INSTALLATION_KEY: ENC[AES256_GCM,data:OLwLjg4JsIT6aA0CyiMg/PIB0PY=,iv:BT573cXQgl35SK+oq3Qlpi3uBmGVPB3EXWX//KbaQt8=,tag:kaUHTKl4yPVkKgvlEWUNpA==,type:str]
    YUBICO_SECRET_KEY: ENC[AES256_GCM,data:nCakh5dNNVQ9dG/yaWX9cZH+KktWg3xS9/mARQ==,iv:nm7AtJfNm/Yx829h3sZUNm44QrSP+qDOARD+VNuiZjg=,tag:ShYhyf5nQ1B9JE+o9w0M1A==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:twcNz3UaVCiNbHt/5DoXdBk=,iv:Fd+czic+cRtDDnvkFtouaeKW2UuDhTWx2/609VesPnI=,tag:5sWEVybgugngjv4igEn8cA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:8GY8+iA85kHhQrun,iv:b4uYygAZWC1DFQnBBC79jGMxyCfMtj2oDQXo4s3PCt8=,tag:119dnq5cz88rMPSvenAKmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWnhBejEvSUxZU3J0THlh
            emZGOWdFK2xvWTMzNG9UdlJ2K21na0o4aWo4Ck9UUVRaZnh6bXVjaUFENkhKQ05U
            WmxwZ3k4SlRvek1YS1pjaVpFNFpHckEKLS0tIHBNMm1yclQ5RjFBR3hadzlLbVZ1
            N3dXazhkdnIwdmZxcFVIaVNLTHdDakUKdb7XAP1890UC86fumrlYiL3fSMMH7LKB
            VEKLC4n8Njl9BTCAJ80KnffVVmdbH84SFBu5lQJn1IqgMnCz9dBbiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-07T10:14:13Z"
    mac: ENC[AES256_GCM,data:FdhELOSaGwV54j/2jT54SAd3CNtuTwQlf1YUxjQqPAV2uKZWJNOfMjGlFv3Gz6jwBH7LmNRdnjpxDQ/arA35fFJ4BDnW+2HcNukG9HkkRauVf/6SLqIS0og62BLC6sAXeJFsc9rICM78PEM+Hobi7mq7RbQV8anWQFhq89gIuW4=,iv:d8+5UY4E3+yQ0T4CNmHZto3M0t24vMdocWkOJ62NbaI=,tag:1zLIKJWO6Ev2L+BYBRBBpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
