apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vaultwarden
type: Opaque
stringData:
    #ENC[AES256_GCM,data:nJA4z1igvTgvzfsohGmcgL5CEWETp+wSsNMhnbnP1mmu+7ck+XbaqwxbelKEGUdnaKf4K+t8MtuTz+3R1b6qm6dx7qeKiZZy7dCUJRR7SrKwi/Njiw0n8pf3,iv:TIC0bs+Hhjb7gfU3jpW79XtQvtcPx9e18Z3VxYbFBO8=,tag:gW55IZoXPRf1X8r3YcNj/w==,type:comment]
    #ENC[AES256_GCM,data:kAIeE5LGmUp+LJsDfDbqhNg3ZgMokJhYOWLSCKOrWp8478fH1ujoUGSMnw==,iv:ZaYTUlSmQIrRkAyeCFQxcfZ0Y1l/cVgnRFQR1DMhjIM=,tag:ByoIQ8keq8TrnPUad+0Spw==,type:comment]
    ADMIN_TOKEN: ENC[AES256_GCM,data:S8VqIHom4qwBRXw9oEB+5G+EoMpJdjSWgULk8LIJB0/9S0vCWpmN3XmhCTnGE864XAxQk+RY+DCSQDvHdzRG75D1lvA67UKAH6MH3yZwzjmXos2oBXDbtPZv14dhu++TzilIY1v1w6LU7ZSW4l6pzDmpzG8Gb8NNFVI38rt9CE7aBq+ycIY=,iv:xxl70meIit5tPzm4so9NKZyeOD8Y/X1CvjQI2VQ4oHQ=,tag:RJsk6kHRBPZiTSBhCwZFUw==,type:str]
    INSTALLATION_ID: ENC[AES256_GCM,data:dzqzegFea1RfbiJbTCfWpl7E9HSpN5nnuJ0UWu3/KSm+jOCq,iv:zqppJFCRfN0kEMioqPBYpnim8XP/3UhoXypxSdeGAwo=,tag:4HUmuBsNB8pIDQQPa9NFqg==,type:str]
    INSTALLATION_KEY: ENC[AES256_GCM,data:yVv+rbYVhspbXsTjYxSW4nOQqkw=,iv:OPdM9amqZlrkW/ChuI+R4WGHZeLJ7mXmaajJOEfYSkE=,tag:Ac4aMz/UUwsbEwm6Uy+vrg==,type:str]
    YUBICO_SECRET_KEY: ENC[AES256_GCM,data:U0UaE+DLtYlBmgc34OjK1NCvjPIFQB1tVvyw2w==,iv:3IYIgRCDLy/EzHS3zZJraELpngeGvIfS4Kiudro1uG0=,tag:AY4rI2euanV2w10zK9BY7Q==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:6OsZRh/HTAsuCNh2lRKJ3HE=,iv:k7EmGuUKJxGgK+Q/KAkacSS2HAOgNsQk5Gh6Eb+1Y/M=,tag:aph0yaIdq4PBIOLQOOSFuw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:F5g7+4WE2bHG3M+G,iv:bCTi9ZUcT18RXVqPUt1Gx9po8YHmd7tz1iT9UMYJsD0=,tag:WnP1+kvCRqRznUNNaeL3GA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNG94VGRYNldLS1R2K1do
            R3Zqb0s5VFhoeGhqRk1yS2ZoeExBK2Nldmg4CjNDZXJNdGt2TldiWmVOVmp2dHdP
            cFF6Yms4Wml6dXltaFh6YXpJSzVObXcKLS0tIGRId1A1RGVpQXdWamJpVkpGUW9l
            VXpOQXZnaktYS1ZieUFuRHJGRXI3Um8KufpawxNLKpqKJPYz6QsHrQuz/pgCegJ4
            7Zx8OJZgz+NDkG2Z8w6y7xWYpJH3ANkVSUS+DlIkU5w4laVy7GK5zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-07T10:20:13Z"
    mac: ENC[AES256_GCM,data:J7/AvGr1wF/Sv40YlJP/gSqj6GMpNeLySKU48txfunjAVAm+1tLTOhd08g6YWZx1ml75p7qcEetFV37SQgNjMqrkc0C+9Ynjig8+zo7MMlkHGgW11MtRxGsa4r49J0mINB5Kt+TiMKLWD4VrHnLWV9dXfi5SK9nR9mizl+XncZk=,iv:z5JzhpvHpiNJx/9ydmqbyRCsmUf0PLOx1bLnWH9I7z4=,tag:Q6A6SOvi3Uba8f1MXX4/PA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
