apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vaultwarden
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:jZ0zz0Gm+1ijV3r4bNZG7k0zzeEjDH224MOZjLDb12I9rBT/33HD4A==,iv:n9YoMoe7sro0eSzoKcaptzYOXFEeTc9zaXNMu69Xwcs=,tag:QhgG6niZ7qmVr4jYNxhM9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSHZBMyt0ditucktCSEM0
            L0xPV2VmRzZMbnl1SDdnK1g4SHpLR0ZTU0VNCnMxK3FkSlZoMzJyZEhkS0VXVjZI
            UG10UTd4VmlrVXhxc2hYR1hFanZ1YjQKLS0tIEJNRHVzQ3VCaWkyanJSTkVvbnp0
            dGh1b2JrNUlHWkhLVjU0UE82YzFUS0UK9fcSxgKGkX2kxv1vw3GSHpAPzVNx1YFr
            95bnkerj3pqiwAInyJPsRpT+HW7jSDGu90eZQLwgparUa1miEFBPlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-06T15:57:03Z"
    mac: ENC[AES256_GCM,data:j+ZzxSnq+h/aZJU/uio7RiizhErnloMuqp17QzSJpwMWlc0KdRyZjdumaPjmgcCmpt8OA/TA5D2481eAhOtRR+4zF7WjR7padOI6ojX+JgTGO/FWtSLNh0qODY9O3DqYIf1i0CB+7L+m+BX9ruwA7MJ/fNVugFwm2jE63d+IKe0=,iv:ikhiJmxNVsAglnBaYSOrn3jcDouMcuDKBJ69AXPCmWQ=,tag:OkIMsFJ6GwhgPovIWznG3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
