apiVersion: ENC[AES256_GCM,data:/w4=,iv:9S0rNzrs46DRUMtxvelMm8xRlkiHhIkXSgURCj9zmUc=,tag:6hnA1N6TlO1CL0Grr/y2Jg==,type:str]
kind: ENC[AES256_GCM,data:roL770yy,iv:m5Pvsmm2par2kzQ2YZOtPTwcdumdTDJGzJvnq0azvPI=,tag:9eXMYjqHFRAahWZFPzkulw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:p0WRRIH4jd21yQHrETM=,iv:gEVDd8MAcyoiEGKXqnCWmsqtjQBkbV8qcZMX/5F9PTM=,tag:fJjVe0wpCwyl6OlMtCJqGA==,type:str]
    namespace: ENC[AES256_GCM,data:el4Vlkg=,iv:NEcpm6X334gDTwrn4cHGwpoXDmCQQReJG+MomdkSWNE=,tag:Bm6CePEVbtDQrk+J9J+ouw==,type:str]
type: ENC[AES256_GCM,data:0f3CX23B,iv:hIEL8Z21D4w/Eexe4GiDyvzXBtPkeKMPvHOWi9ziqeI=,tag:qYcbgmq613Sew8o73HTXKw==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:k5SytjManqi1ElwdmhiweHAA00I2VlVZR/qt7qKb2JSjsDGR4mSfJHqVvs/zSPlJJpwaz8MhaCVEtE0op5aIVyrBBAr7zxItgcXsJpo/jUXXr23FupqCBSc0+Y6+nkM=,iv:D458+Ao3Q9/2hRwFO7p9tjV/OE4LG9mLkJGPGWZapZ4=,tag:OT9vtzpEG6vN46y4UeBxpw==,type:str]
sops:
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQmliNDRHRnpUK1R2M1By
            WDdQR3NmTlBxVlJSenJCRXoyeWRTb2lpbW5BCk10ZFRZZjVHMnVxaU8wYmtRQ0Nj
            QW10ZG1NRHMzTDl6OXdRLzRoQ29FOFkKLS0tIDcwQ1ZlTGJiYTNHQ3dmMDAvVm1s
            OHlZYzZoRHA5emU1c1JHMXFOMGVSMVEKUfWu+kHx5v86NZOCSiCPZ0xvloSNXote
            KtmA/iLbtoHN/UejUhgTJ0ug/EwUhigXsOOjG06FJlnczJhF5Cl6/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-20T16:34:51Z"
    mac: ENC[AES256_GCM,data:839JdlOM4sxf5HiY77puDByN/LGDLBChyPwKicPiMwprapqzZmobkJCbldEVst386DcNQPXYovawRYLvDTFtPN0L77/XVUg2Z+mr/F0O1rELbmtlL5fiGHNXAHMOmv9grSCyj5uLEyvSCiafrREEl3QLDrUvQggm2gMDOYH+i8M=,iv:HS2qzpzNIy3n0w3m5NzHccmMS69UucqnbZ+B6/q6KPk=,tag:cCvKPdNKg+0mQuq64RuAtA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
