apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbitmanage
  namespace: media
  labels:
    app: qbitmanage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbit_manage
  template:
    metadata:
      labels:
        app: qbit_manage
    spec:
      initContainers:
      - name: copy-config
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - cp /load/config.yml /config/config.yml;
        volumeMounts:
        - mountPath: /load
          name: config-yml
        - mountPath: /config
          name: qbitmanage-config
      containers:
      - image: ghcr.io/stuffanthings/qbit_manage:v4.6.0 # {"$imagepolicy": "flux-system:qbitmanage"}
        name: qbitmanage
        volumeMounts:
        - mountPath: /data
          name: qbitmanage-synology
        - mountPath: /config
          name: qbitmanage-config
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      restartPolicy: Always
      volumes:
      - name: qbitmanage-synology
        persistentVolumeClaim:
          claimName: pvc-qbitmanage-synology
      - name: qbitmanage-config
        persistentVolumeClaim:
          claimName: pvc-qbitmanage-config
      - name: config-yml
        configMap:
          name: qbitmanage-config
