---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbitmanage
  namespace: media
  labels:
    app: qbitmanage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbit_manage
  template:
    metadata:
      labels:
        app: qbit_manage
    spec:
      containers:
      - image: ghcr.io/stuffanthings/qbit_manage:latest
        name: qbitmanage
        volumeMounts:
        - mountPath: /synology
          name: qbitmanage-synology
        - mountPath: /downloads
          name: qbitmanage-downloads
        - mountPath: /config
          name: qbitmanage-config
        - mountPath: /config/config.yml
          subPath: config.yml
          name: config-yml
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata 
      restartPolicy: Always
      volumes:
      - name: qbitmanage-synology
        persistentVolumeClaim:
          claimName: pvc-qbitmanage-synology
      - name: qbitmanage-downloads
        persistentVolumeClaim:
          claimName: qbittorrent-downloads
      - name: qbitmanage-config
        persistentVolumeClaim:
          claimName: pvc-pvc-qbitmanage-config
      - name: config-yml
        configMap:
          name: qbitmanage-config
