apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-test-secrets
    namespace: cloudflared
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Std3OB0vd0ik5OHYJQAzcPaHkmhECblAZR+hPiD6yLohMemxXVKYnAF9j7Sq9+Pb2R2cvnevhjJSr2env1X/jzLCXSjKWL3/EAbdErvZHwr4yjDuWmf3kC8E0ni15yji3JkXl4SaJj5JiDAoP9UMuoNExFfzncXRgLbRwsbVgQxVJl8OQ1NV1Le3CBPRolZ6aBrDg6cl762xvegFFlFhr5JsDpfdnYVe7gn2YDOMdHSYmp12MqHzZ0ngKUPhW2o3P1QJK/mxHm7j7F5iZdi12SbB69GA,iv:+PLDBfrTWBWe4/gH4shw3E5WDCSZrLQfJNZywK+XJIY=,tag:XDmn+FF7fzrRa/9hWYaUbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZekRYQlczMXAwZTVxMFp5
            VkFGSGREcnZFcUpaSHQyZkRWdnZwYUs2d3dvCnV1eTA1c25PMWV1Q3hScDdhald0
            djJ0RDNabEtIUGlRYVRSWk9pTTUzUEkKLS0tIFhJSU9YM1R3UWtFWTNUYTdaQVlD
            ZnQ5Y3VZVGpSTTl5WklDdEU5NmNXZkkKeJUsuvZ8y21yW/vJFJE2TPPc8cNK+iHr
            SYJq16mMiOcbqBkSgqex7LoqI5jRVO0zgfWVMtiKYMt7BsiFYLm2eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-29T09:21:37Z"
    mac: ENC[AES256_GCM,data:COBFgzGNA6QF96+tdiI1bgAYrif4Sk9C1HX4lMVRVnp49xLj4MGzEsNmbDpqaarjXGVoYWEG6ySTGYktBlBbj4cXswiA3IjaMdO2mP4LDYa8IdV3Md17qBHqae3yGH4pRAx/krEkoTrYOjxDV9C1aI8goNl0wejFWHiipTuTBtM=,iv:UbCV4a5s1/1LQ0M3urmEtJ6ilzXSSXsg9SPadVMBItg=,tag:dv9PIcmb1SzZDIMHlfUrtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
