apiVersion: ENC[AES256_GCM,data:rcE=,iv:IZ0GkmmzpMhW3SVfYmGwjUZEaDCL+x/4KQI3hPmCFBM=,tag:Ddc0zxYJQim7SomSIhGoFw==,type:str]
kind: ENC[AES256_GCM,data:a1sNTR1s,iv:9K1i3oflTORuXIYAWwfdLJ3+qIKLXl+aSNc50+Ev92U=,tag:+HcEvgYvHcaS0HGEs5PiMA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1V9/kRwNaNQNR3umJ5c=,iv:6KQp17sAE4hREv/hOcTjU8nu1x/SzpHtA5PVnfeKdrI=,tag:ZfhLf+4kv7e1dQAmYLC5lA==,type:str]
    namespace: ENC[AES256_GCM,data:RhFTWas=,iv:KVvgtVlCeetNXkOnzOxG1ODUXEKYRwZDq3H7NJMqWT0=,tag:wyTqko0LWalmJeBJ3WDyvw==,type:str]
type: ENC[AES256_GCM,data:nZffKcMM,iv:kxRh2ljT09PvJL9mxdzdnOG6uzFqdWQGBEt9HZ/dzbc=,tag:mPpwM/mcYwgnmegmZelPww==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:3Ij5LNDrO/go6dAqXu2YoQiR1hbuHU4XBsZ2aUGGPy9nBySVtKGgAf8oNsjvLjR1BJoxrnKgH9GXJWoS59AMT55OSGPReV719BhpjBp5ZBf7Fvw5OLPsYIWQa1QpIyTTZsuKCqn0WxFCek6o9oWDedKZyIVq73ShE0OfpnsPDqfgWns8pERN9EjJKlGv+tGK4ILCL7G+lkERi1lNoE94L+y1kV1d+gyk,iv:jNO3PIyAX2AOrFiL+VkswYke6cdhlVzbZcfxl1jcs8A=,tag:l6jmXGpXnqOdRNH61bbqMw==,type:str]
sops:
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXa2JxNE5XY1hEaVo2d0Fv
            YmxmNXFKTUdRRWg1NDNaOXhZUFpVaDBHakVFCjBtSE5FL3ZRdGNwK09kaWhMaS80
            UUhXR21iZ3k3SURUR3hOdlZEbFhWNFUKLS0tICtGVDNTYmt0TFp4R1RRMkkybUtp
            Y0h4dm1BaGtaSC9yZmFmME5xU2VuNDQKnf+j6qp8QzqKkEYIZX2OWx3nHTiNBFhQ
            La9D4FxKKG5TG9BoUvT3kSsRQt8q8fPaITGQI6hnTNRK9HfvdKdd3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T13:11:18Z"
    mac: ENC[AES256_GCM,data:q0Zc52RiH5wnHrj6gUkwJQqnT9aaFjLI6G9cUMJIprgpHUbYZq/Gg5W77fSmxeU+HIG+53+FcRI3U36ivs3fYMFdF+wizYlIVd1UVP1zR3bYM6k0YHwNoVK+KP45SkOfxYbfkmbwU1i9MoavitNj0hZnCdwjoOQIluHkqe3IMXM=,iv:bi5AGXbUBdFCy7S8Vs39EbtJIbJyjFQ5Wog/aik1Uqw=,tag:jOzNAOgh+0842ZeA9sDBTA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
