apiVersion: ENC[AES256_GCM,data:H0I=,iv:y9+CX+GW3sED77lgpQrnbftDPfgMPfAv10cMdGB6yK8=,tag:kbxdHLV8MmwZbHiUcSXa8Q==,type:str]
kind: ENC[AES256_GCM,data:lj5M0pGY,iv:kQLwkHlQZCCU9/LYBi1LrlYN5SDSrR54TBUkvlB0xMQ=,tag:6WXG6+ilZrJqFNBG5L8a4w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yvJBgek8Wl2PXk9hz8A=,iv:4WCDcA78VtkJ60BRLoOctRdpVOUQdUIHsMQmpV60LC4=,tag:L3QCoFja8MdE35+F9H+C9A==,type:str]
    namespace: ENC[AES256_GCM,data:Y8r6cQk=,iv:hrjDh9s+nXq8FEoRiaY/lD34+1Qbec07IXbBbE4Jr/k=,tag:ymIyyZ274tbe27UkEFQzUg==,type:str]
type: ENC[AES256_GCM,data:NGHDQZxi,iv:Dr/JOzr3YCg8ye2HZMW3YMfr07DWdu2FlqqsyTuOiAk=,tag:jjf4YnYJiiTmWZNU5UxCPQ==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:zna5urIUufpB73dU9ONx2Y0mdlcqGjcbBHmeoYN650zKUlt97ex82v5p+Wm01vtHY8i0+Y1jxNOQT7HS/HvPytDJA0tL/Wa/SIpXCKvG6YxQEHOa1qhzi06XAIkGr2S8/NOQCuB2EQF49Gl+cw2j6JLi/BnWtPs6ocamMhRkc4Yghuxb4UZilhsVE9bogwk8NM5uXSSo7vuQn3iqAv4S+8FityQNtHj7,iv:mXsFIueM7B2m+1J09Mppr2o2YfBiKbcQ/WRTkRrBKlI=,tag:oof6TN/lHAJAkxf/0sm6/A==,type:str]
sops:
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK01WVUkybHJZRWNiQ3lB
            MHU3a2lkczJscEFtVTU1ZStPWTN2WVpxVmlVCjl3aXFFR2ZrMjFqME1Vc3FSdGlV
            T2dDdWdTSUtPVWZHT28wdGdkbVlSYU0KLS0tIHpOVSs5clZid1NGZHI0RDd5ZDlv
            R0lPUTUxdm5wOXYrZ0xVbUhtR0RkUXcKzPeed1PzBf7KEUu4P8Xw9I5ZEW/wnhrD
            Ejye+PBlhFayhUFX02upK2iToejmkrg+GkIBnmrSxALQl4jfzjFgVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T13:15:52Z"
    mac: ENC[AES256_GCM,data:RQr3sEsO8qMWcLNdB0qqu+5b0E9SFBxGoF2VAfYpsK0OJBuDUhz2dgSt4mFo8uJXeKG+P4lumskXqq/1gzhFOT+e/zRwyejkXZ2FoNGwkHvEfg7aQts8DSdEwW/wsQuqeCXbCDpVxQLwWyRc0DwMgTVsR0fW/XCnnnLouMin86A=,iv:UcUkWmh+N0LkbkKczW01g9lWaKZ+nIJOD4kP8gKXsY8=,tag:qhrJEim9JuaN+cxorJ1Ydw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
