apiVersion: ENC[AES256_GCM,data:nLc=,iv:I5d9y3XgO7M+3GOfijTrxVHgiw/+G/dYV3dfl09ZuoU=,tag:mrPmNtiUc/ORXGTwfE6GCg==,type:str]
kind: ENC[AES256_GCM,data:TQDNvNQT,iv:AZ45+2sVYN67FCYSI6LktoMidgmTlT4bdNquO7eGNOE=,tag:T7IvtPJqRmC4Qm333l5vWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:es/+abWEdG5rWV9RWNc=,iv:AUrjbJ+7kWMxMLkXZlUKvX5YJH0y/CUVdVyDtInJbv0=,tag:bAibv/z9WUC8boWpVnm9Aw==,type:str]
    namespace: ENC[AES256_GCM,data:JpDyXoA=,iv:gfKddXAo4BmccbZepNer9LTmGm/V6V8CrWZHmLlOihU=,tag:+iSNJO2NVnHOCWfd179Dow==,type:str]
type: ENC[AES256_GCM,data:REmzib0H,iv:9SPl7g0h3Z7oKdwMhuqYsNAtfMgyh1ZnzBu7cfXTPf8=,tag:s0rlQ5eM10iCYG2kbbbZug==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:nppdzJ2eIdbCDbVN/RemvKOEYClAGnjKJPuzUBqsqMBnUZDI+aD18yfYYetYUnuvbDZ5zNC18M68fbCA6+MFfdDpSi1CCDu0xWHiqVDZyx41AqHkJDRTZzcaMbeVnI9c+c870mtBahrguyp5Bm+6t54M6fEQ4w2DY7Xq/DtIJbQlbwPQcylDtePsTVN6l2dCFHzsIDRxv+yfYME9zdsbAvYoMuWEENb1,iv:gReJRNk23l+1sBi8Mss5hVLxCQZQCZy/Ix5C+6rRKuM=,tag:8LEvEr/IowSRi9C9sxacIg==,type:str]
sops:
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUWJ0UUQwcjNJc3lEWnhH
            UFhoWEFZbkFWWkxBWHAvaG1mK3pCSlh1MmhzCnR2enZ4QU1xd09LOHFJeXBBRDdB
            UzNPVCt1NTBKMHRXUmg5Q2d6bW43RTAKLS0tIFY2M0IwVmdnSnA5Wms2a0I2T2Zt
            dVpoYnhFbzdmQ3RpYlo4UGZHSnlmMUkKzM/0NC1E2jWnZQXKUyuXQzVsHDD01Unh
            PCCfORdt6/mgeEUuEPHFtLSnhOTvwqCTRDpXXBVigxJqAvsyN8A7AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T12:11:26Z"
    mac: ENC[AES256_GCM,data:bH0DwrxImEEGjB/kBt0KUUivY93ZHS75FoKRjv4uhjk7AA3+Q2+sy+VVWa7Oe7GqY01q4alJcFos8aj69I3A2fk07uAls3vdMIwSmcscIcDEcRToa9P7H03z0K4PtEtPmf36PSI+ivL3x9JASYY0OpuOzlkN3Pi+n+3e/wXL1mk=,iv:sIW42zHgRBtIa9uLBdrxK8vX26LM7ozm4iKme/hWvLc=,tag:3khL1QZIB0/ijbOOOBMXuQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
