apiVersion: v1
data:
    client-info.yml: ENC[AES256_GCM,data:Alha6AKawB+y0KuS0tVRS+zKWRywNp9xiF4rLzg8h2VMSTOZ960LEgU5TyeC04kOMn7QlemwORtFpnXXkBFpqQx5LtAkGzDTwmiOOiydM/z/IBYEAXZbCqy9dMNeWE/t4X1c0Eti9kfcpq2MbuAi91sh2G4fuz+7lkpuY3ZZ5FcCI+xn5aaEflTxWAZuuo3Vzx4nRUq+wqnf2OLi8rhMQtm/Zy5KoZfTcPEF+/XvWtPDeR9yCSeL/RqmqCMpV5ffbhxfZs1z9fRpnMk1USbeAUkrd8aKNYzfwY3KCoI7+GkK5nhsUdZrLiPVu9SS184yV4VxKqWth093Vjd18GGO81gnUvLHpFQQY2wwv45RtJpJ0ydaJfzZL3usOIchPyvQ9SuOsVb/EdchdnS8h/anJwfvLAhMoWSPTHwUh1SJgTTGX5Cz40edEX4nshBsRsZcHMG+9FbCVknI3Yzz1H2oVpCVeGjwhqiuGsOGuJeO1l5VjCiBgnhWFaIEp1kQG14QxZ2yr65xI+LwfFktzbCzFoyEWPR5XhFkPxc+p9foY8ck4lSQiHYSKWB2kQAS56DE,iv:RiG4sa/dAfmrEPge+XHkK2/CmWQjJODv8MNXs3mz6iM=,tag:KYrpMe37td/1AUNA44lM1Q==,type:str]
kind: Secret
metadata:
    name: client-info-secret
    namespace: synology
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcXNIWDdLY080YUJwdGFM
            QVlhenV0UUJCMi8xOTE0djh1bjl6TVFRRG5zCkxxOG9yMHhXd0dHdTJMMzkvTWhI
            L3pRamZ6NlpYWmx5RHB0ck9LQlVtK2sKLS0tIEQ4UlFkMlZDUEJaYWFXNTExWTBw
            MlA5cWJXTnlOTVBra2FGWUZhLzVSVkEKgn+KnIkKuoHKwQeX/ksZDFV8MvoFvUv8
            AjW/Jdy67RwDMkRmSuO2Ly2HFTUPsixT0puT1vCPeGhgEli+5s1baQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-05T22:48:46Z"
    mac: ENC[AES256_GCM,data:k4k6nAV5CE+bC1YottCQDRJyngdp2ZdEnR4pobfRLirLU7RBQJoquwBcXaN4k5H6zohc3ZYj2EkqalWUj8b60tVfsSZ4T+Skw2a2hjvnr7s7kEUa8F7t9aMq+P/b4Xrn3HarOpgR5dC4uJEh1RfgrmHKv9JXb6m5kcRK3SjAW7U=,iv:HWGq0Mr8QL3phdchugw0H8O5Vys1ES6ptyO9OG4838c=,tag:a356ci/ptCMSUfl77/zBcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
