apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: postgres
  namespace: flux-system
spec:
  image: postgres
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: postgres-rxresume
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: postgres
  filterTags:
    pattern: '^16-alpine(?P<alpinever>[0-9]+\.[0-9]+)$'
    extract: '$alpinever'
  policy:
    semver:
      range: '>=3.0.0 <4.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: minio
  namespace: flux-system
spec:
  image: minio/minio
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: minio-rxresume
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: minio
  filterTags:
    pattern: '^RELEASE\.(?P<ts>[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2}-[0-9]{2}Z)$'
    extract: '$ts'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: chromium
  namespace: flux-system
spec:
  image: ghcr.io/browserless/chromium
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: chromium-rxresume
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: chromium
  filterTags:
    pattern: '^v(?P<semver>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$semver'
  policy:
    semver:
      range: '>=2.0.0 <3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: rxresume
  namespace: flux-system
spec:
  image: amruthpillai/reactive-resume
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: rxresume
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: rxresume
  filterTags:
    pattern: '^v(?P<semver>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$semver'
  policy:
    semver:
      range: '>=4.0.0 <5.0.0'
---