# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: reactiveresume
type: Opaque
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KsWfsQyzWF6BnpmpmxNyyE8FQmGxZ94=,iv:mjp2ks92Zx3RKQgNlHyAo6eZJhjNtx9dEq1p5fLoFKA=,tag:Zwhf9MqIJJtut2Bh+QC+Sg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:kzbiPjN0Jl96JdGneEhSCl840OspoQ==,iv:ddADQszrcTlTG6hrq8lZ9RpK/0EPfn68ZunhvtDiZmc=,tag:6GKkzWhtctSiGb10fNLBjA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:l78r3vatLDsM5MBzaZNLi0fCkSUNzvk=,iv:mBp0ItlOvYpXOllB92lt3ttfRVsGnUgyKouGhT86dak=,tag:TWJnr0S6/rLJBEudQ20QOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYnhqbzhUWFVGem4xVHMw
            d0crZ2FnZUNobGVOZHkvbHFjS2p4VjVSQURjCmU4MmFOc3BRdE1XNVpZdkF3VDRN
            TDhwSDU0UHdhMUNYajkySlVzemVnOEkKLS0tIFEyTDJXcHZNNUg4L0NwMnFZMnFW
            dzZtSzVxbzZ1WGwrazNFY0liN24zRWcKj0ruC6P5Sli6c57xpspe6KGXmhCmyakc
            g72BT/4zRA4H7048wtwHzeJFpD77sFG1q9atyUbNKGhY74e9wtDukw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:16:45Z"
    mac: ENC[AES256_GCM,data:v6hw05gtoxy2FuyVntv5TIeVbpzV9ZKz+sa4ulbA0Ud3Xx9n1AO7Q1nSTu2KdicrAvmE2aTn9lkLnaTUgp++HhA23jhOEPVffHcnfkAtzpgMnmTu3qWWMlmDEM/YBo9X9bY7szxZI1XBbrn8FbSqNaYY2IwFAg8nGEksnwLGUUg=,iv:UnMomHk7AAfNIs636VQeu3/D9nYY9cGLqRkFF1qL51c=,tag:Y3JOnR22WUUTVuQ0tekLxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# App Secrets
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: reactiveresume
type: Opaque
data:
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:MjYbrgrKaxYZqfewA3Tv4tHv7W1WVJU=,iv:w6Kk5YiUGjFDUeFZRv4WpIWpDGBvM4aFbV3Ytr+bz7k=,tag:dPlqfyFuoxEtXg41hqZong==,type:str]
    REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:N7cOhT+WAqY4wvsv7295p6w2FrmWoMc=,iv:GwM5aTxBbzTRl1Jb/zeBhhPkK7S/iB9ujnZ4LWIKfV0=,tag:2iOD2ogNyZEAhhiyAj5oxw==,type:str]
    CHROME_TOKEN: ENC[AES256_GCM,data:+RsSZSjN5PZ9xmTJowLlJqmKDg==,iv:gHJZKX02ZEc1oqZgR71vbU2dF/yhSm/2O/ws1oI6/xs=,tag:2S7TmtIhbvsicSV4jBkifQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYnhqbzhUWFVGem4xVHMw
            d0crZ2FnZUNobGVOZHkvbHFjS2p4VjVSQURjCmU4MmFOc3BRdE1XNVpZdkF3VDRN
            TDhwSDU0UHdhMUNYajkySlVzemVnOEkKLS0tIFEyTDJXcHZNNUg4L0NwMnFZMnFW
            dzZtSzVxbzZ1WGwrazNFY0liN24zRWcKj0ruC6P5Sli6c57xpspe6KGXmhCmyakc
            g72BT/4zRA4H7048wtwHzeJFpD77sFG1q9atyUbNKGhY74e9wtDukw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:16:45Z"
    mac: ENC[AES256_GCM,data:v6hw05gtoxy2FuyVntv5TIeVbpzV9ZKz+sa4ulbA0Ud3Xx9n1AO7Q1nSTu2KdicrAvmE2aTn9lkLnaTUgp++HhA23jhOEPVffHcnfkAtzpgMnmTu3qWWMlmDEM/YBo9X9bY7szxZI1XBbrn8FbSqNaYY2IwFAg8nGEksnwLGUUg=,iv:UnMomHk7AAfNIs636VQeu3/D9nYY9cGLqRkFF1qL51c=,tag:Y3JOnR22WUUTVuQ0tekLxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# minio Secret
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: reactiveresume
type: Opaque
data:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:IUQ/+7n9nwKliQybDanpTmE=,iv:RS98HGTrFX42L+7bsdpTOGeTNSXSgfrVHeQZZnJHl84=,tag:rGy9tOHZgtIKRnjz0Sf+hA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:4x5xdMGkcNAZucVFtavEBPe7Hg==,iv:xW0qrx2jghDuR7MozCRGW6KDBbBuIf3mJKHOag6DuDI=,tag:ocwkMjORh05iSeNxiI0new==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYnhqbzhUWFVGem4xVHMw
            d0crZ2FnZUNobGVOZHkvbHFjS2p4VjVSQURjCmU4MmFOc3BRdE1XNVpZdkF3VDRN
            TDhwSDU0UHdhMUNYajkySlVzemVnOEkKLS0tIFEyTDJXcHZNNUg4L0NwMnFZMnFW
            dzZtSzVxbzZ1WGwrazNFY0liN24zRWcKj0ruC6P5Sli6c57xpspe6KGXmhCmyakc
            g72BT/4zRA4H7048wtwHzeJFpD77sFG1q9atyUbNKGhY74e9wtDukw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:16:45Z"
    mac: ENC[AES256_GCM,data:v6hw05gtoxy2FuyVntv5TIeVbpzV9ZKz+sa4ulbA0Ud3Xx9n1AO7Q1nSTu2KdicrAvmE2aTn9lkLnaTUgp++HhA23jhOEPVffHcnfkAtzpgMnmTu3qWWMlmDEM/YBo9X9bY7szxZI1XBbrn8FbSqNaYY2IwFAg8nGEksnwLGUUg=,iv:UnMomHk7AAfNIs636VQeu3/D9nYY9cGLqRkFF1qL51c=,tag:Y3JOnR22WUUTVuQ0tekLxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYnhqbzhUWFVGem4xVHMw
            d0crZ2FnZUNobGVOZHkvbHFjS2p4VjVSQURjCmU4MmFOc3BRdE1XNVpZdkF3VDRN
            TDhwSDU0UHdhMUNYajkySlVzemVnOEkKLS0tIFEyTDJXcHZNNUg4L0NwMnFZMnFW
            dzZtSzVxbzZ1WGwrazNFY0liN24zRWcKj0ruC6P5Sli6c57xpspe6KGXmhCmyakc
            g72BT/4zRA4H7048wtwHzeJFpD77sFG1q9atyUbNKGhY74e9wtDukw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:16:45Z"
    mac: ENC[AES256_GCM,data:v6hw05gtoxy2FuyVntv5TIeVbpzV9ZKz+sa4ulbA0Ud3Xx9n1AO7Q1nSTu2KdicrAvmE2aTn9lkLnaTUgp++HhA23jhOEPVffHcnfkAtzpgMnmTu3qWWMlmDEM/YBo9X9bY7szxZI1XBbrn8FbSqNaYY2IwFAg8nGEksnwLGUUg=,iv:UnMomHk7AAfNIs636VQeu3/D9nYY9cGLqRkFF1qL51c=,tag:Y3JOnR22WUUTVuQ0tekLxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
