# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: reactiveresume
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9F+OteqN91AlGtf32EJ+l4i3MI1wUC4=,iv:X239uxrApauy9Vjfb5exOyxM4jKxRJjGu7bNK+94mBk=,tag:R7LRBO4jgaxr0JpDCJHAXw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:/7uLRogfw5LIAdGI6qyPsRJnO4Xr5A==,iv:JDwXhdu9soXJfhWgVIts7ZW5qNgdwleJw4EhB+0nDv8=,tag:RCoV+O+HMs5CznqGo1p+Gw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:kFNmN3aOhmBXCfUYTgdEJ8h8LpOSs/o=,iv:k3LA9PQ+A+6vF764WZqs/+dJaYrz4FqaoSYmuTcKQnk=,tag:0ZY4+xLb4W+sygHcPf/FsQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:LiTy0Q0ft+G9G2EGAqagWk9F2pJ81eC5o1Y0R/aGtqTe0M9z00btud/u+Y9G6oQ3G7sRjytJkQaA3LLC1G2EoVxIdNN5b/SypeVe68fWRTMY+nghukkE04W4AUq6GDCqNw==,iv:W3zFXpPLQ3GXIFi0/Ek4uqGw/0oS2gSNd8jXOU9tsxM=,tag:2zJGIw5KrGkuYEbixToHIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VmpWQmdKL1IwcUIrSzZW
            b1Q4RGNXU3RIazM2SjRVWmtEbjBnUWYvd2g4CmNQSjFiZmQxSVoySzlTMUNDaU5j
            cy83KytxWFJHV3d0bXJNcEdaeDFTT1EKLS0tIHdZMVhIcXROdnhqYjRoZThXZkoy
            WWIxLzhDYVNsTVVZbmowNTJrUzRNUE0K+lb4eJiYDxHTpw71IO1LPZp7c3IJWe02
            pbC4PQ6wzOYsoKdRxChQEQEZTMo9Y6iUDHbsrhX19ma928owvqnlpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:33:45Z"
    mac: ENC[AES256_GCM,data:lJ2p6hgXXtc0U77y2JpuWkFOoZObuyKmEki9nepay8pMG7eupRMSCnlZcdBK0eTZiXLBzmctvPJLitBhul/f7MRU+vtXM1SL+hCr/9a7qLlWxRiXGP9wkUFy78+JIVFVbjSmRAWUx0m6qhEFsUpApw0StQ94ghuAZL2yUzyGJ6w=,iv:G3M+3IkcUX4paLErvNKpGZhn4LFWZRhtkSLqiM7mSmU=,tag:HRu0O5jPUkTdxRKXEHaPig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# MinIO Secret
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: reactiveresume
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:aHSmHV4g1dkl6iq9h4WVdoc=,iv:ii9LPc0gqI+x+tH0l4cFnKaXKcy0WX+VJwqeKtYxdBw=,tag:7tmxqff7cnFlgizhQLPg2Q==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:kGVqKB3oznd0YS9EDR+l2t1UoA==,iv:f0eX0WxzHQgn5WGQiSSZ+GJTux3EbPNMU5Ygl2BFVZ4=,tag:RK1vfnmUR5hyscW5uDlsAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VmpWQmdKL1IwcUIrSzZW
            b1Q4RGNXU3RIazM2SjRVWmtEbjBnUWYvd2g4CmNQSjFiZmQxSVoySzlTMUNDaU5j
            cy83KytxWFJHV3d0bXJNcEdaeDFTT1EKLS0tIHdZMVhIcXROdnhqYjRoZThXZkoy
            WWIxLzhDYVNsTVVZbmowNTJrUzRNUE0K+lb4eJiYDxHTpw71IO1LPZp7c3IJWe02
            pbC4PQ6wzOYsoKdRxChQEQEZTMo9Y6iUDHbsrhX19ma928owvqnlpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:33:45Z"
    mac: ENC[AES256_GCM,data:lJ2p6hgXXtc0U77y2JpuWkFOoZObuyKmEki9nepay8pMG7eupRMSCnlZcdBK0eTZiXLBzmctvPJLitBhul/f7MRU+vtXM1SL+hCr/9a7qLlWxRiXGP9wkUFy78+JIVFVbjSmRAWUx0m6qhEFsUpApw0StQ94ghuAZL2yUzyGJ6w=,iv:G3M+3IkcUX4paLErvNKpGZhn4LFWZRhtkSLqiM7mSmU=,tag:HRu0O5jPUkTdxRKXEHaPig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# App Secrets
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: reactiveresume
type: Opaque
stringData:
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:toLIdLcwtLmBzOQZzemDuVaDLdccDWg=,iv:cDCg25FSToGdO3uCUqwjdxhbYBuvf71EZEQTG2D2yAY=,tag:wyTbjS/F8MexdkK3Q33Hew==,type:str]
    REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:z0P2NDDf+wHJFpMNB2AOygzwTNBcXOo=,iv:6ce+AVmSFw/2QYVPWHJu6nW/R10pgyVT+GF/rXqAXjw=,tag:OrG4X/5htKLmoUPN1M4WhQ==,type:str]
    CHROME_TOKEN: ENC[AES256_GCM,data:BpbLtk3f85adLgTmNYBxvHYNgg==,iv:tzfyd0grdZIoQRHWmnSn8fTidBRjayIrrXzuLM7pZh0=,tag:cHh+R3BcOCaOeRxf5B3X6g==,type:str]
    #ENC[AES256_GCM,data:GQ/P/qLZcm3keUfx8UnQMvurAwHN/YPQ,iv:wBkpmsQfzJXYg2BU7jdm1Q8Dn5ZyPc880U9aIVLGffE=,tag:n7KO8ZQhia7qYkpXmPQI+g==,type:comment]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:RA3H7L350AcUo7eA/4NtOMxdEfA=,iv:S7T+2J7yVOeE4w/iPS5oQFJO2FwRF58IcWvKin373f4=,tag:GtLpcv7MhPUWuHrkBIsBKw==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:OQR2u0QYrzIQNhh5Qrpw4LoxMV3jo8SLLQaIyQqzQaZvK5TSubm3DA==,iv:jmarbB7TGRtDOjt8yQsSJ6sJrgLQgsZ669L79Ql69uQ=,tag:Ay/XzF4iTv2vmjPcYJnElQ==,type:str]
    #ENC[AES256_GCM,data:uqp7BofK5vCv0uHIJUO3ID8YQ7McW2DQ,iv:+JahZoJazuIazZMTI/QJ3ahEHX7U83F9zPYr/7N2wUs=,tag:JcAGRMwrQ1B3AcCISzKxWQ==,type:comment]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:ouTtleXJUq/RF259LxgVOBryaRqxkzq90R90o23iIeYndr3zc06OmTx4PI7yS2fV7Z1eeFUbl+Qx5OtebHAFsZqnl7YfWlZF,iv:dcJpUu65wIogspp/mFDmHnLYXNFmKKjtsR+3/IuPT7I=,tag:lWMW8tcrYRNdIvvoX4gsMA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:12gaSwnQsACIHNFZNyyyDfYO6G7Vi5dnewq5vNsY7msGEk0=,iv:GgZnTlGMWbt+zI1RWNfXyzqaj3WtwU0wXo/RtPjvpYo=,tag:XocXm66oX0cPtvjpQAAacA==,type:str]
    #ENC[AES256_GCM,data:KmGuMAEdHbJxz8kNnDlqCyuvsLqQdh9G,iv:wMamOl/j09inj0zjP0TX5R3WLRrtHXvXnbbHjvaRvTU=,tag:W+B0TqYElwQWjtUepIGF8w==,type:comment]
    OPENID_CLIENT_ID: ENC[AES256_GCM,data:GYY9gLwrr6q8N/V//HFg39y9DqIxsVD8PlYRJo//9u0WRMgjA3FdDnUAYzPP9u6cux6cSJcU7YTNpD0sv6nogw==,iv:oXpe3WCKyZBYlDSLg/KyDBHnu6iNTaAp2DkU7nLDSE8=,tag:GQi4dsIZlTcC/oOOcro0jg==,type:str]
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:tX5XLOWliPEkZ6+3lhdhqeWDcSiQ+I4XlRZfjDDIpF0CtjbzIMtlsfdpzzEmmstexRQsMlbDdAh7ZgjCshxW4Q==,iv:NO1tkqzKQ1uuJq46ZN1C5bvql3RzOHbdCStfg1yw+0Q=,tag:K/Jct2HVbdOjSgcqpYvQ3w==,type:str]
    OPENID_AUTHORIZATION_URL: ENC[AES256_GCM,data:+gbxdBD8cLQqj1f+cOQzlmK/Szq63mib5J354l9eq7p2VOzjDxI84pSkSi1pSNHPg0DRdQ1UVa0pmp0jJzS3btGx2kl/8wYy4Ms1r7NeOVoi1oN0vr2lyg2cjlYiLto746YfEO6WCnsB7yz//5yPfR55eigdfTnFQhTj/PRixSBU+1KVvl2q+ZqYHb3O,iv:LxKMLIsOwxjzQmmG6BrMJSnkk6lolFrGg9URIuNLTIk=,tag:/la5RwB7EctvYZlUckfKig==,type:str]
    OPENID_ISSUER: ENC[AES256_GCM,data:+zZKKvvUc8gktwVzTdzeQb5AWzET0MNjB9ShN5COYbxKU6JvDwWHSRxi7o2CzBqYiWgKH6S2vXQRB/FJxykq3y4CRqNoijI5uQ8OyknsuVv2525UTCIifLEPDtUjpxKzwHgMKh2uXpJOvmQv3MdJn9QlL5H3EZDnCNMxZIDkUw==,iv:5XCv9ZT3LWiTwAAKqRk+DaS3575iBychYfk4sassmIg=,tag:v/nwvJYJoYwhN4gbj+ftMA==,type:str]
    OPENID_TOKEN_URL: ENC[AES256_GCM,data:EYYa9KDjPqOwPFkx7KG8JhKIQbxxEszUIBv5B9RPtpEL1ei2JYZDAGepo25k3WGDkZdWxLTRZAu2t+7c1A4ftv6KF8ehQJFGXtYhkIQTUc6w5lhH6cHSIUNQMDo7tLAk6zFDKCR6WYRVokkRFKjwtC0iPB18GsizpQUCVsrmhJPQi8qDsw==,iv:VK4WGS4itYns4Ly7iC1Wb0Dh1TAjvr8eqoNOQz8xiQ0=,tag:l6TIEj8lYRSr9zy+bGXw2A==,type:str]
    OPENID_USER_INFO_URL: ENC[AES256_GCM,data:jlMmS1zFNTD9iGPJvWRi2XmQ81NeC9EKIAwUYxlst3RuYbnWcueGO0no+Z/5Y6Rt6wRWKLuTao7ruX6xkcfNG5bWvgkvUgzqvqejJeZBaiTL6anGz/eSwr9B2S509G8Vp1kuvv59yfbE+IrbkBj+gpfiTHsNv1E+4ZF5CZpt6I1lpv1PXW68/g==,iv:NNQean3aCebnJEflg16PihiG4Fqjj9z6p0pn6ry0MSQ=,tag:S+UGjqdQGrtSwFtTAU0Jlw==,type:str]
    OPENID_SCOPE: ENC[AES256_GCM,data:YKHaSCx1FXEIk30aEcpjWOs/RTg=,iv:WAS/j9ZpynU6mC4HvEciz9PBL2qqL6ltFGArZ+QjTOM=,tag:I7kTonrOf7xHGV0gghiBWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VmpWQmdKL1IwcUIrSzZW
            b1Q4RGNXU3RIazM2SjRVWmtEbjBnUWYvd2g4CmNQSjFiZmQxSVoySzlTMUNDaU5j
            cy83KytxWFJHV3d0bXJNcEdaeDFTT1EKLS0tIHdZMVhIcXROdnhqYjRoZThXZkoy
            WWIxLzhDYVNsTVVZbmowNTJrUzRNUE0K+lb4eJiYDxHTpw71IO1LPZp7c3IJWe02
            pbC4PQ6wzOYsoKdRxChQEQEZTMo9Y6iUDHbsrhX19ma928owvqnlpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:33:45Z"
    mac: ENC[AES256_GCM,data:lJ2p6hgXXtc0U77y2JpuWkFOoZObuyKmEki9nepay8pMG7eupRMSCnlZcdBK0eTZiXLBzmctvPJLitBhul/f7MRU+vtXM1SL+hCr/9a7qLlWxRiXGP9wkUFy78+JIVFVbjSmRAWUx0m6qhEFsUpApw0StQ94ghuAZL2yUzyGJ6w=,iv:G3M+3IkcUX4paLErvNKpGZhn4LFWZRhtkSLqiM7mSmU=,tag:HRu0O5jPUkTdxRKXEHaPig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
