# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: reactiveresume
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1qgNMUArI+VDu+y3XU/JzKQXvZ7k+yY=,iv:Sif8kOOyxPsEnYmx/0v2oeVLM++Tl6D1iGAa7hCtGR4=,tag:/6hLrmmgXsTOZQNt1kXbsg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:d+EjUN50XCoiHByPKTCEJmVA7IBtkA==,iv:E0bHuB+o8UYnMJDn7G0wc8HR6pDk2yUg67f30FkZ3hc=,tag:UVS9HeEgjvQ+L//mruohUQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:l53f1LESCXOuNEQbiJ+i5GfOfHhI7jo=,iv:4mYfkaij6IdyYbznFLUflVlC2pH7ZH9DqqbnQbf6M9E=,tag:bdZWn36xv6tjjN/x6uUB8g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Eo5BYzSOWW9Z9xRO+YGjI+9i8QDF4rZkFgr0eu3Zal8ElWeb4Dr1KG2OL5elRizCZ6DGbwSSBCmpqa9bzSCrtyTx4iAJm2++6k6D7EQg/5PurPb/UHiSvxqmOW2efNhVHA==,iv:6JZbJyQXG4vczcnofZfwSf5z5Dpl9kGKAsa02Lh3NGk=,tag:/6bsauVaaJAucqrZSMuMTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQmovTFZNNmg1MkZ3U2dh
            cVhZeStCNlpyc1diSVg4YTdIcHN0elRUNFhVCmJkOTBUUWJqM2F1QmZTdkJuZ1pR
            NGNwa25sOFZqLy9OSzM0KzNMZytiVFUKLS0tIEY3YzUyblpLUnVEUHp2eFFRaXB1
            UWY2akYyZGIrdDIrOXFzTDhrbUZYaUkKOK6BJX3iS7DYOUdGTWOwOVu2CJsgbhzy
            JPW9dGTbnmAIisPIp4U9aGYywHcVESiYJ7uD8SQR9kcFQ0Dzdfg0SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:28:21Z"
    mac: ENC[AES256_GCM,data:gs/QgHn6iKCVycLESi/sP6XKWyLaVstIaBkOigCWuSEfmhNDvzZ2WYaBsPMJ7TcmZTU0WzxTh/UeC+uz+W3ZepJZyc70EAl8K23N9fDFzaVmO6hpqeeahFINVU8pZ+OQV0UyayLgswAy+c2fmOwdgxORXMXQUuCn7wOHOV29ehA=,iv:FcId3KSuRHPhpVyt4cJ2m83yhCE5jP88gTKjzh7puss=,tag:pl17eN81GoMDquYzIlty/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# MinIO Secret
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: reactiveresume
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:72XKHbuGqE9a0BypdHzZSCY=,iv:D8226ha3qwdq6hZbM+WDpzxwvpvZAFW4I4uFAqhxsk4=,tag:wSdIowbysJpgW3W/bbogPw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:Yh0PiZVk6GahJw/bp+8r1A0rBQ==,iv:Yuaq+Zvx2tGfDhCU6WXRz/1m+ztVK0x7UDEjNpYn1Sg=,tag:TT67GkJcEZh1HkOHeaW7Ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQmovTFZNNmg1MkZ3U2dh
            cVhZeStCNlpyc1diSVg4YTdIcHN0elRUNFhVCmJkOTBUUWJqM2F1QmZTdkJuZ1pR
            NGNwa25sOFZqLy9OSzM0KzNMZytiVFUKLS0tIEY3YzUyblpLUnVEUHp2eFFRaXB1
            UWY2akYyZGIrdDIrOXFzTDhrbUZYaUkKOK6BJX3iS7DYOUdGTWOwOVu2CJsgbhzy
            JPW9dGTbnmAIisPIp4U9aGYywHcVESiYJ7uD8SQR9kcFQ0Dzdfg0SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:28:21Z"
    mac: ENC[AES256_GCM,data:gs/QgHn6iKCVycLESi/sP6XKWyLaVstIaBkOigCWuSEfmhNDvzZ2WYaBsPMJ7TcmZTU0WzxTh/UeC+uz+W3ZepJZyc70EAl8K23N9fDFzaVmO6hpqeeahFINVU8pZ+OQV0UyayLgswAy+c2fmOwdgxORXMXQUuCn7wOHOV29ehA=,iv:FcId3KSuRHPhpVyt4cJ2m83yhCE5jP88gTKjzh7puss=,tag:pl17eN81GoMDquYzIlty/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# App Secrets
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: reactiveresume
type: Opaque
stringData:
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:km+HHrnRMWA/Hrc9cSzxvMhn5flPgOA=,iv:Ze5Lwa/d8LRmy057nPO9j7iTZuagMErgfwYrWeIiriI=,tag:UzAhVKPHEADJc6sZNZqLcg==,type:str]
    REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:dNdNtUiqL+IaHndYySOcLgl86tfFvDQ=,iv:3wXCuuilH+QwUYsen7l/ScStASNkgQig5P7F74foLbY=,tag:grfOKgJuVtXym9v0rL4v9w==,type:str]
    CHROME_TOKEN: ENC[AES256_GCM,data:VMzu0b0WrQf6g3RYfNfvrXk5gw==,iv:M6QS/mRFaZnIcl95txUpx5rLoBYzJU5by1CVD1CsyUQ=,tag:Pc/SOJHJ8hHoNGATAJMCTw==,type:str]
    #ENC[AES256_GCM,data:X7r6dtJfWqNyOLF0kicg5FwrgQzk1ypb,iv:XMQmhbjQop583ZXHx+ymrWcTMG3Tu7Z96dNf2dVeBfA=,tag:QteG34/Jgp1XfHsVIxURsg==,type:comment]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:e4hIdvcRwt4SwcGcPHMiG0u1Sco=,iv:aRJwrZTsh2YWA26pE6hdG8P2Ev86Jt75QflRVUMdTjM=,tag:W7RDud+lc6/nO9LtX4js2A==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:K0As6akSI4PjBu4aFNXRFgIgsG3dpzu+krdEhEoYLC2AosQTiI8Pig==,iv:pkYK5o7lykMkUVpBSDFhA5F3SwS+l1a0zXhQwiedL3A=,tag:HtiJWTw46oLUludtYdWo2A==,type:str]
    #ENC[AES256_GCM,data:lphYCGYTu8R6q5ybvcZ2lPdrkh34YLa9,iv:LLmQJawBpJlSTeZgAWtubuo63YqRaanbBeGOqShlHs8=,tag:9KX7WnOVeHjuNMi2fGPInw==,type:comment]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:7QRAwJkEzO9tsgm7mhJeUGMFcSabz30gkc83BQ0Xd/qJveO8osTCsUrQ5EAYK2DvoDy3Z5ySKzeTWo7NXZvhNutQwrGLre1f,iv:CF0AJaloNe3G57dEFOLx21UeXcs9eofElXUiAVSji+w=,tag:LBdxXBLpGz1Xp8F0ByuI7Q==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:8mmBpbPvb8KTJDbT/NOL3bIye52ohq6G1fuKgMWFJSxt6rM=,iv:b/1A3CMU3CePSpWhH/dI6mhGVkx7SmGMDIylNogd2A4=,tag:luHTT8Jsg8HKfwQOnoQvwA==,type:str]
    #ENC[AES256_GCM,data:Luny1Wi0qrBTIvQ7JXR0WBijdB6sK1cF,iv:jSh45ADWd04y0J91xLlz0COogeP9fUfZS3U9/IzQ8Wo=,tag:WvoSPmaYEWNPeeiwo7/5Dw==,type:comment]
    OPENID_CLIENT_ID: ENC[AES256_GCM,data:I08Xvmu/MsRV/5tOJRsU/vOtuTtqYOhZpcavKwUsiST2Kq+O0gJMNvNtx6JvyiUF8pgBIP+zWO7IRIZwpWrnBA==,iv:i/AaMDcP/WfhyRKyCMIMUqFpY6j1ZTMk9xKk4oVifG0=,tag:tyfPlh86GrHx7B36wBaX4w==,type:str]
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:UtJg0QbYKh4j6Y/KVxu2Qd+0YrzxxJ1eSCzqBgU56E3IA63rTN99DGlaL7Gst4QQbs2QztlWx4ToCZF7VC0cNQ==,iv:zgxCL+rAzIvcexb4uKQNw+G0e1kUlBSXEWK0UBKpxAs=,tag:OgciPeoRGzmEZh29617VNA==,type:str]
    OPENID_AUTHORIZATION_URL: ENC[AES256_GCM,data:mgVUVVdX3cbULfnAjCS7hsiuDmzL/N88EWxfS8htnP7FAspvR1PW8lAp0A4XRuYUYBZOaH8ThqLPR3wLda0GX8nE3Pzyiyre1Jcw4KFD38pnGy9vN5p1iZj7Rk9m/f71jiL8VxVbKFw7VF1VNU88dcf7AFO5VlJqxI2WyTD7d9RKjqDKizMXLd/DUAqg,iv:e4MxcMAQe+0wAlgXXyXJYWNlL8Bo7wScZ5vuwmSoVfM=,tag:zPV3nDTg85/c2g1gbLSHMA==,type:str]
    OPENID_ISSUER: ENC[AES256_GCM,data:yWri7d+x+vCK4OMD4rJzGeFTrQMGummIvH8lsFTIcQuAUFK8eqy0AQypRdvUfAlQMTeU5u2P8LHL21kqFz457Igm3Ox7JEzOX5c8aH1nbVwXKcaw3LsqidV6lM1KdzjM6WOzWxx2/wXGBpO8IOXrBCWTRRaegDxgDew9QbnWyA==,iv:riTjM+7uSip4uyBhMb8vWid5LqRwT1RoRgwmEnCje0k=,tag:6d9rtkjnx7bEUihbadYJRw==,type:str]
    OPENID_TOKEN_URL: ENC[AES256_GCM,data:5ItFOMd+ppf20Lccm9ABrDC1iPzrxh+j5PsGoYZKLgM4skgvlenmW4lsYfwMIZGtGZZfrAECg3NZxXk/1EKE9bnJ8AXqnTskELgMWYiKO9aUMdXVq3SxyEYykeVwZnBkBZKouD02Xn1k4nzUluKhrxHqpEZjOQAyWf7Nd+OTERRvcc6rQA==,iv:dXDmGPgRPFOBz3P7C4wfZyK/2svOBq5Qxg84oRqtKKw=,tag:TXsFPyNQ1l+o5r2wVvardw==,type:str]
    OPENID_USER_INFO_URL: ENC[AES256_GCM,data:mL10PpZMdUV/yOUwV5q+tJEXTxbxcZI8O7EUYq37VEZOcZn4gBjisWNYHVxTfSwq+Im1u9EpgOnYZNKGjv0NmgWaXrHlF+LMvbsfJFpkMK9nNdWZTi9kgb5jwS9c4s93+MW4CBZd+4O3Z7qc2vkbgo8VJAUq/ZypGse1iu3e2epGCG9EIo8IQQ==,iv:GtmOK6qaw27T6LLCAKQV8Xs0oTw4pymjGn0bszMxWOQ=,tag:gRSaF0JFMLSME24Nx4DDBw==,type:str]
    OPENID_SCOPE: ENC[AES256_GCM,data:sG0F5CYQDmi+lceBnFWvyuZrRWkSYZVvAjuB,iv:hLa0l8EL0/41ePcAvJJLHcpQgMtOFoFw18wVqVwoegQ=,tag:fLUzYwVPLp+NJNMUO7sGpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQmovTFZNNmg1MkZ3U2dh
            cVhZeStCNlpyc1diSVg4YTdIcHN0elRUNFhVCmJkOTBUUWJqM2F1QmZTdkJuZ1pR
            NGNwa25sOFZqLy9OSzM0KzNMZytiVFUKLS0tIEY3YzUyblpLUnVEUHp2eFFRaXB1
            UWY2akYyZGIrdDIrOXFzTDhrbUZYaUkKOK6BJX3iS7DYOUdGTWOwOVu2CJsgbhzy
            JPW9dGTbnmAIisPIp4U9aGYywHcVESiYJ7uD8SQR9kcFQ0Dzdfg0SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:28:21Z"
    mac: ENC[AES256_GCM,data:gs/QgHn6iKCVycLESi/sP6XKWyLaVstIaBkOigCWuSEfmhNDvzZ2WYaBsPMJ7TcmZTU0WzxTh/UeC+uz+W3ZepJZyc70EAl8K23N9fDFzaVmO6hpqeeahFINVU8pZ+OQV0UyayLgswAy+c2fmOwdgxORXMXQUuCn7wOHOV29ehA=,iv:FcId3KSuRHPhpVyt4cJ2m83yhCE5jP88gTKjzh7puss=,tag:pl17eN81GoMDquYzIlty/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
