# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: reactiveresume
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:2plKfQW6l7csBRYETFILUYFPyRG/zQM=,iv:864iXuxtMhQcZfAG9/BnMURtFhpSExDDoVA3gLCZ0/4=,tag:1YyyMba2EqDPvwGVm67W/w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:gD1S9BhiQemXQ3+KN6NmafWrwPyTrg==,iv:oAX7tuhofI/MEV8vu74mjiZUFNGhEM0VHecknVjhUCw=,tag:eSYflPhDyz8clV/sEz0Q1w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:jkyN77CAqwmdOIHNvqEeVwjyG/jp5uA=,iv:weFepEj2MRyjHDXTCndqd3Rh5OX/5NErLvvTEMRu038=,tag:CvDebL2qsbxu7lb0YojEaA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:BVil3QlOpCZzebDNgj3rWGkMFgv5RkMsOq+JY6O+UomCkKiQ6sg84LNHqpmx7R3h+ZRVtkU9lMTp97UF6dzBrNesTryBlNaej9cJ0StiHW1fzxtqxYmf0mdsQppTRsa/sw==,iv:GGoGj/LqOEe9X0Jyz14al/ZuWWdPpIE3OMvi2fGQtaA=,tag:o4MXV5G6uV8/GMVvrkfZ8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSDhCZUhVUlRuQWNYK01M
            YUdZR0tOOUJNNlJxZUF5eDdiVTMza3cwK2x3Cm5ieGljUUxTaXVHQ01MajVSRUYv
            OEUwUzdwL1l2eGs5clFPUXd6c0pENkEKLS0tIFBRTVUvcC8vbmxOVFlPTVI0SjdM
            eEQrRk8xSnVCQUUrVjA5ZnBHRnFaU3MKG3xWKB+IsrvAMDlrV2Bk8R5IUquR8Q+h
            Xr/zoGLmCYHBOFSO/tkaJ2+wI0VKcpArOOdgrz7Qyh2LuFXv4Asf/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:51:15Z"
    mac: ENC[AES256_GCM,data:jgJihlgJQpBQmeY5GQmi+rkTyiawqP53wtkWx00n+gvHQRGWrFgZy921o14mXSHDfQUyuHWh+PTpFtefzi0Rl+gqsIZjqdpklYnW8Aw+97teBWAwn2BiAHCH7upYIcc0+ybrmvu7xBhS3q/5/fWrSH99oyY7EvESA66SNYhFp2M=,iv:GCW3z8TvCsrEh+VG+63Qv3lt9vj1ef5xEj6euQ+jEnc=,tag:UASPO0m/Qzy+flThCbrgaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# MinIO Secret
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: reactiveresume
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:fERrIvXf+NJE9Zdx9tnJjeM=,iv:tCeuuqeLZDA8LUhTEfmEdXmCZJIeLaC31VIPg8aLWnY=,tag:t/a6W0VK6phxXsGR9CZeNQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:MGEZ7jTO3PlwBAQKMTW3gRRvtg==,iv:3Wq51CdLXARoZCjvr4ZwUUUtIvgbYOE0b5adiGA5F08=,tag:yXy8AbLD04sdGppS5o02Cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSDhCZUhVUlRuQWNYK01M
            YUdZR0tOOUJNNlJxZUF5eDdiVTMza3cwK2x3Cm5ieGljUUxTaXVHQ01MajVSRUYv
            OEUwUzdwL1l2eGs5clFPUXd6c0pENkEKLS0tIFBRTVUvcC8vbmxOVFlPTVI0SjdM
            eEQrRk8xSnVCQUUrVjA5ZnBHRnFaU3MKG3xWKB+IsrvAMDlrV2Bk8R5IUquR8Q+h
            Xr/zoGLmCYHBOFSO/tkaJ2+wI0VKcpArOOdgrz7Qyh2LuFXv4Asf/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:51:15Z"
    mac: ENC[AES256_GCM,data:jgJihlgJQpBQmeY5GQmi+rkTyiawqP53wtkWx00n+gvHQRGWrFgZy921o14mXSHDfQUyuHWh+PTpFtefzi0Rl+gqsIZjqdpklYnW8Aw+97teBWAwn2BiAHCH7upYIcc0+ybrmvu7xBhS3q/5/fWrSH99oyY7EvESA66SNYhFp2M=,iv:GCW3z8TvCsrEh+VG+63Qv3lt9vj1ef5xEj6euQ+jEnc=,tag:UASPO0m/Qzy+flThCbrgaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# App Secrets
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: reactiveresume
type: Opaque
stringData:
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:PecvThYUb/SETWaTQ3vDaGm6iWrTFTc=,iv:elTxVU8UOqEnozFZa5U2SP02ICo/jPzbAJYbeh9oFsI=,tag:80wJ1GbyR2v3L7topxbBRQ==,type:str]
    REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:L82i86ui5LNPCzSnTyP/ZQ1hcTyIchA=,iv:hbd9vDEHgpCPyhAkeuyH2Dd2RO/JqMxhMFlmyb7lUUg=,tag:P3hvH2I2OJvcI/YQk70Ksg==,type:str]
    CHROME_TOKEN: ENC[AES256_GCM,data:3NWaHRwHFRRtcoH8EgEoFa2RYA==,iv:X/HE3+MxhV6JVoJcvZ2pJs0t4YClZDsN5sYOmzlFMFo=,tag:7xvcivkXQ5x8yFJP6waL2g==,type:str]
    #ENC[AES256_GCM,data:uOqwmdOGOP2e1uoOVmCiSbo6MARTsyGC,iv:vet+w4hZ00M/UT1PS3xk77p47F4waCKtoJsya98KBUM=,tag:RVIdspo+5CTwaPnun53J4w==,type:comment]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:DJc5d5+YqI005ooDb50iIBZJ1fI=,iv:fr3CXZvBbfXNcLfkh18mYXnVIwvcjG/+tr80YA8YMhQ=,tag:huO+yYpkbbqbLBreG49hBg==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:h2ShAnwZNrqUv9c76ui7i68DjmSqwS0NrEX/XowBCWO/rV9c40xO5w==,iv:uJWtlr3NYpuPSoh/lO5iCU3IOMNkCmS4AiPPYnsLmcs=,tag:iDuV5Wnl5ZlbnPck3EKUQg==,type:str]
    #ENC[AES256_GCM,data:nWivqQdSXgrEzuVbGfq0SKduFMyLXU6w,iv:ZEXf2n31+4Acf7oE+I0TanJ1Lc56lioZQICTR2PlCuU=,tag:xmNV3PH72FQmzukyVQV9Ug==,type:comment]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:OVYDkBrZjkzC12xuKBuTYlzb5FsgWSuE9aoJffncicnywo/EMgCS9GySJ1mF6rtWCR4twHUTtn2mZ1AVZkeb+CUlXpFNkQEz,iv:MXcqBRamHfBa2H+Yn+k9i7aC1Mg70gJnXNx0cWplkAU=,tag:uJu2MhHl0701TTVtIdTPbA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:TwWtAHFxbgY3pMI8ON+yK/bBg5jw89ZS66Ia53Clu/1J0wY=,iv:b7XX2Dz9bpqHqw41792Wj29lopfVy1Z/hevY64WTcZg=,tag:YV99beDgvGB3Mwt2YdJZ/A==,type:str]
    #ENC[AES256_GCM,data:4iZVRxmInQcPY4e8YCFLXCOdMgKZXLTc,iv:GreAOBMGxyiMK4JRp3cy+iXHGoiXx2v2WefPGNxWY+E=,tag:YkyTeBPjWjVTOIt5CGM+gw==,type:comment]
    OPENID_CLIENT_ID: ENC[AES256_GCM,data:EzZiSvcyubxDz5mVAfq5maUA0ImuC35SkhZiZN0ZobXGAqCBjjz4qi+D3iR/E6nI8fC18ZIB7Qa39hWeIwiOSQ==,iv:0m3X3KFTGLo5MeYmpbwWE6yAsR3fOhItlRtNKxhco6E=,tag:ggVVCmI69TmgvtmHlDyfUA==,type:str]
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:dHqvhMkqAyghTL59GflNwkOcpzr3q26nSvo/5GbFuc/Of5/kll2qvAJyCh3JfuQCrDD1K2uuOzu6ZB0zvmtqSQ==,iv:CA+M0BLOurco8Zb5iYL+cniV4SeRrNp2Ygh8BbghjrA=,tag:ZnD+5GwmTn4qVUAjZCTtlw==,type:str]
    OPENID_AUTHORIZATION_URL: ENC[AES256_GCM,data:pO4xobx8SU1tHO6JFfp3eBI2mMxy/OX0v2r2LLiP2CfOLviH8Cas9WiIv47AFNTDF0Eg4reDP3dlACO9UQAKbybPcJAEZWbxTR9QxDTZRDsT25E88u4SbeoRDTMt9DCmsHQMbTtHEeaQrLiDujezfOsGmeUk4pkFrUb9255TAnR8ofb7e+6EWCC6shkZ,iv:m5WxusU0AxheSjQlRoAs3WPmHrMuyYevfRCxmap8GUI=,tag:vh+jxgZR1KGSfxxtC8wJ7w==,type:str]
    OPENID_ISSUER: ENC[AES256_GCM,data:acNNzUcTyDWz+FvVKzsNdi6UiD6uwvhF4HDrRkBYQeyF6azT83MP1IUOoyqrIoOdA6CT5PNOidiUiC/ZYcjQtC8+GKIUKBAgdm5CYD5UlWCCLWPGgC72ilq5oZcGAOdlfKXl7V6wle7YYk3E7VxaV543B62P7f9QTeOPiCHl4g==,iv:2sdDDkMo70lsL6LKjHRzYyKS5JbAXBMrcFkMJc08stw=,tag:SNlcq6seosmdjwBKA6Ma0w==,type:str]
    OPENID_TOKEN_URL: ENC[AES256_GCM,data:WVCYZ07taFR70QU9kIjYZvB/+sjMtq0iJja1p3YqGeMjshmUTBMyF7KSpj5XB8267Bc09nlSjYwWAXL7KQPgSedlE7Jp71RfnVPiVj8dhSRHSkx/R/lyeEy6bIbWcQaIVgBxEgX6S/vvDEY8/DDJnCBmkAngTFfY0TzCB3mynrGRC0QJiA==,iv:m1yZpFB+vSAyUpMWRMdZVWgHUMWD4zCWxWv0byrSdaw=,tag:fcX+hrzYbpD3CdbwWXUj6g==,type:str]
    OPENID_USER_INFO_URL: ENC[AES256_GCM,data:vJgxa1o9tNPQwtWOIbWxNH/a4/SRgwMrUYBRJ7MbbejI2vbfmV7iSQ6gkNrgcsk2hkNSnIhGARJag0A/ttdl7NKX2ZfLlw5qFB2wNKFw1aArHKNJH4b2lIMUSzDjc1mpQpHyBQ+FXKnPyCfCR0mUgJBgzVQzTh+jgAq3PkY/g1hc1aBaCWIcAw==,iv:oL3DU5yCXVZoHQUaYWTf8PxpammtRfihP5dqcxi5hKI=,tag:M3Wk5SaMwOO6f84ewH8Fvg==,type:str]
    OPENID_SCOPE: ENC[AES256_GCM,data:XnKTbJZ4MnyA78IE7GFAXGBDm24=,iv:nkE7a61Ajbwwf+kd+t9249VycyKakKcYqqUacLP3WFQ=,tag:ODHJ0ZNRMj9zF7Ilsem8Vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSDhCZUhVUlRuQWNYK01M
            YUdZR0tOOUJNNlJxZUF5eDdiVTMza3cwK2x3Cm5ieGljUUxTaXVHQ01MajVSRUYv
            OEUwUzdwL1l2eGs5clFPUXd6c0pENkEKLS0tIFBRTVUvcC8vbmxOVFlPTVI0SjdM
            eEQrRk8xSnVCQUUrVjA5ZnBHRnFaU3MKG3xWKB+IsrvAMDlrV2Bk8R5IUquR8Q+h
            Xr/zoGLmCYHBOFSO/tkaJ2+wI0VKcpArOOdgrz7Qyh2LuFXv4Asf/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:51:15Z"
    mac: ENC[AES256_GCM,data:jgJihlgJQpBQmeY5GQmi+rkTyiawqP53wtkWx00n+gvHQRGWrFgZy921o14mXSHDfQUyuHWh+PTpFtefzi0Rl+gqsIZjqdpklYnW8Aw+97teBWAwn2BiAHCH7upYIcc0+ybrmvu7xBhS3q/5/fWrSH99oyY7EvESA66SNYhFp2M=,iv:GCW3z8TvCsrEh+VG+63Qv3lt9vj1ef5xEj6euQ+jEnc=,tag:UASPO0m/Qzy+flThCbrgaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
