# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: reactiveresume
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:i25CsmAZgQtLyZNWNsApYNMn7RpUp9g=,iv:W9GwAakE0W72vYfKd+6A47BHm6SJkN20/Ia4fVpt5o4=,tag:G43CXKf4NmIOC/8rTBLqEw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:iJNlyKdH/aS/MsQMg2zwbQBpcrIBPQ==,iv:EWa2RR/ztKs+ZGjVYoY/HVq5AIjbuF9n9nvo+yXlr38=,tag:Lq30J3TyeKzJ36UEDhD+4w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:9W6F9cCqazWK6NOW7sME7xZyb4eOZFo=,iv:YCcdryGEwQKACx3RlFcEJrc3glsSwmXLqqskh9XDoTo=,tag:+Csr1NnaL3TOvQ/KYcty5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcUFoaVJ0Ly9QejlLTmln
            bkkrb2lVMENsVlFDY1BHQ3VIdEJzZG42Znk4CnlCUGhRRmVEcEVScXZrODJCUzJu
            Snc2WWNkd2twWGhOTDhzcFVtQ1B1ZHMKLS0tIFpDVEtOQlZwWkp1NWN6Q3Q4MFhv
            enFQZGFyV2I4OVpSVUk0aU5RbG1jTGcK7+ZF6ASh+b3RS9NGrXwWK5cW2DBf5pI7
            0kOiIi7vYqoy3hYGkCQgq5QxeVyaeN+JflxmULeVq05k1Kp75M4/iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:24:35Z"
    mac: ENC[AES256_GCM,data:wlVxrFnsG0FCIQfzfRE109tPfrRKhLyrOoJviJgWDImiSR0e6l0BR0p8CENfLFY6lrWnEV47hA/7nygk8jxcipIkDVtT2+mlwTtRhs7I6ysSe6Q/E5LK9mu7cd8mN1iOolPJAEFqnTLDVZqioPr3lrRqepE7Cav1EXIy31nhKdU=,iv:FCZbvRzL17soNvhYC9j76Kq82obcseyBG5cGeJSJaT0=,tag:d3PR41gsO7vctWA33pybpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# App Secrets
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: reactiveresume
type: Opaque
stringData:
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:pCcRvMUZZMviHTwaHbK/BY5nJaqL/1Q=,iv:eOjX4vM0S5B4fFYVzG+//Yz4I0+LV3z4xacebAuvaBY=,tag:KG2p/wVuztSp2IfJeOQOKg==,type:str]
    REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:xax5lAiiG9rbjxZLLC09a4o8S9mi6+Q=,iv:2CQx8vyP250FZ5ANL7P4lXG1vvKqqs3GiqW0H/iOx7w=,tag:fliaFBf3xzGkB0N2ZQpXMQ==,type:str]
    CHROME_TOKEN: ENC[AES256_GCM,data:nThtgwqFjtfPglD1LrtvcjJqYA==,iv:ZtwjcRdyAh8zaAv1GOPcGnZzFIlgu2r118hXOT4Sj2E=,tag:8ifgZv9AzELJZw6HrSqqVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcUFoaVJ0Ly9QejlLTmln
            bkkrb2lVMENsVlFDY1BHQ3VIdEJzZG42Znk4CnlCUGhRRmVEcEVScXZrODJCUzJu
            Snc2WWNkd2twWGhOTDhzcFVtQ1B1ZHMKLS0tIFpDVEtOQlZwWkp1NWN6Q3Q4MFhv
            enFQZGFyV2I4OVpSVUk0aU5RbG1jTGcK7+ZF6ASh+b3RS9NGrXwWK5cW2DBf5pI7
            0kOiIi7vYqoy3hYGkCQgq5QxeVyaeN+JflxmULeVq05k1Kp75M4/iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:24:35Z"
    mac: ENC[AES256_GCM,data:wlVxrFnsG0FCIQfzfRE109tPfrRKhLyrOoJviJgWDImiSR0e6l0BR0p8CENfLFY6lrWnEV47hA/7nygk8jxcipIkDVtT2+mlwTtRhs7I6ysSe6Q/E5LK9mu7cd8mN1iOolPJAEFqnTLDVZqioPr3lrRqepE7Cav1EXIy31nhKdU=,iv:FCZbvRzL17soNvhYC9j76Kq82obcseyBG5cGeJSJaT0=,tag:d3PR41gsO7vctWA33pybpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# MinIO Secret
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: reactiveresume
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:yEwuATo3JlkbbuOYzviWmts=,iv:DVBk3/hZQscEbtBRcbWEtcNBbLs0YzA2pGPQJuNgBAw=,tag:rMX8Ti+V3CQvd8K64hk7rg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:AWpo/lJxnrmWYASMyw6E80sYCA==,iv:HdtQiEGXTuZDd6okqJ4duniwWKisfnDM8Zv9OK8SSDQ=,tag:UhTKDSYQQyXrRW8muzpx1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcUFoaVJ0Ly9QejlLTmln
            bkkrb2lVMENsVlFDY1BHQ3VIdEJzZG42Znk4CnlCUGhRRmVEcEVScXZrODJCUzJu
            Snc2WWNkd2twWGhOTDhzcFVtQ1B1ZHMKLS0tIFpDVEtOQlZwWkp1NWN6Q3Q4MFhv
            enFQZGFyV2I4OVpSVUk0aU5RbG1jTGcK7+ZF6ASh+b3RS9NGrXwWK5cW2DBf5pI7
            0kOiIi7vYqoy3hYGkCQgq5QxeVyaeN+JflxmULeVq05k1Kp75M4/iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:24:35Z"
    mac: ENC[AES256_GCM,data:wlVxrFnsG0FCIQfzfRE109tPfrRKhLyrOoJviJgWDImiSR0e6l0BR0p8CENfLFY6lrWnEV47hA/7nygk8jxcipIkDVtT2+mlwTtRhs7I6ysSe6Q/E5LK9mu7cd8mN1iOolPJAEFqnTLDVZqioPr3lrRqepE7Cav1EXIy31nhKdU=,iv:FCZbvRzL17soNvhYC9j76Kq82obcseyBG5cGeJSJaT0=,tag:d3PR41gsO7vctWA33pybpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
