# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: reactiveresume
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:z/NJwU/hgsUcZb8GxdRjVtHmzhMplvI=,iv:SMLA7wOtDXy/KL21B53y9VakPNSm+/TQ73/4hKMgQ8c=,tag:OVVCAGbkKTC6gUBT0Qe+vA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:S3xcAOohYmMHktdEdT3rPVTDns54rA==,iv:qOsp7jYVFXaawY9fMuSfqglx3zqaiRdpQarUCw9W7NU=,tag:nM+ZQxfChQKtHaPm38owIQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Emtue2/oKYAr3UX4fJdLxcJtAwEJ860=,iv:gfWOTOp1FI5cZCJfusPDs2Z5CWT2/OrD/19Bl+ROUxY=,tag:xnhfmY/SDa/PNVWoHiWpCA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:oAB3rPQoo3OfbpIfy6A0KDg0+J9Qvm7r2NUzzzf2lQSUq1SKcOSWMCuI+Vs2u5onS45PuI/x6nCmfFrqXQs8Y+h8gdPa4Q5hZmCpLzV4h1JHyiMvdxyb3LZ2e2kfSbsvbg==,iv:h0TKgGcjPoPG9SxeKmX+RjsUadLXSwqqgNY/NEU4uMg=,tag:hAyRlIEGwbVuR5SL40U0Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSElIbkgwU3N6dHA0dzVU
            TmF1VlhGSGMzTUE5eThiMkF4T3NtQ0RqNHlVCmQ1K09wdUdFU0w2QlNHTmxJM1Uw
            Wm1VbDlIYk1DTFphMjBNWWlaend3cm8KLS0tIHd6NXpVa3phQmNaSWRQaUs5bU5v
            c1pWRG9ZVVpQNUV0TkxMdXNBRER6aVkKFtxpZoJcPE4mRBsRFd9So/3oUB1+VZ05
            ifAWS/4114gr2sUv2BMGRCkNeCe7hl+wpHBd/Q/xirxaPrr6Mo6wdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:59:06Z"
    mac: ENC[AES256_GCM,data:2ACy5T/tAlIayAwXA34rHAGe+OZtEfZ3aFnz/4/sLq7TtkSw2FbR+VpuXWUt0GJs0/05DtG2pvFzt6xmj8EARbWJantOikliqrNBzD7DkxikP+DF0ad+fiJheie3LFw/MLYLGMKAa/Fo6hVmS2oahghL7gfgOX1i/R1Y1B9FRAM=,iv:c/27DImMr22PU3v9NAnTpF26EkrrMgC2mrqrP8Qw9p8=,tag:SVeVkFsfszadWFAAN3nEyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# MinIO Secret
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: reactiveresume
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:x6W400kX5JnbnLQ4Vl/dDw8=,iv:1Q99WjyScHtDkfN1kN6Am5daDSBAvQCdCDw9maOIUFQ=,tag:oZQreOd3fXv41QZYVm5jNg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:6zEvVycdWGXxCWiuUeRMzhghqA==,iv:TJTkGWDf5776IWtlmodWeijKTuJ0bOVobLGekc9Svt8=,tag:hL+14doXByVTz+ImxKiRfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSElIbkgwU3N6dHA0dzVU
            TmF1VlhGSGMzTUE5eThiMkF4T3NtQ0RqNHlVCmQ1K09wdUdFU0w2QlNHTmxJM1Uw
            Wm1VbDlIYk1DTFphMjBNWWlaend3cm8KLS0tIHd6NXpVa3phQmNaSWRQaUs5bU5v
            c1pWRG9ZVVpQNUV0TkxMdXNBRER6aVkKFtxpZoJcPE4mRBsRFd9So/3oUB1+VZ05
            ifAWS/4114gr2sUv2BMGRCkNeCe7hl+wpHBd/Q/xirxaPrr6Mo6wdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:59:06Z"
    mac: ENC[AES256_GCM,data:2ACy5T/tAlIayAwXA34rHAGe+OZtEfZ3aFnz/4/sLq7TtkSw2FbR+VpuXWUt0GJs0/05DtG2pvFzt6xmj8EARbWJantOikliqrNBzD7DkxikP+DF0ad+fiJheie3LFw/MLYLGMKAa/Fo6hVmS2oahghL7gfgOX1i/R1Y1B9FRAM=,iv:c/27DImMr22PU3v9NAnTpF26EkrrMgC2mrqrP8Qw9p8=,tag:SVeVkFsfszadWFAAN3nEyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# App Secrets
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: reactiveresume
type: Opaque
stringData:
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:2CkLA+w4XJT0p0qbTe0C7PmFHwYQCKY=,iv:4oIt7fvuFstPlXNvjXVcCvWrE34aHHsjtrfymMTBbq8=,tag:P2sOYZUy1M8K/Gy5d/jpFg==,type:str]
    REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:W0xykCpMjlz2NKSBMtwwxSaC0+fPI9E=,iv:Xbo5MRTvdod+JfSijZF4DjVpC/ww5GbRJYgEZixhdr4=,tag:uAm0cDKnz1EVhY7iHZe53A==,type:str]
    CHROME_TOKEN: ENC[AES256_GCM,data:ONKCUA3MCTGMCT6qJ7VuvBK7DA==,iv:NK9EE97nOQc+LWpVizh7uTyaxHfd1kLfSTR4DB5WSgk=,tag:CdZr9wyWXjShguDQdLNKAw==,type:str]
    #ENC[AES256_GCM,data:Og0nfdvpL2vVttPYsFI1bldBkMFY6UDf,iv:28pCNQvHr+2Q2+FFgu5wDCiJ/Zb9rmH8awSkhT3hiLo=,tag:QbgjYDiAYHjhbb2deNUBvQ==,type:comment]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:WEwzo2aWLISTaiMl3liYSq/Op/g=,iv:WsyzHtFS9sQ9QjcCzSB3N8Qip1IbcPih0/IlMjlKnPw=,tag:cO3fjEBLimCu++3lbwUzNA==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:eG+hhAivhgoHPnpM9SU5qWRiWXcbeEJaRVOy7IteLz1x7wdTlqXqFQ==,iv:EthaEblVGJJTOGs+DBuYGELTYCWl+m2LeI0p9XmbXW4=,tag:Tk35dlIrMixkEP5KRrp4UQ==,type:str]
    #ENC[AES256_GCM,data:RTZAVRMgEFsd2GibAKTn+GwTdK1J+CsZ,iv:tFgsX5A8MkXg8RvDovg6gyAQHpoDCa/EcpI5TV6ZJAw=,tag:/zdj+JKqscI6ksXcwzt3Fg==,type:comment]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:3t/ZHnGZeZUbwUGmV2eObDzvGhTkykbc5bxMNcj8XqDgm1RmN7AXlHmJbu9lRGuGkMnaK+KUlZY8LG4g0YfMmuNh5YjrU1A/,iv:WxBRN2MJbuPIDAsaLgujiJmmcwzrDTAvYTYWEcIcq5Y=,tag:5YbfHDE9XsAgzjmO7Rcmwg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:+HDUnHeGtr24TL/SD/iJi4OyEITM9HLPxIcg+P5Tj0ghSkw=,iv:32Lo19oA0BurGOIB2AWkGTOKCtn/6nGzZpkfUu2zZGY=,tag:lQTydwsYbcIbr7HC6yo77Q==,type:str]
    #ENC[AES256_GCM,data:0a71vttVKHhCli2lF01uBGd50tE42ZMw,iv:RR5uRJaWbwmIk+iFwNgAmP83YOFcNq2Q6H/NiQBbSTw=,tag:BjCyC0FjJtlBk5G2wXVynA==,type:comment]
    OPENID_CLIENT_ID: ENC[AES256_GCM,data:6WOB+LNDWaOpHKN3clKByVK1tzVPctdZwcGFUJdjLzFTdG8CimZmcNzgl/zGMvnsrCiFCmnet2DMqwdd3c0vtw==,iv:bO4F1++xmJ47C6pCDGQX03gfVSRDihbL6T5cjT+pRgg=,tag:2eJHkaV6CTwuIpCklB+Zkg==,type:str]
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:5CFqPS6jCIwjsD+HXbmaynYMtbmG8GLF65dpvZLcJZ77yAPh9kp96VsDQLHYSM9PVmysB9WQDu6IZBwqdlxNww==,iv:ygY9NYHQzzWiOVwECBDSmtDT6yLkDJXdgbAseYEB0Z4=,tag:QtA9TRg8QFyzME4QQVFTgw==,type:str]
    OPENID_AUTHORIZATION_URL: ENC[AES256_GCM,data:yTBJk97elQ3pXuP5XIetHQQVIuvivnJkC35liWimqkEBazGIoww0h+T+tJ53GXQwEm24Yyba1LKWWCUI/1n+21seJGhtBd6NXECEUAhYq/AbWufDLOD6LjGf8QHxc+wPCwdyabSynLtHQu9xHLl4K0jUTAy8VdBn8ah6CQAvc1OW5sGfh3TKyHwc5BfA,iv:ckjiQQwssyVgRqwJ0mi1lyWh+GWzyhZCpYMZS476PNI=,tag:cq/PBBd77kqJnl8C7Viq1Q==,type:str]
    OPENID_ISSUER: ENC[AES256_GCM,data:ncw4+wH8CmCso+0KGv3Y8TGgwNHXQ/AFslvUZkm1gcC9H8wEeiA1/MQrzG5ArIHxUEH3drbVOwC/EfTjKacDhiOGUlh3T2gz8+xppfPjYq30y2N2lNXPoO46T4Cnngjh+U8FANwOGPpy9FukQYXKbXdi3RAn5ykq7jx/Uf92LQ==,iv:KnaF7zDqC+4f8akCm8BLdAifGtzzI3dhP/EAK9PsN04=,tag:GFAd1fgOQMcp5Bh9mLFspQ==,type:str]
    OPENID_TOKEN_URL: ENC[AES256_GCM,data:oF2+dYDQaoB43FzeUCTL2yesYvSu10IlpVr/YZYLizhuUDHI6OdyzEsP3bTnI4iDdW4sEWPP7zAQxutGJXUJdug7YmazMsfYh70cyoxEgVzdPRlSMF0+o4wUJIuecKoYM/kwPYUlkfHHSFzVD9EvXpvrq2Ws4cdj3eeQL+AAYn8OE+SCbA==,iv:S/YxEG4WI9fqfJSt1VEsOU9VUrApT8DeZCNy6Pxuv0I=,tag:6O1ppBpkfLJ/TE8w7CqxJQ==,type:str]
    OPENID_USER_INFO_URL: ENC[AES256_GCM,data:GJu+xoJSoR+ag5jJVTRjlsCz+BR8kfBjkjZqyIzw1NJje0LbnilNEjAKgZ+Kv/2MV2gbj9bMDAAWicXyHyk0wr4HaFM6+4k99jjQO46V0l7s/GluAys5b9QviopJaH7pLEvLScXpFoG5ufZCbaa9wIopv81aKB3o5gFU8iIGfMXC7ibLcNubrg==,iv:Lz0cTLBdevP8cscT9uDH/gO8uppyBvKRqMdD3mnbox4=,tag:sLc3nBsGyslUDsQL8fo60g==,type:str]
    OPENID_SCOPE: ENC[AES256_GCM,data:IG/6FnW/ZwqEF8B/vA==,iv:e2Q4i6499asJ42wR8mqG/VAq9nXNOHYFgkbTHtPi76I=,tag:1T5PXOF8o4R6zseDUOeSCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSElIbkgwU3N6dHA0dzVU
            TmF1VlhGSGMzTUE5eThiMkF4T3NtQ0RqNHlVCmQ1K09wdUdFU0w2QlNHTmxJM1Uw
            Wm1VbDlIYk1DTFphMjBNWWlaend3cm8KLS0tIHd6NXpVa3phQmNaSWRQaUs5bU5v
            c1pWRG9ZVVpQNUV0TkxMdXNBRER6aVkKFtxpZoJcPE4mRBsRFd9So/3oUB1+VZ05
            ifAWS/4114gr2sUv2BMGRCkNeCe7hl+wpHBd/Q/xirxaPrr6Mo6wdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:59:06Z"
    mac: ENC[AES256_GCM,data:2ACy5T/tAlIayAwXA34rHAGe+OZtEfZ3aFnz/4/sLq7TtkSw2FbR+VpuXWUt0GJs0/05DtG2pvFzt6xmj8EARbWJantOikliqrNBzD7DkxikP+DF0ad+fiJheie3LFw/MLYLGMKAa/Fo6hVmS2oahghL7gfgOX1i/R1Y1B9FRAM=,iv:c/27DImMr22PU3v9NAnTpF26EkrrMgC2mrqrP8Qw9p8=,tag:SVeVkFsfszadWFAAN3nEyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
