# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: reactiveresume
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:oNLu8Tdu1rwAjMwuMMi9u0RsaYrB8rk=,iv:CJ7gjggX1HrTH9wAW1E7j5jR+UABLHSlsGBg65zuVgw=,tag:GvLJ1wm4pjwYgI89jxnscw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:UzkQsCYCY/fzl3BvnqyONbvmNcwHmg==,iv:AhpDyg3r2b3Cn7GVX+QkA0sB6btqZSQTHFN5dbazxlU=,tag:ZkXLxqNlYQCBhGlcpfHH4g==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:JZhU6Mdo0srFM12sej3I6gA+S9Ku70Y=,iv:wjXqjJBUl0ts6HFXquQ3OIxFnOx44wL6gJ8RAV3q+Cs=,tag:OjONcODIyJDLmnguwcQXVA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:21ohOP21K6YmPCvrY6ClcpHdjENCFU9SxuTzFMaVRupv8TTTIPGIYwCMceVpSWYd9jlZVOBywVqUNDJNah7/tD/JjHlq60OrHtC6BFfXAhz7XAddgSbTRrahZ4BXq5lS7w==,iv:gllpH71ghnvyvnonUakKqnH5dcAfIU4sJ5bnTJo0FL4=,tag:pGUg8i6HXf1I17hGxQMWwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOWFOMmJqRWNVck85K05x
            S3NEU3V1QTN6elhvNzV1YkxtZ0QrMXJ4Y3g4CjhHOXJteXB5YXA3U05BMUpmbXBk
            RG54bUtKZU1sM2NCWXJOYjhZUk1oelkKLS0tIDVxbDBlQ3NnbzI1L0E2MVRRRWk0
            NHJKZzdTT1dxOUR1OXNKUlc2ZzZ4THcKBV1v203l1ElQQRni0racSt3CmHmGf9oO
            jT8NGnkMrt4R/mpXKo5tCnrKadrJpSdS1OkUYW+RUIYMbyWd6wzwoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T12:04:33Z"
    mac: ENC[AES256_GCM,data:DtQDZ0LmAqpv0rvJODxdVStq+M1rLrZT9ojgqgdAdT8LaZ16mOCyCIOn2aCHCmC4vSH9B1Ue9iHywgIotuw4tjM9ROFNedCoHUmc6Xa63Y95s/F9qbgkN84YYTq+OMI7NNaL9vyZzmTn/GPWnqsjW46ZFglo3bsyYQ8oFSBzQKg=,iv:3VOZYVIafVt9OjWfII2wfXoJJVVeQE5Vo/0ReGEHpag=,tag:v+e7OVYNxEyx93ap7Xobaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# MinIO Secret
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: reactiveresume
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:m71mERpEPkAASQ18dtqabFg=,iv:7/pgHmPdUF0pl8ny3OSJS+Ct0/YS8jrwmhgwKJOsELg=,tag:QeI1+KXRTYXnrdx3uKscpw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:6b8F+tH4JmLkYtC9rD0a2cW8AQ==,iv:/xso2yMEdPZ6UJQu3rSD1acgGPYquGAgvjI04b17OI4=,tag:lGGVwxgKAEjC7dTQYOlhaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOWFOMmJqRWNVck85K05x
            S3NEU3V1QTN6elhvNzV1YkxtZ0QrMXJ4Y3g4CjhHOXJteXB5YXA3U05BMUpmbXBk
            RG54bUtKZU1sM2NCWXJOYjhZUk1oelkKLS0tIDVxbDBlQ3NnbzI1L0E2MVRRRWk0
            NHJKZzdTT1dxOUR1OXNKUlc2ZzZ4THcKBV1v203l1ElQQRni0racSt3CmHmGf9oO
            jT8NGnkMrt4R/mpXKo5tCnrKadrJpSdS1OkUYW+RUIYMbyWd6wzwoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T12:04:33Z"
    mac: ENC[AES256_GCM,data:DtQDZ0LmAqpv0rvJODxdVStq+M1rLrZT9ojgqgdAdT8LaZ16mOCyCIOn2aCHCmC4vSH9B1Ue9iHywgIotuw4tjM9ROFNedCoHUmc6Xa63Y95s/F9qbgkN84YYTq+OMI7NNaL9vyZzmTn/GPWnqsjW46ZFglo3bsyYQ8oFSBzQKg=,iv:3VOZYVIafVt9OjWfII2wfXoJJVVeQE5Vo/0ReGEHpag=,tag:v+e7OVYNxEyx93ap7Xobaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# App Secrets
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: reactiveresume
type: Opaque
stringData:
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:arENDYmG1U8WJ/WPXgI2AUE9QdlgOgs=,iv:6TCB2MfVRgtgdmldnH8H+hHUTsJMPT5uw0oL6P2398c=,tag:3rf9kj2m/QW+fGeaspZKyg==,type:str]
    REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:NDddGym/9sbKeIXPSsW6w4xV6aG7coQ=,iv:9PC/5Ye/aM0Ngzr3D16masmOHxPyLYBeCKvaIySHcxs=,tag:BW2aMVimGPBJ05OQkivMUw==,type:str]
    CHROME_TOKEN: ENC[AES256_GCM,data:xAI6CM8HxiBj8cHZohtsgOuimQ==,iv:ImsCfk7IArU8clEWqVbfUPRh5BaDMoRxBgAxjG+9fCU=,tag:7FSYJ2DklpFyy7pwQpYkiQ==,type:str]
    #ENC[AES256_GCM,data:EcrPGQiJRc36+4eaUAiKiOMzbOD27Cm/,iv:WpQHbMfF92HZisy0qH6WImejTmC+/s6c1jcSADkqTzk=,tag:2smLC2wZ0nQvHEVLyCoMDQ==,type:comment]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:IQfMuqbW1RcIBqOijjwrKlpLDlM=,iv:ekaPEf6R5loTlKo0HI+j78IZ/Y05OZwjXHvbKcuKcWs=,tag:kb5vtZ+wBv4KvW8rtkJKjA==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:ui/BgTDuHuYyVi1QGSOpBaBRhowrlfrEPGiGnMKlVwZ0Cjoc6ZUa/w==,iv:rnCgigXvclm8mrUJVQccUHUh/s3HenQhTdxNJy8WB60=,tag:CLL05IQ+2m0dASAl0wjshg==,type:str]
    #ENC[AES256_GCM,data:NfoRWHj68nfdT4UA54Osj7EEEvWlcR/q,iv:1j7LS12gc2/ke/6mUYet2GzMRTnWM6+1wmt0n4gItH4=,tag:ZL4Nnjzmi0oJLDzg58U9ag==,type:comment]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:A9rGQryZQu0ddxMaKkYqDh7o0QT/fZCDqz39MvtsfzQghLvfMuRaTAx2KFNbCokCTf5y167ra1NimEWtNM5HPOGlMoYd9ces,iv:cwAYtbGRPOy8DPKpeMcIDUzG874S2klHNzq7oYY8C8c=,tag:W3gvhe9u1GzUZticBKXrGw==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:xYewpGV4TcEkkycNx2WI2eBkkMp9TYfpEGZxNyeVT8Ifi2Y=,iv:EgmpVOamGsBOinV/ecvXvU/veE9aBGjPHcHBaMBZZ2I=,tag:VaMnhDqU3L79TplB2aSj8g==,type:str]
    #ENC[AES256_GCM,data:b/GE05r0K9Lv01zVfqHC1CeSUFHJzl5q,iv:ObjfpSvnLuTPbJlvLkJ3jD7sDHpZQ4kweQkxjYKlkDQ=,tag:Kyq7jydGTq7+QPy6iYHNww==,type:comment]
    OPENID_CLIENT_ID: ENC[AES256_GCM,data:+huo2+KUzpqXIWClYZZ3Xs3bHtNx+qLA6gVIYNzcLgUtpt/Kqbq+AXCHFD/rGZU1fFkbqZxxMkjCaoy05kh/Rw==,iv:dhcUlKoa2uqlUJ0hjLBkYA+h5Cqn+eMrktVTywwB8dg=,tag:U7cS2bY8g7R0GoO/U04KyQ==,type:str]
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:Wu/xIkPkS0Ss88gcQMMgiWWBGQSWVqYnL5fsfr16G3jH4QgH/ZtjfTtKe06od8sHhpr8I/BrX0B5nWdaa28KEg==,iv:Av8uKvWseeFUxzj3mj0t/XpRj9RhVi2o0YEiOYGjqWo=,tag:9iCVBVQF107+e8wyFEx8tw==,type:str]
    OPENID_AUTHORIZATION_URL: ENC[AES256_GCM,data:ojdye9H9bH+LAXknW+B2aadgdOrvZbe0WBjqfHXmmMofRYU9Rg5uhFCESBM0fELUNbe6Z9WoS8tL8Mos03PQuh7lB6B9Oh8u8XrXgHcDT9RZr+if+DEgT3DiBHXN6rK4zIErefDPCXnYOWqWKjzL/PlIe3EJCsSWi4LpCO+tkNCz0bjOr9JXEHHdygz7,iv:VvOpEyqk6IgwyxTbHDnj7uwK1AslgMjJGUsEaQ/SWkU=,tag:9mtth5/JuUCE9FPhGLBrWA==,type:str]
    OPENID_ISSUER: ENC[AES256_GCM,data:F1Gz848TWAnfUghdrZI/QrjeqKon5rUa0ap/eaPDZCW32VNeMR8NGzWv/QOHw0g2q7h+Cxv2cSxEr+uC42fX4nNlYErrc+P+oHlXny2nQ3RjewgqyFx4cnrujTWy3RP7qJrdpjwetO0Dgp6IrBpc3ecBRukUihCGu3cyuf7gQQ==,iv:Xqmd6m5nmZNWswBaC2ZsOstNm+ZwPv+CJcsMdLXmRN0=,tag:/bvGqGijTodKQeg6323mZQ==,type:str]
    OPENID_TOKEN_URL: ENC[AES256_GCM,data:wQ1NbH37/kTl5cahTD7pSQ3Doje9tNufyhSzGRJLd/5M4Hqn3m7dvqrl73yD/cYZNB3L/6Pki2VRuwrN+sLc8eVgZB9wxM2tbIEM4UcgThuZJPZtQm/Wje6g8b8W+mQZXKjCZlqHZtkw4rS6HLCa4sZE2Snh2NbfQiLgid5XYa5Sa72Zmg==,iv:kNv1nLYuiERxerYoOfnmF+pTr7z9p5iHycZ4x2E64sE=,tag:iqhpp8gHzL7+TwkhEr+F0g==,type:str]
    OPENID_USER_INFO_URL: ENC[AES256_GCM,data:YJhw7FVoX+UDx0EHYn0Pi984FizcUYl5FYXwdDldS7nlfMuTZro0mLKAjZOKHU86gfZCXz5VcG9nbC393mhEax+QDChUf2ecdN7xxePXMuZ1qejBFJv+vo4GL1O/X+7V3w0lydCbebaZkBzi4Z+N1i/FawzriihBFgy7XG+/LiHr8WMR9a0Dzw==,iv:JoteOiYsJ18udRp3kXFMinH6BnxjXunHqOKppmP7G54=,tag:mtg14Z8uPDfgPyWhntHAEg==,type:str]
    OPENID_SCOPE: ENC[AES256_GCM,data:z9E/WGIHY2gCFv/ClxXf5QUhi9Y=,iv:y6azlbRboo6hbUsj1vlaiRGKpNZqXk+E2lKmtuHim0w=,tag:wi+REGF9ktJFRw5jSyIv0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOWFOMmJqRWNVck85K05x
            S3NEU3V1QTN6elhvNzV1YkxtZ0QrMXJ4Y3g4CjhHOXJteXB5YXA3U05BMUpmbXBk
            RG54bUtKZU1sM2NCWXJOYjhZUk1oelkKLS0tIDVxbDBlQ3NnbzI1L0E2MVRRRWk0
            NHJKZzdTT1dxOUR1OXNKUlc2ZzZ4THcKBV1v203l1ElQQRni0racSt3CmHmGf9oO
            jT8NGnkMrt4R/mpXKo5tCnrKadrJpSdS1OkUYW+RUIYMbyWd6wzwoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T12:04:33Z"
    mac: ENC[AES256_GCM,data:DtQDZ0LmAqpv0rvJODxdVStq+M1rLrZT9ojgqgdAdT8LaZ16mOCyCIOn2aCHCmC4vSH9B1Ue9iHywgIotuw4tjM9ROFNedCoHUmc6Xa63Y95s/F9qbgkN84YYTq+OMI7NNaL9vyZzmTn/GPWnqsjW46ZFglo3bsyYQ8oFSBzQKg=,iv:3VOZYVIafVt9OjWfII2wfXoJJVVeQE5Vo/0ReGEHpag=,tag:v+e7OVYNxEyx93ap7Xobaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
