# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: reactiveresume
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:A/IgeSZs4FP1j/y/9CVylctGdnR7fBY=,iv:KFRsmWP2bcBusl14OmzJZ3rPTeLAqcWN4fS+evpXrSc=,tag:HPwkpv2sZ3L7Q6rc0g9E2g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:/tQZTTVfQqYUVSQPMA+iteprskFEew==,iv:4T3P5U7kpjPvrBTUGvSMbEs3Q3hJoICa2m4OLmriZoY=,tag:JOQCuQTkg9g4P2XWyd5OHg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:UCaa+BDmNDF5PcA9dh1CseZKAYbfv6c=,iv:SDtZv8Q3614prTyWm2mI657tayYsm26C7E6xUPjX0eg=,tag:zou7SMORF5bJexM88nqzPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUlJDWVZtc2NTK3NzZjZq
            U1JCUFR3cWJJRXhKOHRyaGZyQzhOT1BBV3hrCnpwSWpjTjBabzN5d0VnT2VGSTZ1
            bkR5T0t4ZXR6czNMb0VjT1pNalJKMlUKLS0tIFI4NXA1ZGtmNUhqbVZoalhCUjdT
            YzhWWmhvS3JEN1V3Tm5JV1BIWVl2Q1EKNoieqjfgrhfhwyr6QO5dQFwUQu6hWCWT
            DwB5YQcMuVLWpE7AGThHXNG58HLk36aPbNFochjtzLnNX5jjXcn0UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:43:31Z"
    mac: ENC[AES256_GCM,data:do/rOJHdZrnxI/Ji3eZVZtj7I9t/hBfZBJ2r5wVi+Uz7ZAlQlwjX3CDvzvTz3yNYLAG3/92iwrV/sUDCvYlvumqwzbht3OsfKAuR9bTpw+Fm5Gzebdh0zHgz1Dbt83zR5FuL7X+gDX8L5S6LbTLRbsBGXB/9U0DtS4BODWVWQmg=,iv:dfWYKlXczoc2ElbCuvbafqTflqGR0j7Evgq9QD3AuOc=,tag:6rvL9DCV7PDzaVHyawgQfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# App Secrets
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: reactiveresume
type: Opaque
stringData:
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:ZBnbRm+GRCplHKrmoAmL9UtUO+stXeM=,iv:I4qbX50pB7tx6hAZ6VQjASrlleSVW46bsqtdMFWXlC8=,tag:XjezPRhtDMhy8WEIb7u/Gw==,type:str]
    REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:wj5lTnBYWySbUY+3p4U3HF/Ig9cAl2w=,iv:aq7RiWS08WrnnYUO3i8MjjrBeVoIutarjwCOw93lRBo=,tag:l0dFPpx3JbD4ogrGL4TlbA==,type:str]
    CHROME_TOKEN: ENC[AES256_GCM,data:goZxObnS7tF6E21DETfHCpZCEw==,iv:Sgljk0iGbwTfPCb6BmC5wwgLtAbKcpQslFVcJHGsPTo=,tag:uu+S6M/dtEAc2VahD1lZsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUlJDWVZtc2NTK3NzZjZq
            U1JCUFR3cWJJRXhKOHRyaGZyQzhOT1BBV3hrCnpwSWpjTjBabzN5d0VnT2VGSTZ1
            bkR5T0t4ZXR6czNMb0VjT1pNalJKMlUKLS0tIFI4NXA1ZGtmNUhqbVZoalhCUjdT
            YzhWWmhvS3JEN1V3Tm5JV1BIWVl2Q1EKNoieqjfgrhfhwyr6QO5dQFwUQu6hWCWT
            DwB5YQcMuVLWpE7AGThHXNG58HLk36aPbNFochjtzLnNX5jjXcn0UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:43:31Z"
    mac: ENC[AES256_GCM,data:do/rOJHdZrnxI/Ji3eZVZtj7I9t/hBfZBJ2r5wVi+Uz7ZAlQlwjX3CDvzvTz3yNYLAG3/92iwrV/sUDCvYlvumqwzbht3OsfKAuR9bTpw+Fm5Gzebdh0zHgz1Dbt83zR5FuL7X+gDX8L5S6LbTLRbsBGXB/9U0DtS4BODWVWQmg=,iv:dfWYKlXczoc2ElbCuvbafqTflqGR0j7Evgq9QD3AuOc=,tag:6rvL9DCV7PDzaVHyawgQfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# MinIO Secret
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: reactiveresume
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:awVtB8ctikQKqJbMIjetqJ0=,iv:ileqRsiZskoVyX+Yg15UMIgChgjeSa69+/zpT48ZzJQ=,tag:H4DJnVM6zIQPCNY/9G2G5w==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:OOzjM6tMYra1l2DlpyJaQO6Gdw==,iv:CWQHXmd0jnd9tvftXWDLquiS+Cj05GLYIs0pFdUtFQU=,tag:txNhqKHYcOVVSZrfdotheg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUlJDWVZtc2NTK3NzZjZq
            U1JCUFR3cWJJRXhKOHRyaGZyQzhOT1BBV3hrCnpwSWpjTjBabzN5d0VnT2VGSTZ1
            bkR5T0t4ZXR6czNMb0VjT1pNalJKMlUKLS0tIFI4NXA1ZGtmNUhqbVZoalhCUjdT
            YzhWWmhvS3JEN1V3Tm5JV1BIWVl2Q1EKNoieqjfgrhfhwyr6QO5dQFwUQu6hWCWT
            DwB5YQcMuVLWpE7AGThHXNG58HLk36aPbNFochjtzLnNX5jjXcn0UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:43:31Z"
    mac: ENC[AES256_GCM,data:do/rOJHdZrnxI/Ji3eZVZtj7I9t/hBfZBJ2r5wVi+Uz7ZAlQlwjX3CDvzvTz3yNYLAG3/92iwrV/sUDCvYlvumqwzbht3OsfKAuR9bTpw+Fm5Gzebdh0zHgz1Dbt83zR5FuL7X+gDX8L5S6LbTLRbsBGXB/9U0DtS4BODWVWQmg=,iv:dfWYKlXczoc2ElbCuvbafqTflqGR0j7Evgq9QD3AuOc=,tag:6rvL9DCV7PDzaVHyawgQfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
