# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: reactiveresume
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:VsTiwVomp12s9P5uzH2cRk+ABahlSQg=,iv:pBofbOOYEkb+dqH12S1GLUx2tthn4P8u+JgykqQhk3g=,tag:YwAMpj2Pm+EbGbJzJG+jAQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:p4al9TbjK/SVFjX8kp+/WomjkUWVyQ==,iv:11FD+jWbh6yEIP+JyPrXgsdZ67cJkT/gRCcUgAtJmtA=,tag:lVAjCppAizZ7rYswFnbcOg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:MgLEF/fuqVmiauRcs1Y9GDxjJDmYABM=,iv:h81HNqqsIehEiT5P8CjaP2j8kxXrbq64qsbSu4KJ2iU=,tag:urVoyUaUssMv89FGLTQhtQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:vLxy9EOgmCbx3/ucwt6gtwJhz9ZCCzZJahQZ7/xy13E5u84GmX2HrEuPSu+TgVCk7QwVlsp5Itg8XAdXu+LfQRe73MYp3OWe7c5lypb4OuKvrEhgCoTE5wUIkn7ACvenMQ==,iv:LhCOhrql7VdiRfuklZWHSakYbz9fWCAFnb0+b2NBke0=,tag:E8EJuAdAsP6r+MX3iuzzmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVGlKSkVkY1hQUENpOWVN
            aFFGY0hCbmFHbEllZkY5ZDVRdDZVQmFweEVNCmNTNEtZbnVWQ3M5aGlmeWhwK0Fz
            Q01JKzRLSzVMeTNNUGx6S3JqcHU0eDAKLS0tIGo4L1pIbk1GdnQyZ1pkWXVmOVpX
            YjBBSGtBbE1qSGJrRUREVVI4QUFCWmcKGpesTOrNx9Rhl0nVJ6s0U5CTgaRMvJf8
            PjVsEZKltdL+7OWRlTjqhqhsDIW2at1I1cCeD11CYKfcF0tAToP9Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:17:45Z"
    mac: ENC[AES256_GCM,data:VDyp6LJk8rG/nY+WsaJKNU2DoQArxuGz+UXUD4FHnvo4nP8Zm9nYivexJmQHMhKiMn/OEVXX8PvC9lxDFkelZw9cv/19UGTZznRIvZB2crC9F49q3hT5Ejeu5LLW+ymWa30qfoSiwY1ooZF5dTeuFXde/ng2/MqPWlfwln3fzZI=,iv:k5VU7tsWXJ4BV7SFbE+dcTc4HG4xER8nGN6FthvhTAY=,tag:ZlRN1gwudhS1JsHvNYW3oQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# MinIO Secret
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: reactiveresume
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:w4CowBOTC+p+KvVGBC1Vgn8=,iv:C/vVX67q65X8eAqwYtkadAN3pTQ8S4PRGgS4lHjbsC8=,tag:DhiPQtiS1iO1fL+4qTG2RQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:87mdrTksYF2kBW1/9QEciFxvYQ==,iv://eWSD9RtIGgsXKVxe715tP9dZxQ/UuO2exepOTnhEA=,tag:evGCoqbQSY+VZA2cSqiXzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVGlKSkVkY1hQUENpOWVN
            aFFGY0hCbmFHbEllZkY5ZDVRdDZVQmFweEVNCmNTNEtZbnVWQ3M5aGlmeWhwK0Fz
            Q01JKzRLSzVMeTNNUGx6S3JqcHU0eDAKLS0tIGo4L1pIbk1GdnQyZ1pkWXVmOVpX
            YjBBSGtBbE1qSGJrRUREVVI4QUFCWmcKGpesTOrNx9Rhl0nVJ6s0U5CTgaRMvJf8
            PjVsEZKltdL+7OWRlTjqhqhsDIW2at1I1cCeD11CYKfcF0tAToP9Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:17:45Z"
    mac: ENC[AES256_GCM,data:VDyp6LJk8rG/nY+WsaJKNU2DoQArxuGz+UXUD4FHnvo4nP8Zm9nYivexJmQHMhKiMn/OEVXX8PvC9lxDFkelZw9cv/19UGTZznRIvZB2crC9F49q3hT5Ejeu5LLW+ymWa30qfoSiwY1ooZF5dTeuFXde/ng2/MqPWlfwln3fzZI=,iv:k5VU7tsWXJ4BV7SFbE+dcTc4HG4xER8nGN6FthvhTAY=,tag:ZlRN1gwudhS1JsHvNYW3oQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# App Secrets
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: reactiveresume
type: Opaque
stringData:
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:RogxNV3HSZHppV5uXdzNjYF53YyEalg=,iv:OnWjaEmErYqm9uWsArPrNPSj+qLIDLqRWVMXY7RW/QY=,tag:/Hp9OFwydZSYxYT6sRQABg==,type:str]
    REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:HWJFOuJhat8HKxUicSgD9wTFBzDDBNI=,iv:ncP6TL4U0v/aoDyABnBlOi4v2puUWVADPIIgVpvTjIg=,tag:jGXd3i6DnX0Co+5Zua5Xbg==,type:str]
    CHROME_TOKEN: ENC[AES256_GCM,data:wH44uzBettfQCIBFXhD4QTYpSg==,iv:puDsCBJj7C79j+O1k1V90pD2NTxuCKiH7mf2a8B3++8=,tag:hCXqrWvu/PK8iILjCILXug==,type:str]
    #ENC[AES256_GCM,data:sSzz6hFqEHyaUeZzJSnexSPomw2Tl5Zc,iv:QuYA5sQsWiOxeYWdwT3kWpepCCNSx9T0ATzuJ62N18U=,tag:GlYdoyONSrMCCCF5hIFOxQ==,type:comment]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:Q2AMnmkLQ7k5koh6L6zYBGp4McA=,iv:TB4yFDHAgQWNgzeaU0avIJZ0tvIJSclSGpjGD16dXKg=,tag:v97QAeb23ErflMPqmmJATQ==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:XST6EWkleHAp4BcNfWu1wI+XnjvYASOSKCfmL3/dWg4QCUCXyP9WEw==,iv:UezAZ73jiVvYkWa2LFdzWwMSY5uS9+gEyc9MYhI2lgU=,tag:Hv88VsVuLOS7S+3fWeAznA==,type:str]
    #ENC[AES256_GCM,data:Y7JNYyq2xwRhx911kcXNp767fL5swsya,iv:U3uSsnCCbYqwunGYYby02eKAXt4xczNCz/izlrFVAhk=,tag:HL/Qf7DxC7xMMzIbuOlgig==,type:comment]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:mZiKymN2SpzWAnYgQEoJYfjalSb222pza7ZcAjYrc4CyT2+mDJnugkmMZ3M2qEKqJsHn4gYqNUHE5J6JwSUqoUlW1HAuLxd3,iv:NOfTSofw1/Z6vBRsPh2tJ0SDSsbNjRB7uaiiNgAy1hk=,tag:K0aq5NnB4a4XNIyIq5JGIg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:Xd/SP2MMs56XbGt9zTrGClYUwOJ+QQv9ubG5cEh0894fktk=,iv:aO+T9d4ul00qOADn8y4upTZrFdzlGBzcc00/NNO1Cmo=,tag:IOYuIn4ihEUuGvfkU7n/8w==,type:str]
# -- OpenID (Optional) --
#VITE_OPENID_NAME: OpenID
#OPENID_AUTHORIZATION_URL:
#OPENID_CALLBACK_URL: http:/localhost:3000/#api/auth/openid/callback
#OPENID_CLIENT_ID:
#OPENID_CLIENT_SECRET:
#OPENID_ISSUER:
#OPENID_SCOPE: openid profile email
#OPENID_TOKEN_URL:
#OPENID_USER_INFO_URL:
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVGlKSkVkY1hQUENpOWVN
            aFFGY0hCbmFHbEllZkY5ZDVRdDZVQmFweEVNCmNTNEtZbnVWQ3M5aGlmeWhwK0Fz
            Q01JKzRLSzVMeTNNUGx6S3JqcHU0eDAKLS0tIGo4L1pIbk1GdnQyZ1pkWXVmOVpX
            YjBBSGtBbE1qSGJrRUREVVI4QUFCWmcKGpesTOrNx9Rhl0nVJ6s0U5CTgaRMvJf8
            PjVsEZKltdL+7OWRlTjqhqhsDIW2at1I1cCeD11CYKfcF0tAToP9Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:17:45Z"
    mac: ENC[AES256_GCM,data:VDyp6LJk8rG/nY+WsaJKNU2DoQArxuGz+UXUD4FHnvo4nP8Zm9nYivexJmQHMhKiMn/OEVXX8PvC9lxDFkelZw9cv/19UGTZznRIvZB2crC9F49q3hT5Ejeu5LLW+ymWa30qfoSiwY1ooZF5dTeuFXde/ng2/MqPWlfwln3fzZI=,iv:k5VU7tsWXJ4BV7SFbE+dcTc4HG4xER8nGN6FthvhTAY=,tag:ZlRN1gwudhS1JsHvNYW3oQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
