# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: reactiveresume
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:6vEO7xGw/+x56ucVvuxfqw5gLKTScJI=,iv:JVijPmj2gRYSSUOwI1W2S58d0L1O/zM1sh6XknzvnOc=,tag:2vUhUannlVKXmoXJA2PV1w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Kd7LhxbQwA3GZeACQdszno+Xdz6ztg==,iv:3ZNVYrboGr3AC8ZT5KRdNVRsQwPtyM47ntX6MzTflFA=,tag:INxb5e7Vi8BL+ZZrwxkH6w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:nKDuHHFjHYNKSVOq2qtX9lEN6iAITQA=,iv:rMLvYUKd48UUVnMbnS6D3GpHOs6XbrAE2cuqMf2xuBc=,tag:prODXAN6FVg+LmQk8XN/Qg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:bFjrLlqHuJb09yL4l1uQoAB62rw0YqnkzKXUIH+AfArtRq5mFfx9HYSiR2ypNLZHpb8rsj+9Uc/XgkEZvwqUECrAv2mFTUEDe6iYJErcr6JdL8DbkSX1RuxN86RZsI0lbg==,iv:xgTbyHvDnC/wMRzs9XUS6mWDN5UBC4Z86kSd3tXIT+w=,tag:wzurqaBLGPTy+09rskTK7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Vk9iZllXNUxPc2RLTGlY
            RFFBSnI4QXhqTlBQbDJSOG9VRFVDa2tlT0hjCkN1VTBUUXZ6dzd2Rm9COGZDYnNX
            Q0FmQWxkcTQxMkVocjUvWm5pUG1SV3MKLS0tIHM5WHIzdUhQZTg0M2hnNmdKMUZm
            UjltL29tREVPUVJCSDl6Y2VpU1RkYVkK4S2mvmasvrs7JNWfb5pRes+l+JTCeoVU
            dsgj+VGlMU18Zufl/7Yv3hcSBcYxpDr4yBz+LQsz2TFwkr63wFSInw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:10:57Z"
    mac: ENC[AES256_GCM,data:c8vGdI7UpqNEAcg2iLo6KKT/s5SSkJD9yBxGsK/aWYpgGgrfjMbS0Rrqat1eCAVn4fzgQpiXhmqKv85nsIgz6a4cV7aSTKPYwi+inaEB2Y311IzfIucP7QuyFAxtKKJdLOkGjiU3eL58WrbadA6QxZWp2NmceVcnu6yNg7YQONE=,iv:424JOSgktVge2sY7kM76bSK9yHVEKL12s6QVvWDu1yA=,tag:3FVSXGQo7N2swiCHUReIWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# MinIO Secret
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: reactiveresume
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:RcZ9vtIt+Yjsl0fmgFOWXX4=,iv:iRSzKWPFFZKLJLz8bqkxrPr42m9/6Ab6PEAP625Ygys=,tag:0Y78GDeAhvV5acmnHi1AyA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:qvedBGevFZSPDVQf8j+cgxZQQw==,iv:POEREnY8tdap6ugEsEUymXt09M08Oi6sDi3HkVH3Qw8=,tag:TD+qSJG0Xl7zZXcPe/7q4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Vk9iZllXNUxPc2RLTGlY
            RFFBSnI4QXhqTlBQbDJSOG9VRFVDa2tlT0hjCkN1VTBUUXZ6dzd2Rm9COGZDYnNX
            Q0FmQWxkcTQxMkVocjUvWm5pUG1SV3MKLS0tIHM5WHIzdUhQZTg0M2hnNmdKMUZm
            UjltL29tREVPUVJCSDl6Y2VpU1RkYVkK4S2mvmasvrs7JNWfb5pRes+l+JTCeoVU
            dsgj+VGlMU18Zufl/7Yv3hcSBcYxpDr4yBz+LQsz2TFwkr63wFSInw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:10:57Z"
    mac: ENC[AES256_GCM,data:c8vGdI7UpqNEAcg2iLo6KKT/s5SSkJD9yBxGsK/aWYpgGgrfjMbS0Rrqat1eCAVn4fzgQpiXhmqKv85nsIgz6a4cV7aSTKPYwi+inaEB2Y311IzfIucP7QuyFAxtKKJdLOkGjiU3eL58WrbadA6QxZWp2NmceVcnu6yNg7YQONE=,iv:424JOSgktVge2sY7kM76bSK9yHVEKL12s6QVvWDu1yA=,tag:3FVSXGQo7N2swiCHUReIWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# App Secrets
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: reactiveresume
type: Opaque
stringData:
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:P89TH6S2RFIApU92c/4Apr5KmCiUdWI=,iv:O4BQKBCzNH9Ef2r11YlsW+SFwJBDOAoJtT8hG1vjS+A=,tag:ugyVGP5SXcnttG0K6nxnfw==,type:str]
    REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:4rcnhmCH2/K03z7EIN2c2kQOdR0dH1E=,iv:6cvtJ2+8D6fnfAWJu5sCSprWLCywMw89uoEupyryL7o=,tag:6ie7o+r4joZpZoJ9oGhsVQ==,type:str]
    CHROME_TOKEN: ENC[AES256_GCM,data:OjyvrjlgS7+iYXJWlRx5+66aig==,iv:w+zbbTuMnQFoIONEjnsMAw+Sp3fxAMwspeGdSiKFVS8=,tag:21GR27+mpv5flxMmmq9PoQ==,type:str]
    #ENC[AES256_GCM,data:ylM454DEMnViRKUrcWI/i0l71RpgTjir,iv:Hbsxb+RahZs50JUOKYitkDH68ieE68h4Cf+BGaJUA44=,tag:1JTF07+H7oz28OwiQqplNQ==,type:comment]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:rAZARto3BFvSHtvalYuFKkdlaYs=,iv:7fqEq25rSc6YOhgR+1FnGr0h1CQzUIhaTyKfRbdtjZ4=,tag:jGmdrH8WTFuGkiMVkJ1g1w==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:lHfQXM0duGljqgfRLxvzvk+u0qeplWYcpxMKQaiBhaEvUoVCVCtBzg==,iv:FXrolA6CkQpL1pMB3ajOf1BylOsgGVq4/8KH9U4vw9U=,tag:4gIVa4w/o+Dawu9pvX/MCw==,type:str]
# -- Google (Optional) --
#GOOGLE_CLIENT_ID: google_client_id
#GOOGLE_CLIENT_SECRET:google_client_secret
#GOOGLE_CALLBACK_URL: http:/localhost:3000/api/auth/google/callback
# -- OpenID (Optional) --
#VITE_OPENID_NAME: OpenID
#OPENID_AUTHORIZATION_URL:
#OPENID_CALLBACK_URL: http:/localhost:3000/#api/auth/openid/callback
#OPENID_CLIENT_ID:
#OPENID_CLIENT_SECRET:
#OPENID_ISSUER:
#OPENID_SCOPE: openid profile email
#OPENID_TOKEN_URL:
#OPENID_USER_INFO_URL:
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Vk9iZllXNUxPc2RLTGlY
            RFFBSnI4QXhqTlBQbDJSOG9VRFVDa2tlT0hjCkN1VTBUUXZ6dzd2Rm9COGZDYnNX
            Q0FmQWxkcTQxMkVocjUvWm5pUG1SV3MKLS0tIHM5WHIzdUhQZTg0M2hnNmdKMUZm
            UjltL29tREVPUVJCSDl6Y2VpU1RkYVkK4S2mvmasvrs7JNWfb5pRes+l+JTCeoVU
            dsgj+VGlMU18Zufl/7Yv3hcSBcYxpDr4yBz+LQsz2TFwkr63wFSInw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:10:57Z"
    mac: ENC[AES256_GCM,data:c8vGdI7UpqNEAcg2iLo6KKT/s5SSkJD9yBxGsK/aWYpgGgrfjMbS0Rrqat1eCAVn4fzgQpiXhmqKv85nsIgz6a4cV7aSTKPYwi+inaEB2Y311IzfIucP7QuyFAxtKKJdLOkGjiU3eL58WrbadA6QxZWp2NmceVcnu6yNg7YQONE=,iv:424JOSgktVge2sY7kM76bSK9yHVEKL12s6QVvWDu1yA=,tag:3FVSXGQo7N2swiCHUReIWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
