# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: reactiveresume
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:xQcl768qkLI64mUopBOftH5LxhzH6IM=,iv:5/vfi8Imu5NEnfUqSZIQRy1J2BJcaFa5IFvDmBofmj8=,tag:b8eS6/YEtcxREsnvib/fAg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:p3gZDD4g8TYr4pZKb5yHYIkwld2ZSA==,iv:yh/yHPmvUx7vK9yxVQkpUPYrePTCeg5X9dMBiQqVNcg=,tag:TQv71DDdsq8kGaWbow0d0g==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:cJzDNrvdA0Zm/hklWPX6x/Bof3wlI1E=,iv:+e/yyb9iAnrw+RzMrdwoJPnMap+5zDw4SzRBjtJ6vhs=,tag:OlPt7OpR7a8O65VAFihcLw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:5lC1Yx8JxtyICkBNMR+VoNFsMcUzbHf6vq92pWVtmfalsSG/LERDUbD7H1D9XGpQGtlj8HHRF4PXCExL9I6JPXL3yOndfXYLPzH2JWJk+1uG+FYfokpWbnpf2MCF3JTDZw==,iv:2Jv1ZPBGioEKzb3H7JFQxd+9L9kuTQiZQVKzbu2/z1Y=,tag:WpbAwFsJHs6SwM0muU1eYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURkxsOHVoRTdHanVTY0ty
            bXprS3lZZlJTU2trYjZuR1gzWmtSSHQyb25FCnNwWGc0RTVva09tZ216MTFXQUR4
            ZEdQMktvcUNkYXhreVU2MUIvYXZVb1UKLS0tIE9mSDdIMlVydk51T1BndVJCdlM4
            VTJOWHB4QWZGenJtdFRwOUdDSmdpblkKPPeLGjalKmCd/mXhBciqE72xe+PypeQl
            U5lP24a1rvmfx08Q6IpfVUXbW8f8L2EVYkhBVmE4zj2FP79E+baWpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:58:44Z"
    mac: ENC[AES256_GCM,data:ljV6Xtm+kqbU+Af7OxoK2c5WGVvqzWwUa1fgEP31akesBlteF7Lt9r+TD8eSUuCaldigkE03qmO3cWwI64pQNVsQBHILMin70w40cQKJccYt1gls7lYNSq2dXwOquXZlxDn0TjuQptGemvjLNCbBFQGlWF9RziCA2LVOnayo2DY=,iv:i+oRl9iVye8eMg25oHjQ8TQChWnEN5CvtKQhebBYkAU=,tag:2/9QTSwxMvUQIZMfZieb+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# App Secrets
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: reactiveresume
type: Opaque
stringData:
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:+Xpgwxdalc7ccenUqsLiCctKgP/IHCU=,iv:2Fx+rMRo2uBqheMLRqIzZJuHLui0DmJuNQj3ZNzpPEU=,tag:zQ0vuMMZG1tK+ZU12GEpKA==,type:str]
    REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:zf//1DGPzoU9RHrl8Rfd/+MEAz/xmSk=,iv:/n/FmAm80gRQdjCjJPqcwILoVZY9ceEYeskzRQo4tjI=,tag:7rczDRBCdiiOmc7wicyMfA==,type:str]
    CHROME_TOKEN: ENC[AES256_GCM,data:k8weZz/eX9ABxGE0riE/rfmldQ==,iv:MgNyzSI7NVK5gNUsfwvbmSfyMp0EDodfUAudb0gX49A=,tag:zfajixaSnEWJ4FXiFe67Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURkxsOHVoRTdHanVTY0ty
            bXprS3lZZlJTU2trYjZuR1gzWmtSSHQyb25FCnNwWGc0RTVva09tZ216MTFXQUR4
            ZEdQMktvcUNkYXhreVU2MUIvYXZVb1UKLS0tIE9mSDdIMlVydk51T1BndVJCdlM4
            VTJOWHB4QWZGenJtdFRwOUdDSmdpblkKPPeLGjalKmCd/mXhBciqE72xe+PypeQl
            U5lP24a1rvmfx08Q6IpfVUXbW8f8L2EVYkhBVmE4zj2FP79E+baWpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:58:44Z"
    mac: ENC[AES256_GCM,data:ljV6Xtm+kqbU+Af7OxoK2c5WGVvqzWwUa1fgEP31akesBlteF7Lt9r+TD8eSUuCaldigkE03qmO3cWwI64pQNVsQBHILMin70w40cQKJccYt1gls7lYNSq2dXwOquXZlxDn0TjuQptGemvjLNCbBFQGlWF9RziCA2LVOnayo2DY=,iv:i+oRl9iVye8eMg25oHjQ8TQChWnEN5CvtKQhebBYkAU=,tag:2/9QTSwxMvUQIZMfZieb+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# MinIO Secret
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: reactiveresume
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:a4d9dqRA8dYit8FGmf47SNo=,iv:1Ld/dp+HAipq+hUGqZ0tEXapGMHvl9SaIm2xTiV/pgU=,tag:MZ4DOy/1mLKD5bPJMVF82A==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:nSxrVAH1hCZ8wp6Bim3NCuAGWw==,iv:/4vsu7lvlWEoxSsLryeqN2jhy9YkhlMfZbBecQQ/j1U=,tag:erIHWx1FA+hikzLyqZHXUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURkxsOHVoRTdHanVTY0ty
            bXprS3lZZlJTU2trYjZuR1gzWmtSSHQyb25FCnNwWGc0RTVva09tZ216MTFXQUR4
            ZEdQMktvcUNkYXhreVU2MUIvYXZVb1UKLS0tIE9mSDdIMlVydk51T1BndVJCdlM4
            VTJOWHB4QWZGenJtdFRwOUdDSmdpblkKPPeLGjalKmCd/mXhBciqE72xe+PypeQl
            U5lP24a1rvmfx08Q6IpfVUXbW8f8L2EVYkhBVmE4zj2FP79E+baWpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T10:58:44Z"
    mac: ENC[AES256_GCM,data:ljV6Xtm+kqbU+Af7OxoK2c5WGVvqzWwUa1fgEP31akesBlteF7Lt9r+TD8eSUuCaldigkE03qmO3cWwI64pQNVsQBHILMin70w40cQKJccYt1gls7lYNSq2dXwOquXZlxDn0TjuQptGemvjLNCbBFQGlWF9RziCA2LVOnayo2DY=,iv:i+oRl9iVye8eMg25oHjQ8TQChWnEN5CvtKQhebBYkAU=,tag:2/9QTSwxMvUQIZMfZieb+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
