# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: reactiveresume
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:65VnJf1PwFRX7UMXxSNKEdBuHoGOo7M=,iv:Oqewtg50NEyu8ONFQ4LkahGn2n4CrVEWBdAONTaXelQ=,tag:D6kAmI2Z6DLiFAMiX16xFw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:QWEksEtzkvkI0QiiqRRMVGsx5+rZuA==,iv:rzxt5kDdZswoAyqKOJbQuf7gRKMnZCznJHFXxCdjezk=,tag:z8sYQ5F5M33ofVvqjpPcqQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:fI/1p1bPjsG9K6A6zQVPlxcf740aH0M=,iv:siLfHMjcjkQt3DwvVIDxEArcGjF13ZsA918ex9vcsI0=,tag:80G9MTj/6xYqzpOdOKHSRg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:O1l6mHIxlBJcw0XknxLG0KA2Q1IVewAj9L4ul6FeuLmMaemiszIYxfosKmjmLXIUH0L3rXPUCXRSVFc9ywqU7/FlbU77wnhPxwCgKidpQCTrkQYuo+ZTbg4ToxqmnYVMVA==,iv:ULBR1jGZqCEQyn0lRR9+WHKgg6GOKxyk0mHAS3eFjqI=,tag:eRMMAomM1MxwKXPJUgqUjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVlZieTdIZkhTK2JXbWtL
            RFRxaXNMRnZNS1hqZktkc2ZFQ2VLUk1RVzFFCmhjRG1nYW1EeGFGUURSOXpPdXh4
            VUwrajFjMndHNDNRbjlUOXJ4ZlN0cnMKLS0tIEhNZitsd1k5eTdzR3ZIL0hnQnIx
            QUVHRnUzRHl6aUhKWTBXSzJpSmhLQWMK+rN9fI95jqz1IpVa1sBKfPAgSc9L7riX
            XVHV+/ALd5ujFl/l35giXryuH+3qPw0OdjXGfaKcwfxA9rbJm6RJ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:40:23Z"
    mac: ENC[AES256_GCM,data:Vykn+HfDMdenLNL2HHPOayBTmL/x3cB1tCgNWwxww8zUibbuEwlSf0hoZOMLs+yVKlpmhTQpWkfzhNJX2W7dJlje60cT7F/EpzqwJCW8HpQOwf3rdRhTiMoGsK2jQZOETPVkELeS/kNkP9lsMMXGz5b1m9+wpywBvl/lsZyLHHs=,iv:InWphtbclejmXcGWM+b4W0X4k1xgcFB1yZI0hTe1Ea0=,tag:ibBFBuTtMT94j2yAX/Mpzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# MinIO Secret
apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: reactiveresume
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:SlrTaJAdLocpMX7fJfC+CP8=,iv:oegkiREbQ4lrvAMLc5IjCIpnXaZV7/mUllr5dURqRb8=,tag:MHaisrnxlr4ZWgdzhoIqZg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:Z7ASiR19PCbwREC/X7Tn7ed7gQ==,iv:I0lkkdcsyEOW+VG/Wfhdkdtsxiq6DyfCW9vBEPfVCvA=,tag:S6RSQm2KEA5quqGswORdeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVlZieTdIZkhTK2JXbWtL
            RFRxaXNMRnZNS1hqZktkc2ZFQ2VLUk1RVzFFCmhjRG1nYW1EeGFGUURSOXpPdXh4
            VUwrajFjMndHNDNRbjlUOXJ4ZlN0cnMKLS0tIEhNZitsd1k5eTdzR3ZIL0hnQnIx
            QUVHRnUzRHl6aUhKWTBXSzJpSmhLQWMK+rN9fI95jqz1IpVa1sBKfPAgSc9L7riX
            XVHV+/ALd5ujFl/l35giXryuH+3qPw0OdjXGfaKcwfxA9rbJm6RJ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:40:23Z"
    mac: ENC[AES256_GCM,data:Vykn+HfDMdenLNL2HHPOayBTmL/x3cB1tCgNWwxww8zUibbuEwlSf0hoZOMLs+yVKlpmhTQpWkfzhNJX2W7dJlje60cT7F/EpzqwJCW8HpQOwf3rdRhTiMoGsK2jQZOETPVkELeS/kNkP9lsMMXGz5b1m9+wpywBvl/lsZyLHHs=,iv:InWphtbclejmXcGWM+b4W0X4k1xgcFB1yZI0hTe1Ea0=,tag:ibBFBuTtMT94j2yAX/Mpzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# App Secrets
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: reactiveresume
type: Opaque
stringData:
    ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:q/4O1KacMJ2txPvfEEl4mND04HaflCw=,iv:YjrJHAxExoyCY7q00NzkzPuBNJN8uSZiZrSsmgaF/fA=,tag:4Gc5chUNnEq2N+e0duHnig==,type:str]
    REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:kq61JRqusNOA5VY+bYlL5QfRsqwPySI=,iv:dVIaxhANMzD/6CqfzxItAjYiSa4MCL8/D6zLRh7Ulwg=,tag:66dWBIXIgxcYuGrYOOQS1w==,type:str]
    CHROME_TOKEN: ENC[AES256_GCM,data:fa+GfZ/Pp4wU6pEB1eRQ9bn7Ow==,iv:v64ZXf8QwTDnHZvgPap79/psRORIcHBkPcAmOOeC6R0=,tag:yjKj1B6o4VG7WcoBNHcSRg==,type:str]
    #ENC[AES256_GCM,data:rHCbal611eIfdJyPtY+NvFd6b/JO46Ms,iv:r7GkntJubvvI4UmeAPi/JocImXXlQPPUxBqj20Xa/cw=,tag:OF0JuzxP1Mn4aIr3nhIcAA==,type:comment]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:z12FziJzHBYbnTMrB+DfikTH50s=,iv:d0DF1HzwffHOH8A6IjRGCBdCrVlPVEdkyRbmCnHmx/c=,tag:9u0/SCr6IqFg7czjL7sTxg==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:NExGwQVDMSMr1zgCFf30UHQPdEP2K4UxKmKUploY+utRdPUiaKNbvw==,iv:zWlmsylVu6GfkZLM44vpCUe2wpGaKybmLoi/7SOqYFw=,tag:GeSnXpFoy4/0BTR5SEXAuw==,type:str]
    #ENC[AES256_GCM,data:VwzaGTU6ExvBBtFbtOzWtQC2QVq0r1SZ,iv:TidM1TqpacS5uf7OwdMykZpmesrJ6IHOSc+U6ekgVaU=,tag:NETVt4u+124h1uWX5I+1cg==,type:comment]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:0CBKDcVUl+5ga8hRWGa8TSLhwHEo+reJXclzp/XgHJhJ6P51IPsBSCOUt6BFIrvsiL1gpDMjjfTWlIOrfNwEnACHEiPJqabk,iv:MEKt5aLGLtCISyl5J0CQCqRcvUUcGeFZlAbd9clrKXc=,tag:iccCvApU7sCdIwYX9O8sHA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:Mvxl+ota9KTgjvLN5Ba66kFwmBsmtyCGWu0WLW1EL1DoMi8=,iv:b3iKGd2IMP74de1Fs7S9ZzZECSIvXbi23KktEV/bx7M=,tag:3ZZxxLmOG991vYh2azTJpA==,type:str]
    #ENC[AES256_GCM,data:vDi8id+E9KQso1gk1nJ3VFwRkcTWxp5I,iv:qjd1XRIe06cO75epJDJcmo1G1mAo+To+ZPotHlEYu8A=,tag:xtpmb1ZEg1W9lKvu8qi1cA==,type:comment]
    OPENID_CLIENT_ID: ENC[AES256_GCM,data:CTcRFR+vyGjEsp8A98WELgwFWVJWuiMkLYGzbKcESyQ64Wb6ZmYSxGpop5dpoVlRMYKeYT7nGASDwzhgKZVseQ==,iv:OFF2M7tvthyHsS3y5sBKpjsQRJzbibEM+FNm613DYKc=,tag:zWvOxKZc40SLMYswTYxI1w==,type:str]
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:gzgsOwBNVHrGeV7JwePkmcOANGE1htG6Lc2m5D0aO0m6lnMUFByIyv23WxSpzUropzrgpVhXNTVezMJ9XAPGCA==,iv:owHc0nlz71omrmdAZAjoniNj/tucz12IpnnzVCxAeJI=,tag:IPdBUIZRiJ02KrD50e+bTQ==,type:str]
    OPENID_AUTHORIZATION_URL: ENC[AES256_GCM,data:j58cMhPxRUWJ3C7u4CVWMPyNZ+xlNrns6+M7aneWghu3Yfp5TNJIOXLOjW9P/fvDvguvgsQBGIngf1QunJFpyV/ls4Nxohx9jd0ERVhBfYdYwr+fZ0JYyt4U7Q+36ULYNSUKCY4LKHXLupHm8S5sEFg3xf955808CwIwpmjs9dmpGizwjTv8u55IO1vi,iv:gmQ/IDGC5YGTxqkJ9XGVW0p3jOeypQESCLzeJc2nauc=,tag:aSPsuFAcF/GZ+uGxjJxA6g==,type:str]
    OPENID_ISSUER: ENC[AES256_GCM,data:6yhHXDr7mZR2nXXTuUAOOyu2xBzjFSl+tCIC+jR9x4c9QYIW+q5lwdRtTmiVDBsVW4L+UktwZMCR4rUF3fUYP2jy03nuXroXalK0CcCV6FB6qVwZI99ihY3G+oANBMdyx5GLhRy6X4bqndbC19+rf7Llfwf/jr/ljtv/H/qO+Q==,iv:sEaZC7ToTA90y1A9wfC2sTq99t+zdXY/vis6M3SvsZA=,tag:r+VkXQ+JFygGKkZ9by1CDg==,type:str]
    OPENID_TOKEN_URL: ENC[AES256_GCM,data:aw2YLg0PtZj4V0dPCgVlyMEySXyNs6xZ5inEr18ckVV+yqBzOoiIV3rrz5KSxK8unrzTG8uO7qhYSFRF2aA7LTDH3Zx5n81EhhVVcCaK3zI53HItVHZ2vRfGaAjo1t9JJiLGqvnrd0SCHTQcAKguq6ahPB9NBh8VkjThtKt7FeJCJMinVQ==,iv:gNFxJXgfiHBgAAO9kUzwU5Hw+apj2dMuoF//Fj2zZlQ=,tag:LXQCTliVEv1B6oMEyyaBjQ==,type:str]
    OPENID_USER_INFO_URL: ENC[AES256_GCM,data:ZS0nx7T6yCWkCHvYz3MthPqbgCHiT+HjaYsaHiJ/BVQvODX4LjOSFH2iAZbXZ0mycj99L6y8FeEbr2G24AP4gpD8/rzTsLmEZUOish0MG9XLEWBxToVzEgBMd2t05Xbu6X1sU/5hy/Yyl0jY36lnl6hxGhuOu+WCGZObXmsTPWyyzHqZH044Ng==,iv:eWCuRfnE9tq8XvoFhd7FlO65z+Jz2JgpST38zjqsokk=,tag:JWZ167Uqi4QRf1a3Q2RI0g==,type:str]
    OPENID_SCOPE: ENC[AES256_GCM,data:P+PBq9Nffh9Rsb/ccB5MANCBY3k=,iv:mcfzfP+qvL1BgOuqxV5+rXKbDOGhjUlGzH57QHO46zU=,tag:tkL6D+NclbQej9gXU3dKmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10p70n0z6ter2m7yw2tz55ufhukkxkjkhy9etclfd06fuxqwef46qmr5gwn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVlZieTdIZkhTK2JXbWtL
            RFRxaXNMRnZNS1hqZktkc2ZFQ2VLUk1RVzFFCmhjRG1nYW1EeGFGUURSOXpPdXh4
            VUwrajFjMndHNDNRbjlUOXJ4ZlN0cnMKLS0tIEhNZitsd1k5eTdzR3ZIL0hnQnIx
            QUVHRnUzRHl6aUhKWTBXSzJpSmhLQWMK+rN9fI95jqz1IpVa1sBKfPAgSc9L7riX
            XVHV+/ALd5ujFl/l35giXryuH+3qPw0OdjXGfaKcwfxA9rbJm6RJ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-10T11:40:23Z"
    mac: ENC[AES256_GCM,data:Vykn+HfDMdenLNL2HHPOayBTmL/x3cB1tCgNWwxww8zUibbuEwlSf0hoZOMLs+yVKlpmhTQpWkfzhNJX2W7dJlje60cT7F/EpzqwJCW8HpQOwf3rdRhTiMoGsK2jQZOETPVkELeS/kNkP9lsMMXGz5b1m9+wpywBvl/lsZyLHHs=,iv:InWphtbclejmXcGWM+b4W0X4k1xgcFB1yZI0hTe1Ea0=,tag:ibBFBuTtMT94j2yAX/Mpzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
