apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: xteve
  namespace: media
spec:
  interval: 1m
  chart:
    spec:
      chart: xteve
      version: 8.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    env:
      # -- Set the container timezone
      TZ: Europe/Lisbon
      
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: xteve.nmoura.pt
            paths:
              - path: /
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: 
        secretName: nmoura-pt-tls
        hosts:
          - xteve.nmoura.pt
    
    persistence:
      config:
        enabled: false
        #type: pvc
        #mountPath: /config
        #nameOverride: config
        #readOnly: false
        #accessMode: ReadWriteOnce
        #size: 5Gi
        #retain: true